SA-1588 - Typeahead includes custom reports
SparkPost/2web2ui pull request #1789
Opened 2020-09-03 05:57 UTC by PatrickSison

### What Changed
 - Action/Reducer for API request added
 - Custom autocomplete select added

### How To Test
 - Go to Report Builder
 - On top of report builder, select preset reports
 - Blur and focus typeahead again
   - Field should empty and allow for new typeahead

### To Do
- [ ] Update tests
- [ ] Make list items look correct

2020-09-03 15:39 UTC, bkemper reviewed
This branch has a new console warning.

<img width="1387" alt="Screen Shot 2020-09-03 at 11 39 16 AM" src="https://user-images.githubusercontent.com/1335605/92136530-205f6e80-edda-11ea-9994-0489a426ed0c.png">

2020-09-03 15:41 UTC, bkemper commented on src/components/typeahead/TypeSelect.js
> +            <PopoverActionList open={isOpen} actions={items} maxHeight={maxHeight} />
Looks like this `actions` prop has been deprecated.

<img width="1389" alt="Screen Shot 2020-09-03 at 11 40 20 AM" src="https://user-images.githubusercontent.com/1335605/92136681-4b49c280-edda-11ea-99b2-ccf10817a321.png">

2020-09-11 19:34 UTC, kchu1337 requested changes
There's also a SavedReportSection.test.js that is being skipped because the typeahead got changed to a select. Not sure if you want to look into that or just remove it until later.

2020-09-11 19:34 UTC, kchu1337 commented on src/components/typeahead/tests/TypeSelect.test.js
> +      expect(functionWrapper).toMatchSnapshot();
Does this test really help anything?

2020-09-11 19:35 UTC, kchu1337 commented on src/pages/reportBuilder/components/SavedReportsSection.js
> +          itemToString={report => (report ? report.name : '')}
Seems like this is a catch for if there is no report value. Maybe during initial load?

2020-09-14 19:55 UTC, bkemper commented on src/components/typeahead/tests/TypeSelect.test.js
> +      expect(functionWrapper).toMatchSnapshot();
Nope.

2020-09-15 20:02 UTC, PatrickSison reviewed
Only one main comment on some of the UX.

2020-09-15 20:02 UTC, PatrickSison commented on src/pages/reportBuilder/components/SavedReportsSection.js
> +    <Columns
This is neat

2020-09-15 20:02 UTC, PatrickSison commented on src/store.js
> +const configureStore = initialState => {
What is this for, out of curiosity?

2020-09-15 20:48 UTC, bkemper commented on src/store.js
> +const configureStore = initialState => {
This shouldn't affect how our app functions, but it will allow us to inject state for testing.  For example, I added a `isHibanaEnabled` prop to `<TestApp />`.

2020-09-15 20:49 UTC, bkemper commented on src/components/typeahead/TypeSelect.js
> +    const SuffixIcon = isOpen ? KeyboardArrowUp : KeyboardArrowDown;
I updated the notes in the ticket after a conversation with Aubrey, but this is how she wanted it.

2020-09-16 20:47 UTC, PatrickSison reviewed
Looks good 👍 Can't approve directly though

2020-09-16 20:48 UTC, bkemper approved these changes

2020-09-16 20:48 UTC, merged