FE-1157 - [Dashboard UX Redesign] Incorporate "Signals Deliverability" artwork from Matchbox
SparkPost/2web2ui pull request #1797
Opened 2020-09-09 13:53 UTC by nicklemmon

[FE-1157](https://sparkpost.atlassian.net/browse/FE-1157)

### What Changed

### How To Test

### To Do
- [ ] Any outstanding tasks go here

2020-09-09 15:35 UTC, nicklemmon commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +      );
For now, there are multiple links with the same content, so had to change this to `findByAll`

2020-09-09 15:36 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                <Panel.Section>
Just went ahead and removed the use of `LEGACY` components here since they are all Hibana-only pages.

2020-09-09 15:36 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <Dashboard.Tip>
I thought this was a better name? Also, wanted to use it for the new UI 🤷

2020-09-10 19:45 UTC, kchu1337 requested changes
Really minor stuff, mostly stylistic. If you don't want to address anything, just request another review and I can approve it.

2020-09-10 19:45 UTC, kchu1337 commented on src/components/picture/Picture.js
> +function Picture({ children, role, className }) {
Should we allow className as a prop?

2020-09-10 19:45 UTC, kchu1337 commented on src/pages/dashboardV2/DashboardPageV2.js
>  import { Loading } from 'src/components/loading';
Could add Picture to components index and import both {Picture, Loading} from src/components.

2020-09-10 19:45 UTC, kchu1337 commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <Box backgroundColor="gray.100" height="100%" borderRight="400">
Could add a `collapseBelow` prop but would then need to add a bottomBorder and ideally set up a media query that has the right border when size > md and bottom border when size < md.

2020-09-10 19:45 UTC, kchu1337 commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <Box backgroundColor="gray.100" height="100%" borderRight="400">
Also, not sure if the box background color is working.

2020-09-10 20:20 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <Box backgroundColor="gray.100" height="100%" borderRight="400">
> Could add a collapseBelow prop but would then need to add a bottomBorder and ideally set up a media query that has the right border when size > md and bottom border when size < md.

This would work, but UX actually wants it to not be visible at all on smaller screen sizes. I could handle that with `<Box/>` or `styled-components` but the `Column` wasn't supporting `className` out of the box. I cut a ticket and pushed a fix with Matchbox but just don't have it available yet 🤷‍♂️

2020-09-10 20:21 UTC, nicklemmon commented on src/components/picture/Picture.js
> +function Picture({ children, role, className }) {
This is required to make `styled-components` work! So if I wanted to do this, it would work:
```
const StyledPicture = styled(Picture)``
```

2020-09-10 20:29 UTC, nicklemmon commented
@kchu1337 Addressed your feedback - take another look when you get a minute!

2020-09-10 21:25 UTC, kchu1337 approved these changes

2020-09-11 15:25 UTC, kchu1337 approved these changes
Seems to work. Artwork is gone when screen size is smaller.

2020-09-11 20:18 UTC, kchu1337 approved these changes
LG again

2020-09-11 20:21 UTC, merged