SA-1606 - Subscription limit on reports
SparkPost/2web2ui pull request #1807
Opened 2020-09-15 14:57 UTC by PatrickSison

### What Changed
 -Tooltip shows if limit for reports reached
 - Button for creating new report disabled if limit for reports reached

### How To Test
 - Go to report builder
 - Check appteam
 - Create new report button should be working
 - Create new account
 - Enable user ui option `allow_saved_reports`
 - Button should be disabled
 - Tooltip should exist

### To Do
- [ ] Check usage (since list isn't guaranteed to be the full list)

### Notes
 - Rebased off of SA-1588. Will mark appropriate file changes

2020-09-15 14:59 UTC, PatrickSison commented on cypress/fixtures/billing/subscription/200.get.reports-limited.json
> +{
File added for subscription limit

2020-09-15 14:59 UTC, PatrickSison commented on src/pages/reportBuilder/ReportBuilder.js
> +  useEffect(() => {
Retrieves subscription

2020-09-15 14:59 UTC, PatrickSison commented on src/pages/reportBuilder/ReportBuilder.js
> +      primaryArea={
Tooltip and button disabling

2020-09-15 14:59 UTC, PatrickSison commented on cypress/fixtures/billing/subscription/200.get.json
> +      },
Added higher report limit for default subscription

2020-09-18 21:03 UTC, kchu1337 requested changes
Can you also rebase from master so that only your 1606 commit shows up?

2020-09-18 21:03 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +  const reportsProduct = subscription?.products?.find(({ product }) => product === 'reports');
I think you can move this within the memoization.

2020-09-22 20:14 UTC, kchu1337 reviewed
LGTM, can you just rebase onto master? It might not be necessary since we are squashing commits, but the PR would be cleaner.

2020-09-23 14:47 UTC, kchu1337 approved these changes

2020-09-23 15:09 UTC, merged