FE-1173 - [Domains UX Redesign] Verify Sending/Tracking/Bounce Domain Page
SparkPost/2web2ui pull request #1826
Opened 2020-09-30 20:26 UTC by shrirupa

FE-1173 - [Domains UX Redesign] Verify Sending/Tracking/Bounce Domain Page

### What Changed
 - Added the Verify Sending Domain Page -  https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478910830
 - Added the Verify Tracking Domain Page - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478945610
 - Added the Verify Bounce Domain Page -  https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478945608

### How To Test
 - On creating Sending Domain, Tracking Domain and Bounce Domain you should be redirected to /domains/details/:id/verify-sending, /domains/details/:id/verify-tracking and /domains/details/:id/verify-bounce respectively.
- Currently the form doesn't have support for creating bounce domain, cypress tests should be the best to see this.

### To Do
- [ ] Address feedback
- [ ] Cut a separate ticket for Sending/Bounce Domain -  https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478945612

2020-10-02 05:57 UTC, shrirupa commented
@kchu1337 I have rebased the branch onto master and also updated the above description with the steps https://github.com/SparkPost/2web2ui/pull/1826#issue-495768216.

2020-10-05 15:15 UTC, kchu1337 requested changes
Some minor stuff

2020-10-05 15:15 UTC, kchu1337 commented on src/pages/domains/components/TrackingDnsSection.js
>    let trackingDomain = _.find(trackingDomains, ['domainName', id]) || {};
Not sure if this is working correctly because I don't see the message with a newly created tracking domain

2020-10-05 15:15 UTC, kchu1337 commented on src/pages/domains/components/TrackingDnsSection.js
>    let trackingDomain = _.find(trackingDomains, ['domainName', id]) || {};
Might need to translate it to lowercase.

2020-10-05 15:15 UTC, kchu1337 commented on src/pages/domains/VerifySendingDomainPage.js
> +          isSectionVisible={true}
There's a bunch of typos in this section compared to mocks.

2020-10-06 15:14 UTC, shrirupa commented on src/pages/domains/components/TrackingDnsSection.js
>    let trackingDomain = _.find(trackingDomains, ['domainName', id]) || {};
Good catch! Corrected it 3 other places too.

2020-10-06 17:48 UTC, kchu1337 requested changes
One last typo, then it's good.

2020-10-06 17:48 UTC, kchu1337 commented on src/pages/domains/components/VerifyEmailSection.js
>              you click verify on the recieved you can send email from this domain, but SparkPost will
`verify on the email received`

2020-10-07 14:50 UTC, kchu1337 approved these changes

2020-10-07 14:52 UTC, merged