FE-1194 - Add the Modal for Domain Alignment
SparkPost/2web2ui pull request #1830
Opened 2020-10-06 20:52 UTC by shrirupa

FE-1194 - Add the Modal for Domain Alignment

### What Changed
- Added the Modal as in the mocks. This modal shows up when user clicks on Save and Continue for a sending domain.

- If the user clicks on ‘Yes’ for ‘Strict Alignment’ then redirect to Sending/Bounce Verification Page - domains/details/:id/verify-sending-bounce

- if the user clicks on ‘No’ for ‘Strict Alignment’ then redirect to Sending Verification Page - domains/details/:id/verify-sending

mock - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/479035680

### How To Test
 - Create a Sending Domain from /domains/create and Select Yes or No and check if it redirects to the correct page

### To Do
- [ ] Address feedback

2020-10-07 13:52 UTC, shrirupa commented on src/pages/domains/components/CreateForm.js
> +      />
I wish these diffs were better I only added `<>` and `<DomainAlignmentModal>`

2020-10-07 17:58 UTC, nicklemmon requested changes
@shrirupa I left some feedback for you. Let me know what questions you have!

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +          </Button>
It looks like the modal form elements should be disabled while the request is pending - _or_ use a loading spinner inside the modal. I think we have tended to do the latter? Not sure what the UX preference is though.

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +            <Text as="p">
This should default to a paragraph? I don't think you have to declare it as such.

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +              <Text as="span" fontWeight="semibold">
You should be able to use the global `<Bold />` component here.

```js
import { Bold } from 'src/components/text'

<Bold>Text goes here</Bold>
```

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +        <Modal.Header showCLoseButton>Domain Alignment</Modal.Header>
Looks like a typo? `showCLoseButton` - yet the button is still showing! That's odd!

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +    <form onSubmit={handleSubmit(onSubmit)} id="domainAlignmentForm">
Semantically I believe the `<form>` should render inside the `<Modal/>` so that it can be interpreted correctly. If that doesn't work with the component as it works now, we should follow up with Jon.

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/CreateForm.js
> +      />
This did the trick for me! Don't know why it doesn't default to checked, though.

<img width="291" alt="Screen Shot 2020-10-07 at 1 54 10 PM" src="https://user-images.githubusercontent.com/3613392/95368827-a3c22300-08a4-11eb-8185-77a916342236.png">

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +    <form onSubmit={handleSubmit(onSubmit)} id="domainAlignmentForm">
I guess one option is to just wrap the `<Radio.Group>` with `<form></form>` and then that `form=""` attribute on the submit button should do the trick?

2020-10-07 17:58 UTC, nicklemmon commented on cypress/tests/integration/domains/createPage.spec.js
> +      });
Nice. Your tests look really great. Well done!

2020-10-07 17:58 UTC, nicklemmon commented on src/pages/domains/components/DomainAlignmentModal.js
> +        <Modal.Header showCLoseButton>Domain Alignment</Modal.Header>
Hmm, the button is showing but closing isn't working! Try clicking it and see if that's happening for you. Not sure if that's related to the typo or not.

2020-10-08 15:24 UTC, shrirupa commented on src/pages/domains/components/CreateForm.js
> +      />
Thanks! this is definitely much better diff now.

2020-10-08 17:49 UTC, shrirupa commented on src/pages/domains/components/DomainAlignmentModal.js
> +        <Modal.Header showCLoseButton>Domain Alignment</Modal.Header>
corrected the typo and added the onClose to ` <Modal>`.

2020-10-08 17:50 UTC, shrirupa commented on src/pages/domains/components/DomainAlignmentModal.js
> +              <Text as="span" fontWeight="semibold">
Nice!

2020-10-08 18:00 UTC, shrirupa commented on src/pages/domains/components/DomainAlignmentModal.js
> +    <form onSubmit={handleSubmit(onSubmit)} id="domainAlignmentForm">
ok, I was confused about which is correct html `form inside modal` or `modal inside form`.

2020-10-08 19:50 UTC, nicklemmon approved these changes
@shrirupa Much better! Looks good to me.

2020-10-08 19:53 UTC, merged