SA-1681: API request and reducer
SparkPost/2web2ui pull request #1833
Opened 2020-10-07 18:39 UTC by PatrickSison

### What Changed
 -API request uses new query params
 - Form initializes with report options from URL

### How To Test
 -  Go to report builder (hibana)
 - Enable account UI feature flag `allow_report_filters_v2`
 -  Click `Add FIlters`
 - Verify form works correctly
 - Apply filters
 - Verify that request attaches filters under query param `query_filters`
 - Click `Add Filters`
 - Verify that filters form is correct as what was applied
 - Refresh page
 - Click `Add Filters`
 - Verify that filters form is correct as what was applied.

### To Do
- [ ] Update tests
- [ ] Verify it works with actual API
- [ ] Address feedback

2020-10-07 20:49 UTC, nicklemmon requested changes
@PatrickSison A few things to take a look at - let me know what you think. I don't think I see anything inherently problematic, but a few things to think about/discuss.

Nice work! It works well.

2020-10-07 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/helpers/index.js
> +};
I believe we have this sort of mapping repeated in several places? Looks like it's in `FiltersForm` in a way (my fault there) and also in `src/helpers/metrics`?

2020-10-07 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/ReportOptions.js
> +  isComparatorsEnabled: selectCondition(isAccountUiOptionSet('allow_report_filters_v2'))(state),
We should use this instead of the `<AccessControl />` component to conditionally render the new filters form - remove some complexity while we're here.

2020-10-07 20:49 UTC, nicklemmon commented on src/reducers/subaccounts.js
> +      return { ...state, status: 'error', listLoading: false, listError: payload };
I see what you did there. Should have been doing this all along!

2020-10-07 20:49 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/analyticsReportFiltersForm.spec.js
> +      cy.findByText('Fake Subaccount 2 (ID 102)').should('be.visible');
I think it would probably be valuable to check for more than just these two tags in the form? Like make sure the other form controls you're expecting are rendering as well?

2020-10-07 20:49 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/analyticsReportFiltersForm.spec.js
> +      cy.findByText('Fake Subaccount 2 (ID 102)').should('be.visible');
Also, should there be another test just starting with a `cy.visit()` with the query parameters applied and verifying the form state from that?

2020-10-07 20:49 UTC, nicklemmon commented on src/reducers/subaccounts.js
> +      return { ...state, ready: true, listLoading: false, list: payload };
🤔 Not `status: 'success'`?

2020-10-07 20:54 UTC, PatrickSison commented on src/reducers/subaccounts.js
> +      return { ...state, ready: true, listLoading: false, list: payload };
Issue is that loading the subaccounts needs to happen at least once. Typeahead keeps retriggering, which chains effects and ends up resetting the filters form

2020-10-07 20:59 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/analyticsReportFiltersForm.spec.js
> +      cy.findByText('Fake Subaccount 2 (ID 102)').should('be.visible');
👍

2020-10-08 14:55 UTC, nicklemmon requested changes
@PatrickSison Looks good other than the weird loading state issue on `/signals/analytics` - and looks like some failing tests. Fixing and we can get it done 👍

2020-10-08 14:55 UTC, nicklemmon commented on src/pages/reportBuilder/helpers/index.js
> +import { FILTER_KEY_MAP } from 'src/helpers/metrics';
👍

2020-10-08 14:55 UTC, nicklemmon commented on src/pages/reportBuilder/helpers/index.js
> +const getFilterType = value => {
👏

2020-10-08 14:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/ReportOptions.js
> +                {isComparatorsEnabled ? (
👏

2020-10-08 21:04 UTC, nicklemmon approved these changes
@PatrickSison Looks good! Let's deploy first thing tomorrow.

2020-10-09 14:01 UTC, merged