SA-1732: Fix Summary Report precision & date range with metrics rollup on initial load
SparkPost/2web2ui pull request #1841
Opened 2020-10-09 21:46 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-10-13 17:34 UTC, kchu1337 commented on src/helpers/metrics.js
> +const _getPrecisionOptions = _.memoize(diff => {
Found out, the UI was making this call multiple times, so I memoized it.

2020-10-13 17:36 UTC, kchu1337 commented on src/pages/reportBuilder/components/DateTimeSection/PrecisionSelector.js
> +    if (from && to && selectedPrecision) {
Added this, so the side-effect doesn't get called before the reportOptions gets populated by URL params or default params.

2020-10-13 17:38 UTC, kchu1337 commented on src/components/datePicker/DatePickerNew.js
> +  const getPrecision = props.useMetricsRollup ? getRollupPrecision : getRawPrecision;
Precision stuff was added to the other datepicker in a previous ticket and I am adding them to this one now.

2020-10-13 17:39 UTC, kchu1337 commented on src/components/datePicker/DatePickerNew.js
> +  const { updateShownPrecision } = props;
This will update the precision selector to show the correct precision while selecting a new date.

2020-10-16 15:35 UTC, nicklemmon reviewed
@kchu1337:

- [x] The OG summary report bug is fixed
- [x] The datepicker still works on the Blocklist feature

I'm confused about how the precision `<select/>` updates when using the datepicker? When I click between the options on the lefthand side of the datepicker the precision value changes, but seemingly randomly. I don't quite understand what the requirement is.

2020-10-19 14:38 UTC, kchu1337 commented on src/components/datePicker/DatePickerNew.js
> +  max-width: 38.5rem;
Not sure, copied from the other one.

> @kchu1337:
> 
> * [x]  The OG summary report bug is fixed
> * [x]  The datepicker still works on the Blocklist feature
> 
> I'm confused about how the precision `<select/>` updates when using the datepicker? When I click between the options on the lefthand side of the datepicker the precision value changes, but seemingly randomly. I don't quite understand what the requirement is.

If the current selected precision is allowed, keep that precision. If that precision is not allowed, use the recommended precision.

2020-10-20 13:19 UTC, nicklemmon requested changes
@kchu1337 I think I would be more comfortable moving forward if we had some automated testing to support this change? That would also help document what the intended requirement is for the feature.

Also, did you see my comment about `max-width: 38.5rem`? Is there a `sizing` design token value we could use there instead?

2020-10-26 20:41 UTC, nicklemmon requested changes
@kchu1337 Left a few comments for you - I'm still able to get unusual precision results by clicking between the different date ranges on the lefthand side of the date picker. Not sure if that's expected, or if I am doing something wrong?

2020-10-26 21:39 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/dateAndTimeSection.js
> +      cy.findByText('Apply').click({ force: true });
Looking at the visual from the cypress runner, I don't think the datepicker is even opening up correctly. So it's in the DOM but out of view, which is why I used `force`

2020-10-27 13:17 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/dateAndTimeSection.js
> +      cy.findByText('Apply').click({ force: true });
Weird!

2020-10-27 14:26 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/dateAndTimeSection.js
> +      cy.get('[aria-label="Tue Dec 03 2019"]').trigger('mouseover', { force: true });
Nope, it doesn't seem to work.

2020-10-27 14:28 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/dateAndTimeSection.js
> +      cy.findByText('Apply').click({ force: true });
Also `cy.findByRole('button', { name: 'Apply' }).click({ force: true });` doesn't seem to work either.

2020-10-27 16:01 UTC, nicklemmon approved these changes
@kchu1337 Let's do it

2020-10-27 16:11 UTC, merged