SA-1721: Add filter link works for comparators table
SparkPost/2web2ui pull request #1843
Opened 2020-10-13 15:43 UTC by PatrickSison

### What Changed
 - Group by table adds filters for new filter structure

### How To Test
 - On hibana account with feature flag `allow_report_filters_v2`, go to `/signals/analytics`
 - Go to bottom group by table and select a filter
 - Go to group by table
 - Click link to add filter
 - Verify that link adds filter to the table

### To Do
- [ ] Address feedback

2020-10-14 19:48 UTC, nicklemmon requested changes
@PatrickSison Seeing some unusual behavior with the table rendering an empty state?

Also, I think we could stand to have more testing backing this one up.

2020-10-14 19:48 UTC, nicklemmon commented on src/pages/reportBuilder/components/AddFilterLink.js
> +      addFilters(newFilter);
Much better

2020-10-14 19:48 UTC, nicklemmon commented on src/pages/reportBuilder/context/ReportBuilderContext.js
> +    }
For some reason adding a new filter from the group by table causes the table to refresh and then show an empty state?

<img width="1085" alt="Screen Shot 2020-10-14 at 3 42 14 PM" src="https://user-images.githubusercontent.com/3613392/96037543-f915ab80-0e33-11eb-8611-79577c7fc74a.png">

2020-10-14 19:48 UTC, nicklemmon commented on src/pages/reportBuilder/components/tests/AddFilterLink.test.js
> +    expect(addFilters).toHaveBeenCalledWith({ id: 10, type: 'Subaccount', value: 'submarine' });
It looks like the integration tests are testing this behavior, but only the old implementation. We should probably add some that test the new implementation as well.

2020-10-15 12:25 UTC, PatrickSison commented on src/pages/reportBuilder/context/ReportBuilderContext.js
> +    }
Not sure how this was working in the first place, but requests are coming from 2 separate places (group by table, and the main `refreshReportBuilder`. The group by table request is not properly attaching filters to the request and doesn't seem like it has been. Will update and add testing around this.

2020-10-15 13:23 UTC, PatrickSison commented on src/helpers/metrics.js
> +    options.query_filters = filters.length ? JSON.stringify({ groupings: filters }) : undefined;
This adds the actual API request query param. It's real

2020-10-15 13:24 UTC, PatrickSison commented on src/actions/summaryChart.js
> +        { isComparatorsEnabled },
This was missing and causing weird empty state behavior

2020-10-15 15:29 UTC, nicklemmon requested changes
@PatrickSison I found an issue - though I'm a little unsure what the UX expectation is!

2020-10-15 15:29 UTC, nicklemmon commented on src/helpers/metrics.js
> +    options.query_filters = filters.length ? JSON.stringify({ groupings: filters }) : undefined;
Nice!

So I'm seeing some errors for some of the "Break Down By" options - I think the `value` for each option is slightly different than what the API expects? When I selected "Sending IP" from the dropdown:

<img width="459" alt="Screen Shot 2020-10-15 at 11 21 28 AM" src="https://user-images.githubusercontent.com/3613392/96151021-f8832080-0ed8-11eb-8fb3-641b9d2db926.png">

2020-10-15 15:29 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/analyticsReportFiltersForm.spec.js
>    });
Nice. Really good test here.

2020-10-15 15:29 UTC, nicklemmon commented on src/helpers/metrics.js
> +    options.query_filters = filters.length ? JSON.stringify({ groupings: filters }) : undefined;
It looks like this happens after adding one "Break Down By" filter. So steps to reproduce:
1. Select "Break Down By" -> "Campaign" and choose one of the campaigns
2. Then try and select any other "Break Down By" option

To be honest, the UX for this whole table is very confusing to me. It wouldn't be clear to me on its face whether clicking another option in the table would add to or replace the existing filter 🤷‍♂️

2020-10-15 19:32 UTC, nicklemmon approved these changes
@PatrickSison Looks good - let's make sure tests pass, then move forward.

2020-10-15 20:42 UTC, merged