FE-1204 -
SparkPost/2web2ui pull request #1855
Opened 2020-10-19 18:55 UTC by nstanard

### What Changed
 - Disable the `Authenticate for Bounce` and `Authenticate for SPF` buttons until they select the checkbox
 - Disable the `Update Tracking Domain` button unless they actually change the select value

### How To Test
 - Go to the Domain Details page `http://localhost:3100/domains/details/{domain_name}`

Picture of the `Authenticate for Bounce` button disabled since the checkbox is not selected.
![image](https://user-images.githubusercontent.com/4204806/96498990-677eb300-1212-11eb-9676-b8d0116328ec.png)

 - `Authenticate for Bounce` and `Authenticate for SPF` buttons are disabled when the checkbox above them are not selected; enabled when the checkbox is selected.

 - `Update Tracking Domain` button is disabled until the select dropdown value changes. 

### To Do
- [ ] Review Feedback

2020-10-20 19:44 UTC, nstanard commented on src/actions/tests/trackingDomains.test.js
> +// TODO: Finish the tests for tracking domains actions
I didn't fill these in, just skipped em for now. Shouldn't be hard but just not really what this task is about.

2020-10-20 19:47 UTC, nstanard commented on src/actions/tests/__snapshots__/sendingDomains.test.js.snap
> +exports[`Action Creator: Sending Domains  chained dispatches Action Creator: Sending Domains Update should request with correct post data 1`] = `
So now we can snapshot chained dispatch events that happen in action functions.

2020-10-20 19:49 UTC, nstanard commented on src/__testHelpers__/snapshotActionHelpers.js
> +export async function snapshotAction({ actionCreator, state = {} }) {
This is the main change that caused the file list to grow.

2020-10-20 19:50 UTC, nstanard commented on src/actions/sendingDomains.js
> +  const shared = data.shared_with_subaccounts;
This is the change that prompted me to enhance `src/__testHelpers__/snapshotActionHelpers.js`

2020-10-20 19:51 UTC, nstanard commented on src/actions/tests/sendingDomains.test.js
> +    jest.mock('../helpers/sparkpostApiRequest', () => jest.fn(a => a));
There's probably a simpler way to mock `sparkpostApiRequest`. I'm seeing we have a _mock_ file for it but also lots of test files just directly mock it.

2020-10-20 19:52 UTC, nstanard commented on src/actions/tests/sendingDomains.test.js
> +    jest.mock('../helpers/sparkpostApiRequest', () => jest.fn(a => a));
Also I was mocking it for each describe block at first, but that was just because I was testing jest mocking and we could probably move this line to the top of the file instead of at the top of each describe block.

2020-10-20 21:50 UTC, nstanard commented
Did we want to use the`ShareWithSubaccounts` component for the DomainStatusSection?

2020-10-20 21:54 UTC, nstanard commented on src/actions/sendingDomains.js
> +  const shared = data.shared_with_subaccounts;
Andddddd now it turns out this change wasn't what we needed/wanted. gj me 🙄

2020-10-20 21:55 UTC, nstanard commented on src/__testHelpers__/snapshotActionHelpers.js
> +export async function snapshotAction({ actionCreator, state = {} }) {
Andddd now it turns out this change wasn't actually _needed_ now that the update action in sendingDomains is not chaining dispatch events. But I'd like to still leave this. It was a good exercise and exposed a few tests that needed "improved"

2020-10-22 20:21 UTC, nstanard commented on src/actions/tests/__snapshots__/sendingDomains.test.js.snap
> +        "shared_with_subaccounts": true,
I think I need to revert this - The first time I went through this work I didn't realize that action was for more than just the "share domain with all subaccounts" toggle so I had changed the data param.

2020-10-28 17:47 UTC, shrirupa commented on src/__func__/billing/addIpToExistingPool.test.js
> +  const dedicatedIpButtonPredicate = node =>
just prettier ?

2020-10-28 17:47 UTC, shrirupa commented on src/__func__/billing/addIpToNewPool.test.js
> +  const dedicatedIpButtonPredicate = node =>
just prettier

2020-10-28 18:13 UTC, nstanard commented on src/actions/tests/abTesting.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
This line was changed because we have the __mock__ of that in the action helpers....

https://github.com/SparkPost/2web2ui/pull/1855/files#diff-a32ba1261eb85838069a1f34d0619e81e7811403b4802cd698629b4cc8dcb424L1

2020-10-28 18:15 UTC, nstanard commented on scripts/test.js
>  // Ensure environment variables are read.
linting/prettier

2020-10-28 18:16 UTC, nstanard commented on src/__testHelpers__/fill.js
>    type,
prettier only

2020-10-28 18:24 UTC, nstanard commented on src/actions/auth.js
>   *
prettier

2020-10-28 18:25 UTC, nstanard commented on src/actions/currentUser.js
>  import sparkpostApiRequest from 'src/actions/helpers/sparkpostApiRequest';
prettier

2020-10-28 18:25 UTC, nstanard commented on src/actions/helpers/__mocks__/sparkpostApiRequest.js
> -const mock = jest.fn((action) => action);
prettier

2020-10-28 18:25 UTC, nstanard commented on src/actions/sendingDomains.js
>      type: 'LIST_SENDING_DOMAINS',
prettier

2020-10-28 18:26 UTC, nstanard commented on src/actions/snippets.js
>    sharedWithSubaccounts = false,
prettier

2020-10-28 18:31 UTC, nstanard commented on src/__testHelpers__/snapshotActionHelpers.js
> +      if (e.message === 'dispatch(...).then is not a function') {
This error handling might not be needed at this point - i'll double check that.

2020-10-28 18:32 UTC, nstanard commented on src/actions/auth.js
>   *
prettier

2020-10-28 18:32 UTC, nstanard commented on src/actions/tests/acceptedReport.test.js
>  jest.mock('src/helpers/metrics');
prettier

2020-10-28 18:33 UTC, nstanard commented on src/actions/tests/api-keys.test.js
> +    actionCreator: actions.listApiKeys,
all action -> actionCreator changed are because of the changes to snapshotActionHelper.js

2020-10-28 18:34 UTC, nstanard commented on src/actions/tests/api-keys.test.js
> +    actionCreator: actions.listApiKeys,
Everything else is prettier

2020-10-28 18:35 UTC, nstanard commented on src/actions/tests/currentUser.test.js
> +jest.mock('src/actions/helpers/sparkpostApiRequest', () => jest.fn(a => a));
`, () => jest.fn(a => a)` @shrirupa 🎊 - thanks! I'll remove this one too

2020-10-28 18:44 UTC, nstanard commented on src/actions/tests/trackingDomains.test.js
> +        actionCreator: () => trackingDomains.listTrackingDomains({}),
at some point we need to fill in these action objects/params, but that's not important for this PR

2020-10-28 18:44 UTC, nstanard commented on src/pages/domains/components/TrackingDnsSection.js
> +              Add the{' '}
The mocks had `the` so I changed it 😬

2020-10-28 18:45 UTC, nstanard commented on src/pages/domains/components/TrackingDnsSection.js
> +  const [checked, toggleChecked] = useState(!!unverified);
I think I'll change this to `Boolean(unverified)` instead of `!!unverified`

2020-10-28 18:46 UTC, nstanard commented on src/pages/domains/components/SetupForSending.js
> +              <CopyField
these <Field & <CopyField changes are probably the most important things to double check/test

2020-10-28 18:48 UTC, nstanard commented on src/actions/trackingDomains.js
>      meta: {
prettier

2020-10-28 18:56 UTC, shrirupa commented on src/actions/currentUser.js
> +export function userGivesCookieConsent() {
👍

2020-10-28 18:59 UTC, shrirupa commented on src/actions/tests/accountSingleSignOn.test.js
>  snapshotActionCases('Action: Current User', {
action - >actionCreator + prettier

2020-10-28 19:00 UTC, shrirupa commented on src/actions/tests/dataPrivacy.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:00 UTC, shrirupa commented on src/actions/tests/customReports.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:00 UTC, shrirupa commented on src/actions/tests/blocklist.test.js
> +jest.mock('src/actions/helpers/sparkpostApiRequest');
👍

2020-10-28 19:01 UTC, shrirupa commented on src/actions/tests/billing.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:01 UTC, shrirupa commented on src/actions/tests/messageEvents.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:01 UTC, shrirupa commented on src/actions/tests/metrics.test.js
> +      actionCreator: metrics.fetchMetricsDomains,
👍

2020-10-28 19:02 UTC, shrirupa commented on src/actions/tests/recipientLists.test.js
> +  getRecipientList,
👍

2020-10-28 19:02 UTC, shrirupa commented on src/actions/tests/recipientValidation.test.js
> +  triggerJob,
👍

2020-10-28 19:03 UTC, shrirupa commented on src/actions/tests/report.test.js
> +jest.mock('src/actions/helpers/sparkpostApiRequest');
👍

2020-10-28 19:03 UTC, shrirupa commented on src/actions/tests/scimToken.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:05 UTC, shrirupa commented on src/actions/tests/sendingDomains.test.js
> +const sendingDomains = require('../sendingDomains');
👍

2020-10-28 19:05 UTC, shrirupa commented on src/actions/tests/sendingIps.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:05 UTC, shrirupa commented on src/actions/tests/signals.test.js
> +  formatInputDate: d => d,
👍

2020-10-28 19:06 UTC, shrirupa commented on src/actions/tests/snippets.test.js
> +  updateSnippet,
👍

2020-10-28 19:06 UTC, shrirupa commented on src/actions/tests/subaccounts.test.js
> +    actionCreator: actions.clearSubaccount,
👍

2020-10-28 19:06 UTC, shrirupa commented on src/actions/tests/support.test.js
> +    dispatchMock = jest.fn(a => a);
👍

2020-10-28 19:06 UTC, shrirupa commented on src/actions/tests/templates.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:07 UTC, shrirupa commented on src/actions/tests/trackingDomains.test.js
> +
👀

2020-10-28 19:07 UTC, shrirupa commented on src/actions/tests/webhooks.test.js
> +jest.mock('../helpers/sparkpostApiRequest');
👍

2020-10-28 19:40 UTC, shrirupa commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +  const [selectValueChanged, setSelectValueChanged] = useState(false);
useForm hook has a inbuilt way to do this, we should use that.

2020-10-28 19:41 UTC, shrirupa commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +                      onChange();
and since onChange was called without arguments, the Select wasn't working.

2020-10-28 19:41 UTC, shrirupa commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +                      onChange();
```

onChange={(values) => {
                      setSelectValueChanged(!selectValueChanged);
                      onChange(values);}

```

2020-10-28 19:46 UTC, shrirupa commented on src/pages/domains/components/SetupBounceDomainSection.js
> +  const [checked, toggleChecked] = useState(
same comment as above we should use watch method from useForm instead.

2020-10-28 19:57 UTC, shrirupa commented on src/pages/domains/components/SetupForSending.js
>                <Button variant="primary" onClick={handleVerifyDkim} loading={verifyDkimLoading}>
we need to add that disabling for submit button here too

2020-10-28 20:10 UTC, shrirupa commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +  const [selectValueChanged, setSelectValueChanged] = useState(false);
we don't have to use useState here, `useForm()` has a `getValues`, we can use that instead 

> `const { getValues } = useForm();`
> ...... `<Button variant="primary" type="submit" disabled={!getValues(trackingDomain)}>`

2020-10-28 20:11 UTC, shrirupa commented on src/pages/domains/components/SetupForSending.js
>                <Button variant="primary" onClick={handleVerifyDkim} loading={verifyDkimLoading}>
We also need to make this disabling of Submit button in `SendingAndBounceDomainSection.js`

2020-10-28 20:13 UTC, shrirupa commented on src/pages/domains/components/TrackingDnsSection.js
> +  const [checked, toggleChecked] = useState(!!unverified);
same as above we should set this up as Form and then use watch

2020-10-28 20:17 UTC, shrirupa commented on src/pages/domains/components/TrackingDnsSection.js
> +              <CopyField label="Hostname" value={trackingDomain.domainName} hideCopy={true} />
hideCopy={!unverified}

2020-10-28 20:34 UTC, shrirupa requested changes
There were some places where the submit button wasn't disabled and other useForm related things. I made a PR to this PR for all the changes that I mentioned above https://github.com/SparkPost/2web2ui/pull/1870, please let me know if you have questions.

2020-10-28 20:39 UTC, nstanard commented on src/pages/domains/components/TrackingDnsSection.js
> +              <CopyField label="Hostname" value={trackingDomain.domainName} hideCopy={true} />
🤔  This almost had to be a merge issue from upstream. Or maybe I just missed it. Either way - Thanks!

2020-10-28 20:58 UTC, nstanard commented on src/pages/domains/components/TrackingDnsSection.js
> +  const [checked, toggleChecked] = useState(!!unverified);
Merged all of this and going over digesting/doing a final self review. Thanks again!

2020-10-28 22:01 UTC, nstanard commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +  const { control, handleSubmit, watch } = useForm();
I just need to put a little more time going over these changes and getting familiar with `useForm`. Then I'll put together a solid testing plan for all of this so when we move to staging and production it'll be really simple to hit some URLs and verify things work.

2020-10-29 17:03 UTC, nstanard commented on src/pages/domains/components/LinkTrackingDomainSection.js
> +  const { control, handleSubmit, watch } = useForm();
![image](https://user-images.githubusercontent.com/4204806/97607195-ae249800-19de-11eb-9962-93b1c5c724bc.png)
Ok, I've gone through and given myself a map of url -> state -> button -> .js file

http://localhost:3100/domains/details/josezamora.info
http://localhost:3100/domains/details/test.spappteam.com
http://localhost:3100/domains/details/45.45.45.wer

2020-10-29 18:39 UTC, shrirupa approved these changes
Looks good to me!

2020-10-29 18:50 UTC, merged