Sa 1736
SparkPost/2web2ui pull request #1859
Opened 2020-10-21 22:56 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-10-22 18:00 UTC, kchu1337 commented on src/components/reactHookFormWrapper/ComboBoxTypeaheadWrapper.js
> +    if (value !== componentValue) {
It was breaking my unit test without this. Not sure why. 🤷

2020-10-22 18:05 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const [timezone, setTimezone] = useState(getLocalTimezone());
I just handle these 2 fields without react-hook-form since these types of input are less common and I didn't think it was worth the time/effort to make wrappers.

2020-10-22 18:19 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +export const formatFormValues = formValues => {
I'm not using the first/second/ect week value since theres no way to make a single cronjob that runs on the 1st Friday of every month.
Not adding timezone right now, but I talked with backend team and they said they would implement timezone as parameter since it is easier on their end b/c of the cron-parser library accepting timezone as an option.

2020-10-27 15:09 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const { name, description = 'NA', subject, period, ...rest } = formValues;
They will remove description from the API soon. But right now, it's a required parameter.

2020-10-27 17:56 UTC, nicklemmon requested changes
@kchu1337 Left you some notes - let me know what questions you have for me.

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                  <Text as="p">reports@sparkpost.com</Text>
We have a component for this I believe - `Definition` in `src/components/text`

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                        name="pm"
These should have the same `name` attribute

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +            <Button variant="secondary">Cancel</Button>
This doesn't do anything?

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +      itemToString={item => (item ? `Name: ${item.name} ---- Email: ${item.email}` : '')}
Is this how it's supposed to be formatted? Looks funky. Doesn't match the mocks either:
<img width="636" alt="Screen Shot 2020-10-27 at 1 37 46 PM" src="https://user-images.githubusercontent.com/3613392/97340144-cc14c000-1859-11eb-9f53-503969bce755.png">

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    <RadioButtonGroup id="period" label="Grouping Type">
I'm glad that worked!

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                        name="pm"
I think you wouldn't need the `setPeriod` function as a result? Not sure though.

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                      message: 'Invalid time format, should be hh:mm 12 hour format',
<img width="1068" alt="Screen Shot 2020-10-27 at 1 41 32 PM" src="https://user-images.githubusercontent.com/3613392/97340457-2e6dc080-185a-11eb-8046-0ff140a984c2.png">

The validation works well, but the error rendering is pretty funky. I think this is due to the flex alignment of the `<Inline/>` component?

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/tests/ScheduledReportForm.test.js
> +    expect(screen.getByText('Time Zone')).toBeVisible();
Yaaay no snapshots!

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/tests/ScheduledReportForm.test.js
> +    it('formats form values for daily schedule correctly', () => {
These formatting tests are really great. Very clear.

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +            </Button>
I don't see any form control disabling when the form is submitting? That's definitely needed across the board.

2020-10-27 17:56 UTC, nicklemmon commented on src/components/reactHookFormWrapper/ComboBoxTypeaheadWrapper.js
> +export default function CheckboxWrapper(props) {
I don't think this is supposed to be called `CheckboxWrapper`

2020-10-27 17:56 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const [timezone, setTimezone] = useState(getLocalTimezone());
Would wrappers be needed? I guess I don't understand why the checkbox controls would need it.

2020-10-29 17:42 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                  <Text as="p">reports@sparkpost.com</Text>
There's also a new matchbox component for it as well https://matchbox-storybook.netlify.app/?path=/story/layout-labelvalue--vertical-orientation

2020-10-29 17:48 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                        name="pm"
Oh yeah I got it working. It wasn't working before and when I tried at first but then I realized I set both values to AM due to bad copy+paste.

2020-10-29 17:58 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +      itemToString={item => (item ? `Name: ${item.name} ---- Email: ${item.email}` : '')}
UX said they would prefer if email was available as well. The ideal situation would be something like this: 

![image](https://user-images.githubusercontent.com/25185606/97613180-bf75a080-19ee-11eb-8138-0554eb52fcec.png)

With email replacing `appteam`. But I didn't want to also make changes to the comboboxTypeahead in this ticket.

2020-11-02 16:25 UTC, nicklemmon requested changes
@kchu1337 Things are looking good - I had some minor feedback - looks like the `Definition` component has some slightly off CSS. Not your doing, but we may as well fix it now.

Nice work! The form works well.

2020-11-02 16:25 UTC, nicklemmon commented on src/pages/reportBuilder/ScheduledReportCreatePage.js
> +  const dispatch = useDispatch();
So much better.

2020-11-02 16:25 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +          <ButtonWrapper>
👍

2020-11-02 16:25 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    <Definition.Value>{report.name}</Definition.Value>
<img width="588" alt="Screen Shot 2020-11-02 at 11 15 03 AM" src="https://user-images.githubusercontent.com/3613392/97891408-bccfbf80-1cfc-11eb-800e-5639dcf66f53.png">

This isn't your doing, but the `Definition.Value` component almost definitely has the wrong font size design token.

2020-11-02 16:25 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    <Definition.Value>{report.name}</Definition.Value>
Yeah, inspecting the mocks it should be `18px` which maps to `props.theme.fontSizes[300]` (rather than `400`).

Would you mind updating the component? The text just looks huge right here. I'm sure it does elsewhere too.

2020-11-02 16:25 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    <Definition.Value>{report.name}</Definition.Value>
<img width="679" alt="Screen Shot 2020-11-02 at 11 18 48 AM" src="https://user-images.githubusercontent.com/3613392/97891781-3667ad80-1cfd-11eb-8629-9fc80188e4b5.png">

2020-11-03 15:43 UTC, nicklemmon approved these changes
@kchu1337 and @PatrickSison Looks good!

2020-11-03 16:32 UTC, merged