FE-1184 - Add Deep Link for filter on ListPage and Add Remaining UX feedback updates
SparkPost/2web2ui pull request #1866
Opened 2020-10-27 00:58 UTC by shrirupa

FE-1184 - Add Deep Link for filter on ListPage and Add Remaining UX feedback updates

### What Changed
 - Added [Deeplink](http://localhost:3100/domains/list/sending?readyForSending=true&readyForDKIM=true) for filters on Domains List Page
 - Added [Error state](http://localhost:3100/domains/details/tracking/this.domain.is.not.found) for Details Page (when a certain tracking, bounce or sending domains is not found)
 - Separated the routes for [Sending/Bounce](http://localhost:3100/domains/details/sending-bounce/te.te.te) (details/sending-bounce) and [Tracking](http://localhost:3100/domains/details/tracking/another.newdomain.com) (details/tracking) for details page.
 _This change was made because earlier logic of determining isTracking did not take into consideration when sending/bounce domain has the same name as tracking domain_
- The subaccount names weren't showing up on [Tracking List Page](http://localhost:3100/domains/list/tracking) earlier fixed that 
- Subaccount names weren't showing on[ Details Page](http://localhost:3100/domains/details/sending-bounce/staging-test.spappteam.com) Fixed that 
- Added a Component wrapper for LabelValue
 - UX Feedback updates
     - Added [unverified banner](http://localhost:3100/domains/details/tracking/another.newdomain.com) for unverified tracking domains
     - Rearranged the filters on [List Page](http://localhost:3100/domains/list/sending) of domains to match the mock
     - Changed the Button for Domain Status to look like Select on [List Page](http://localhost:3100/domains/list/sending)
     - Updated "Principal" -> "Master" on [Create Page | Domains](http://localhost:3100/domains/create).
- Added cypress tests for above changes

### How to test
 - Clicking on links in each point should take you to the page which has the said change (links are specific to appteam)

### To Do
- [ ] Address feedback

https://sparkpost.atlassian.net/browse/FE-1184

2020-10-27 16:21 UTC, shrirupa commented on src/config/routes/index.js
> +    path: '/domains/details/sending-bounce/:id',
separated the details pages to sending-bounce and tracking. This change was done because previous method of identifying isTracking wasn't taking into consideration the case when sending/bounce and tracking domain with same name.

2020-10-27 16:21 UTC, shrirupa commented on src/context/RouterContext.js
> +  const value = useMemo(
This is just prettier changes.

2020-10-27 16:22 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +    return (
Added error handling

2020-10-27 16:22 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +  if (
Added error handling when a tracking domains is not found

2020-10-27 16:23 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +          <Banner
Added banner for unverified tracking domain

2020-10-27 16:25 UTC, shrirupa commented on src/pages/domains/ListPage.js
> +    if (matchesSendingTab) {
made earlier code a little more concise with the new hooks from `react-router-dom`

2020-10-27 16:25 UTC, shrirupa commented on src/pages/domains/components/CreateForm.js
> +                          label="Share with all Subaccounts"
Renamed Principal to Master

2020-10-27 16:26 UTC, shrirupa commented on src/pages/domains/components/DomainStatusSection.js
> +                  <Subaccount id={subaccountId} name={subaccountName} />
Added the `<Subaccount/>` component to the Domain Status Section.

2020-10-27 16:26 UTC, shrirupa commented on src/pages/domains/components/DomainStatusSection.js
> +                  <LabelValue label="Status" orientation="vertical">
Used the new `LabelValue` component from matchbox.

2020-10-27 16:27 UTC, shrirupa commented on src/pages/domains/components/SendingDomainsTab.js
> +  const location = useLocation();
Added the query params for filters on List Page of Domains

2020-10-27 16:44 UTC, shrirupa commented on cypress/tests/integration/blocklists/incidents.spec.js
> +  it.skip('changes the date range and makes the correct http call', () => {
not sure why this integration test is failing

2020-10-27 16:45 UTC, shrirupa commented on cypress/tests/integration/domains/detailsPage.spec.js
>  const PAGE_URL = `${BASE_UI_URL}/fake-domain.com`;
rearranged the test here and divided them to tracking and sending/bounce.

2020-10-28 14:35 UTC, kchu1337 requested changes
Left some comments and questions.

2020-10-29 17:16 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +      Boolean(_.find(trackingDomainList, ['domain', match.params.id.toLowerCase()]))
I updated this condition, I had added it earlier because of on the first render the domain hasn't loaded so the page breaks. let me know if the conditions look good to you now.

2020-10-29 17:17 UTC, shrirupa commented on src/pages/domains/ListPage.js
> +  const location = useLocation();
we should move away from using the this custom hook since it is now present in the new version of react-router-dom. https://msys.slack.com/archives/C69L53989/p1603899304131500?thread_ts=1603893427.125800&cid=C69L53989

2020-10-29 18:08 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +          settrackingDomainNotFound(true);
Add a comment here!

2020-10-29 18:08 UTC, shrirupa commented on src/pages/domains/DetailsPage.js
> +          settrackingDomainNotFound(true);
`setTracking`

2020-10-29 19:41 UTC, shrirupa commented on src/pages/domains/components/SendingDomainsTab.js
> +    for (let key in tempFilters) {
This and [this](https://github.com/SparkPost/2web2ui/pull/1866#discussion_r513438656) were very nice feedback, ended up making code lot more concise. Thanks!

2020-10-29 19:43 UTC, shrirupa commented on src/pages/domains/components/SendingDomainsTab.js
>      }
realised that I didn't have to write all that logic there any way.

2020-10-29 19:43 UTC, shrirupa commented on src/pages/domains/components/TrackingDomainsTab.js
> +
https://github.com/SparkPost/2web2ui/pull/1866#discussion_r514431962

2020-10-30 14:34 UTC, kchu1337 requested changes
Some small things.

2020-10-30 14:37 UTC, shrirupa commented on cypress/tests/integration/domains/detailsPage.spec.js
> +      // });
ohh no! Thanks for pointing this out!

2020-10-30 15:13 UTC, shrirupa commented on cypress/tests/integration/domains/detailsPage.spec.js
>          });
done 👍

2020-10-30 15:13 UTC, shrirupa commented on cypress/tests/integration/domains/verifyTrackingDomainPage.spec.js
> +      });
done 👍

2020-10-30 15:31 UTC, kchu1337 approved these changes

2020-10-30 15:38 UTC, merged