Fe 1225
SparkPost/2web2ui pull request #1883
Opened 2020-11-05 00:10 UTC by shrirupa

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-11-09 15:26 UTC, nicklemmon requested changes
@shrirupa A little bit of feedback - I'm going to do some additional testing as well, but these items you can at least take a look at in the meantime.

2020-11-09 15:26 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/tests/SaveReportModal.test.js
> +  ...jest.requireActual('react-router-dom'),
I'm surprised you have to do this?

2020-11-09 15:26 UTC, nicklemmon commented on src/pages/signals/tests/IntegrationPage.test.js
> +  // });
Did you mean to re-introduce this?

2020-11-09 15:26 UTC, nicklemmon commented on src/pages/templates/hooks/useEditorNavigation.js
> +  const [navKeyTemp, setNavKeyTemp] = useState(navKey.toLowerCase());
This is probably a better way to do it, but does the old way not work?

2020-11-09 21:04 UTC, shrirupa commented on src/pages/reportBuilder/components/SavedReportsSection/tests/SaveReportModal.test.js
> +  ...jest.requireActual('react-router-dom'),
Good point! I was able to remove it from most of the places but still couldn't get the useEditorNavigation.test.js working without `jest.requireActual('react-router-dom'),`

2020-11-09 21:33 UTC, shrirupa commented on src/pages/signals/tests/IntegrationPage.test.js
> +  // });
yeah I am still not sure how to get these two unit tests in this file working  🤔

2020-11-09 21:33 UTC, shrirupa commented on src/pages/signals/tests/IntegrationPage.test.js
> +  // });
I am thinking of adding cypress test instead for this page

2020-11-12 16:02 UTC, nicklemmon requested changes
@shrirupa Had a few comments, re: the new Cypress tests. The features impacted appear to be working still

2020-11-16 22:00 UTC, shrirupa commented on cypress/tests/integration/configuration/integrationsPage.spec.js
> +    cy.findByDataId('next-page').click();
yeah, this one looks like an ally bug

2020-11-16 22:01 UTC, shrirupa commented on src/components/matchbox/Pager.js
> +  return <HibanaPager.Previous {...props} data-id="previous-page" />;
right, this looks like an ally bug, but I think till we get this fixed, can we have data-id's here for these test ?

2020-11-16 22:10 UTC, shrirupa reviewed
@nicklemmon this is ready for final pass, whenever you have some time.

2020-11-16 22:33 UTC, shrirupa commented on cypress/tests/integration/configuration/integrationsPage.spec.js
> +    cy.findByText('Review the health of your Signals integration.').should('be.visible');
looks like this is ally bug bug too. PageDescription doesn't have role of heading

2020-11-17 14:22 UTC, nicklemmon commented on src/components/matchbox/Pager.js
> +  return <HibanaPager.Previous {...props} data-id="previous-page" />;
I looked at the components and they do have content within them:
```html
<button type="button" class="sc-bdVaJa sc-jTzLTM bwdivw">
  <span class="sc-jzJRlG hgvSdV">
    <svg></svg>
    <span class="sc-htoDjs hzTsVD">Next</span>
  </span>
</button>
```

You can't grab them with `cy.findByRole('button', { name: 'Next' })`?

2020-11-17 14:23 UTC, nicklemmon commented on cypress/tests/integration/configuration/integrationsPage.spec.js
> +    cy.findByText('Review the health of your Signals integration.').should('be.visible');
Nope, you're right actually - `PageDescription` is just a paragraph, which oddly enough does not have a relevant `role`. My feedback was wrong!

2020-11-17 17:57 UTC, shrirupa commented on src/components/matchbox/Pager.js
> +  return <HibanaPager.Previous {...props} data-id="previous-page" />;
Thanks for fixing this!

2020-11-18 19:02 UTC, nicklemmon approved these changes
@shrirupa Looks good to me!

2020-11-18 19:03 UTC, merged