SA-1847: Update form and tests
SparkPost/2web2ui pull request #1894
Opened 2020-11-10 18:21 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-11-10 20:46 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const day_of_week = timing === 'monthly' ? `${rest.day}${rest.week}` : rest.day || '*';
Monthly timing will be formatted like fri#2 for second friday of the month. Or monl as the last monday of the month. day is set to * when the day field is disabled for daily scheduled reports.

2020-11-10 20:46 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +    day_of_month: '?',
Cron changes needed ? instead of *.

2020-11-12 18:47 UTC, nicklemmon requested changes
@kch Overall looks pretty good! I did notice an issue that seems to be unrelated to this ticket - when I'm searching in the "Send To" field and get no results, the "No results" message renders then quickly disappears.

<img width="620" alt="Screen Shot 2020-11-12 at 1 46 50 PM" src="https://user-images.githubusercontent.com/3613392/98982548-932d4a00-24ed-11eb-921d-5c40857ca184.png">

Other than that, the feedback I have is very minor.

2020-11-12 18:47 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  { label: `First`, value: '#1' },
Don't think you meant to use backticks here?

2020-11-12 18:47 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const day_of_week = timing === 'monthly' ? `${rest.day}${rest.week}` : rest.day || '*';
This comment clarifies things - would you mind adding it to the code rather than just here? I think it would come in handy for future maintainers.

2020-11-12 21:37 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const day_of_week = timing === 'monthly' ? `${rest.day}${rest.week}` : rest.day || '*';
Very helpful, thanks for doing that.

2020-11-13 14:26 UTC, nicklemmon reviewed
@kchu1337 Take a look at my comments - I think I found a bug with the Typeahead changes?

2020-11-13 14:26 UTC, nicklemmon commented on src/components/typeahead/ComboBoxTypeahead.js
> +      error: error && !isOpen ? error : undefined,
<img width="808" alt="Screen Shot 2020-11-13 at 9 21 09 AM" src="https://user-images.githubusercontent.com/3613392/99082049-a5f95a80-2591-11eb-810d-b2532e5be96c.png">

Hmm, looks like this state shouldn't be possible - there should be some user entry required before the empty state renders?

2020-11-13 14:26 UTC, nicklemmon commented on src/components/typeahead/ComboBoxTypeahead.js
> +      error: error && !isOpen ? error : undefined,
To reproduce:
1. Sign in with the usual account in prod
2. Go to `/alerts/edit/71570`
3. Focus on the "Subaccounts" field and "No Results" will render before typing anything

2020-11-13 16:11 UTC, nicklemmon approved these changes
@kchu1337 Looks good to me. Thanks.

2020-11-13 16:23 UTC, merged