FE-1211 - Verify Sending Domain Onboarding
SparkPost/2web2ui pull request #1895
Opened 2020-11-10 22:42 UTC by nstanard

### What Changed
 - _coming soon_

### How To Test
 - _coming soon_

### To Do
- [ ] Feedback

2020-11-16 21:19 UTC, nicklemmon requested changes
@nstanard I left you a few things to chew on. The feature appears to work as expected on the surface, though there are some issues I highlighted that could result in bugs down the road.

👍 Let me know what questions you have.

2020-11-16 21:19 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +  );
See my comments a little further down, but you shouldn't need to use state management for any of these.

2020-11-16 21:19 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                        </ExternalLink>
Same here - you can leverage the `<Stack/>` component instead of managing space between each element.

2020-11-16 21:45 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                {!addSendingDomainOnboarding && !verifySendingDomainOnboarding && (
This has been done FE-1214 already based on conversation with @PatrickSison

2020-11-16 21:46 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +  );
This part has been addressed on FE-1214 already - where all onboarding steps come together.

2020-11-16 21:53 UTC, nstanard commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +    it('onboarding step two - one unverified sending domain', () => {
Adjusting this on FE-1214 accounting for all onboarding steps.

2020-11-16 21:54 UTC, nstanard commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +      cy.title().should('include', 'Dashboard');
Adjusted on FE-1214

2020-11-16 21:57 UTC, nstanard commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +        .and('include', '/details/sending-bounce/sparkspam.com');
much nicer!

2020-11-16 22:04 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                        <Text pb="600">
Good to know!

2020-11-16 22:04 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                          size="default"
Removed all on FE-1214

2020-11-16 22:05 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                          data-id="onboarding-verify-sending-button"
Gone!

2020-11-16 22:06 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +    }
I'll take a look at doing this while looking into calling into the action in the container too.

2020-11-16 22:18 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
>      // TODO: FE-1212
https://github.com/SparkPost/2web2ui/pull/1899/commits/ec294abcf4741eb14fa20a6f0888be37c510dc00 - All comments that I've flagged as resolved have been added to FE-1214. Now I'll take a look at moving the API calls up to the container level.

2020-11-16 23:45 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
>      // TODO: FE-1212
Ok - This all makes sense. Getting adjusted now.

2020-11-17 15:46 UTC, nstanard commented
closing in favor of FE-1214

2020-11-17 15:46 UTC, closed without merging