FE-1234 - Last few cleanup items on domains page
SparkPost/2web2ui pull request #1897
Opened 2020-11-12 20:50 UTC by shrirupa

FE-1234 - Last few cleanup items on domains page

### What Changed

- Visually hide the Apply button
- Added Select all checkbox for domain status filter
- Input placeholder text for domain name
- Sending domain tab  - Rename Sending -> Verified in Domain status filter
- Bounce Domain tab - Remove Bounce from the list
- Tracking domain tab  - Rename Tracking -> Verified in Domain status filter

### How To Test
 - testing if all the above changes look good 
mock - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478910828

### To Do
- [ ] Addressing feedback

2020-11-12 21:28 UTC, nicklemmon requested changes
@shrirupa - it works well, though I have a few concerns:

1. I think we need some new testing for some of the changes here
2. Making the "Apply" button visually hidden actually defeats the purpose if it being there - I left some notes about a possible alternative, but I don't think it's as good as the existing design.

2020-11-12 21:28 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +        </VisuallyHiddenBox>
Hmm, the purpose of the button is that it is actually there visually - screen reader users can always close the popover with the escape key. When it's wrapped in `<ScreenReaderOnly>` I believe it is removed from the tab order anyways - and even if it weren't, that would break the experience for users who are _not_ blind but use the keyboard to navigate pages. If UX wants this design, it would be best to remove the button and have some directions at the top of the checklist wrapped in `<ScreenReaderOnly>`. For example:

```
<ScreenReaderOnly as="p">
  Checkboxes filter the table. When checked, table elements are visible, when unchecked they are hidden from the table.
</ScreenReaderOnly>
```

I'm not sure if that's actually the behavior of the filtering?

This is actually why I advocated for just having the `<button/>` as it removes some of the complexity, and makes maintenance easier as you don't have to think about updating that content if the filter behavior changes.

2020-11-12 21:28 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +              .map((filter, index) => (
Probably want to have some testing checking the different types of checkboxes depending on the selected tab, right? Just seems like something that could be accidentally broken in the future.

2020-11-12 21:28 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +            key="select-all"
I don't think this needs a `key`? You may have a reason for having one here.

2020-11-12 21:28 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +      if (action.name === 'selectAll' && !isChecked) {
Should have some testing around this as well - could maybe even add it to an existing test

2020-11-12 21:28 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +
Actually, read my later comments - I don't think this is necessary either way. 👇

2020-11-12 22:25 UTC, shrirupa commented on src/pages/domains/components/TableFilters.js
> +        </VisuallyHiddenBox>
Thanks for explaining this! I will go ahead and add `ScreenReaderOnly` text then and remove the Apply button.

2020-11-13 14:18 UTC, nicklemmon approved these changes
@shrirupa Looks good to me. Let's get it out.

2020-11-13 14:18 UTC, nicklemmon commented on src/pages/domains/components/TableFilters.js
> +          </ScreenReaderOnly>
This is great! 👍

2020-11-13 14:18 UTC, nicklemmon commented on cypress/tests/integration/domains/listPage.spec.js
> +      });
👍 Nice.

2020-11-13 14:50 UTC, merged