FE-1214 - [Dashboard] Analytics Report onboarding fallback
SparkPost/2web2ui pull request #1899
Opened 2020-11-12 23:14 UTC by nstanard

Epic: https://sparkpost.atlassian.net/browse/FE-1185
Task: https://sparkpost.atlassian.net/browse/FE-1214

Branched From: https://github.com/SparkPost/2web2ui/pull/1898
Compare of upstream branch: https://github.com/SparkPost/2web2ui/compare/FE-1216...FE-1214

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-11-13 17:24 UTC, nstanard commented
FE-1209 - Comments being resolved on this PR
https://github.com/SparkPost/2web2ui/pull/1888#pullrequestreview-527390945

useReducer change coming soon

2020-11-17 19:28 UTC, nicklemmon requested changes
@nstanard Have a few feedback items for you - let me know what questions you have.

(And you were totally right - this isn't too big to review all at once)

2020-11-17 19:38 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                  {onboarding === 'addSending' && (
Yea; this was already a piece of feedback I was incorporating from FE-1209. 👍

2020-11-17 19:39 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    .filter(Boolean);
Good callout. Just haven't built the habit of checking for existing selectors.

2020-11-17 19:50 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                            Need help integrating? Want to share Analytics Report? Invite your team!
Yea I must have typed this one out I assume. Good eye!

2020-11-17 20:07 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +  lastUsageDate = state?.account?.rvUsage?.messaging?.last_usage_date;
I wasn't completely sure what the differences were between the usage and rvUsage objects. There's also a `timestamp` property. But I'm fairly certain the last_usage_date is the correct thing to check for what we are doing here.

2020-11-17 20:09 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              Create an API key in order to start sending via API or SMTP.
One annoyance I've found so far is stacking text broken up by different formats and then testing it with Cypress. It'd be nice if the rules around bare strings and spaces weren't conflicting so often.

```
<Text>
    <TranslatableText>Create an </TranslatableText>
    <Abbreviation title="Application Programming Interface">
    API
    </Abbreviation>
    <TranslatableText>
    key in order to start sending via API or SMTP.
    </TranslatableText>
</Text>
```

2020-11-17 20:22 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              Create an API key in order to start sending via API or SMTP.
used a span element to get the space needed

2020-11-17 20:23 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    onboarding = 'startSending';
Something to bring up to UX. The specs drawn up have this startSending onboarding step be the last visible for admin || dev while the "fallback" onboarding state is for non-admin and non-dev users.

2020-11-17 20:35 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    onboarding = 'startSending';
Although. If you have sent before.... I don't think you should be seeing any of the onboarding steps. That state should (once the tasks have been worked) show the pinned report. Since the pinned report work isn't done yet though I'd imagine you'd be seeing nothing - let me know when you have a moment.

2020-11-17 20:50 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    onboarding = 'startSending';
K, actually this makes sense. I made an adjustment so it's _even better_ than before.

2020-11-17 20:52 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    onboarding = 'startSending';
yep, when I sign in with the usual testing account, I actually see nothing at all, which is probably the expectation.

But that account does have some RV usage (recipient validation) which is a totally distinct feature from sending.

2020-11-17 20:55 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              Create an API key in order to start sending via API or SMTP.
Yeeeah - you should use something like the `nbsp;` character - I don't think a `<span/>` is correctly parsed as a space.

And that is annoying. I actually learned something from Shrirupa earlier - it looks like if you use `cy.contains()` you can check for text that is broken up in to multiple elements more easily.

2020-11-17 20:56 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +  lastUsageDate = state?.account?.rvUsage?.messaging?.last_usage_date;
I absolutely love how this all turned out. Super clean and well organized. State management in the container layer and cypress test coverage. Great feedback. Cypress driven development is rather empowering.

2020-11-17 21:34 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +  lastUsageDate = state?.account?.rvUsage?.messaging?.last_usage_date;
https://sparkpost.atlassian.net/browse/FE-1249 - i wanna handle this part on it's own so I can better isolate the development and testing of it.

2020-11-17 21:58 UTC, nicklemmon requested changes
@nstanard Totally my fault - I missed a few things on the last pass - but everything is shaping up nicely. After one more round, I can approve and we can move forward.

I'm still a little unclear about when the usage data shows you have recently sent a transmission - on the usual test account it works correctly, but on my personal account it doesn't appear to me. Might warrant more testing before we remove the feature flag.

Nice work - this looks really good. A much better experience than what we currently offer.

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                                key in order to start sending via API or SMTP.
Looks like "SMTP" still needs to be wrapped in `<Abbreviation />`

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              <TranslatableText> DNS settings.</TranslatableText>
Oops! Missed this one. Could use `<Abbreviation/>` here as well.

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +  if (pending) return <Loading />;
👏  Much more clear here

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
>      getAccount({ include: 'usage' });
You may not even need this request anymore - though I know you didn't introduce in your PR. Your invocation of `getUsage()` _should_ get you what you need, though if you don't want to deal with that at this point in time I understand.

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.container.js
> +    isDev,
You cleaned this up nicely.

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              </ExternalLink>
Is this supposed to be an `ExternalLink`?

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                            </ExternalLink>
Same here, I think this should just be a `<PageLink/>` - usually when we are leaving the app we use `<ExternalLink/>` but just `<PageLink/>` when it's an internal route change.

2020-11-17 21:58 UTC, nicklemmon commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +          .should('have.attr', 'href', 'https://www.sparkpost.com/inbox-tracker/');
There are a few more of these where you could use `cy.verifyLink()` both right here and earlier in the file

2020-11-17 21:58 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              SMTP.
More `<Abbreviation/>` instances would be nice here

2020-11-17 22:42 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                            </ExternalLink>
Yea...... copy paste without looking close enough cause they're visually the same and worked 😓

2020-11-17 22:47 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              </ExternalLink>
Yea :( more copy paste

2020-11-17 22:55 UTC, nstanard commented on src/pages/dashboardV2/DashboardPageV2.js
> +                              Create an API key in order to start sending via API or SMTP.
`cy.get('p').contains('Create an API key in order to start sending via API or SMTP.');`

<3 <3 <3

2020-11-18 14:30 UTC, nicklemmon approved these changes
@nstanard Looks good to me! Thanks for going back and for with me on this one.

2020-11-18 14:30 UTC, nicklemmon commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +      cy.get('p').contains('Create an API key in order to start sending via API or SMTP.');
Normally I'm not a huge fan of grabbing HTML elements, but in this case, it makes perfect sense. 👍

2020-11-18 17:40 UTC, merged