[FE-1237] - The domains page should be visible to user with either tracking_domains/manage or sending_domains/manage grant
SparkPost/2web2ui pull request #1900
Opened 2020-11-16 18:19 UTC by shrirupa

[FE-1237] - The domains page should be visible to user with either tracking_domains/manage or sending_domains/manage grant

### What Changed
 - Added the condition with grant to domain pages

### How To Test
 - Domains page shouldn't be visible to Templates, Reporting and Subaccount Reporting user.

### To Do
- [ ] Address feedback

2020-11-16 19:40 UTC, shrirupa commented on cypress/tests/integration/domains/listPage.spec.js
> +      cy.findByRole('tab', { name: 'Tracking Domains' }).click({ force: true });
for some reason chaining was causing the issue locally.

2020-11-16 20:07 UTC, nicklemmon requested changes
@shrirupa I have a few comments I left for you.

One more thing - should the tabs on `src/pages/domains/ListPage` render conditionally as well? Right now _technically_ a user could see the tab for "Tracking Domains" but only have the grand for sending domains.

2020-11-16 21:44 UTC, shrirupa commented on src/config/navItems/index.js
> +  condition: any(hasGrants('sending_domains/manage'), hasGrants('tracking_domains/manage')),
ok, as we discussed I am adding, `all(hasGrants('tracking_domains/manage'), hasGrants('sending_domains/manage')),` to routes for ListPage and CreatePage.

2020-11-16 21:55 UTC, shrirupa commented
@nicklemmon this is ready for another pass

2020-11-17 14:20 UTC, nicklemmon requested changes
@shrirupa I left a couple of comments - looks like you found a gap in our testing!

2020-11-17 14:20 UTC, nicklemmon commented on src/config/routes/index.js
> +    condition: hasGrants('tracking_domains/manage'),
I think you would want to use the same condition for all these pages:

```js
all(hasGrants('tracking_domains/manage'), hasGrants('sending_domains/manage'))
```

I know that might seem weird on its face, but I'm imagining a user going to the list page, clicking on a tracking domain, and then getting an error.

2020-11-17 14:20 UTC, nicklemmon commented on cypress/tests/integration/hibana/hibanaNavigation.spec.js
> +        });
All of these assertions are actually nested within a `describe('account settings dropdown', () => {})` so this isn't the right place for them.

It actually looks like our Hibana navigation tests are missing role-based assertions, whereas our OG theme tests do have those assertions. I know it's expanding the scope of the ticket, but would you mind adding some? Should just basically involve creating users with those roles and then writing tests to assert against what you see when signed in as those users.

2020-11-17 14:53 UTC, shrirupa commented on cypress/tests/integration/hibana/hibanaNavigation.spec.js
> +        });
I meant to paste it inside the that }); 😄  . Thanks for catching that!

2020-11-17 16:37 UTC, nicklemmon approved these changes
@shrirupa Looks good to me!

2020-11-17 16:41 UTC, merged