SA-1617: Charts localize request
SparkPost/2web2ui pull request #1901
Opened 2020-11-18 14:29 UTC by PatrickSison

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-11-18 16:13 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +    return getQueryFromOptions({ ...reportOptions, metrics: formattedMetrics });
Maybe `getMetricsFromKeys` can get baked into `getQueryFromOptions` to avoid having to pull it in twice

2020-11-18 16:13 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +  const { reportOptions } = props;
Need to verify if we expect hydrated or dehydrated metrics. If we expect hydrated, might be harder to integrate with other pages.

2020-11-18 16:13 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +  switch (charts.length * (compare.length || 1)) {
Chart calculation to account for comparison

2020-11-19 14:22 UTC, nicklemmon requested changes
@PatrickSison A bit of feedback for you to start on - the review is a little confusing with the other PR here too - but hopefully we can get out SA-1773 today to help with that.

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +  const { compare } = reportOptions;
This name confuses me a bit. Should it be `comparisons`?

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +            <Box key={`chart_group_${index}`}>
The `key` needs to be on the outermost element here. `Panel.Section` in this case. Probably no need for the `Box`?

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +              <Heading data-id={`heading_${index}`} as="h2" looksLike="h5">
This probably shouldn't be an `h2` - double check the heading structure of the page. At most it would be an `h3` but might even be an `h4`.

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +        ];
I don't quite understand what's happening here. Would you mind adding some comments to explain things?

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +              <Heading data-id={`heading_${index}`} as="h2" looksLike="h5">
I would double check the font size token used in the mock - the mocks show:
1. A larger font size
2. Space below the heading. Probably worth using a `<Stack/>` here.

2020-11-19 14:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
>              showXAxis={i === charts.length - 1}
The mocks don't appear to have the label on the lefthand side, or a dividing line between charts. Are these old mocks?

**Mocks:**
<img width="1124" alt="Screen Shot 2020-11-19 at 9 18 53 AM" src="https://user-images.githubusercontent.com/3613392/99677953-4941e800-2a48-11eb-9db8-6c00a66b88aa.png">

**Actual:**
<img width="1255" alt="Screen Shot 2020-11-19 at 9 19 22 AM" src="https://user-images.githubusercontent.com/3613392/99677992-552daa00-2a48-11eb-8e75-f0fa834ed086.png">

2020-11-19 14:50 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
>              showXAxis={i === charts.length - 1}
Yeah, let me attach new mocks to the ticket

2020-11-19 14:51 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +            <Box key={`chart_group_${index}`}>
Yeah, that's true. Will update

2020-11-19 14:51 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +  const { compare } = reportOptions;
I'm cool with changing the variable name. I didn't settle on a specific variable name. Will update this + query param

2020-11-19 14:53 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +export function ChartGroups(props) {
Yeah. Report options might not be coming from reportbuildercontext and may need to be sourced from somewhere else I think (e.g. Dashboard V2, or IP monitoring). We could make the reportBuilder context reusable so that other pages can use the same context provider, and then keep some of that business logic for the report options? What do you think?

2020-11-19 14:54 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +      enabled: reportOptions.isReady,
Yeah, didn't realize it wasn't rendering until then. Will remove.

2020-11-19 19:39 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
>              showXAxis={i === charts.length - 1}
But, the mocks have always had the y axis. I'll double check how we want to go forward with the charts

2020-11-19 20:54 UTC, PatrickSison commented
@nicklemmon For easier diff comparison: https://github.com/SparkPost/2web2ui/compare/SA-1773...SA-1617

2020-11-20 19:55 UTC, nicklemmon requested changes
@PatrickSison Have some more feedback for you. Things seem to be working well.

Also, looks like query params aren't updating for this yet? Has that been wired up? I looked at Jira but couldn't tell if there was an additional ticket to address that.

2020-11-20 19:55 UTC, nicklemmon commented on src/helpers/api/defaultQuery.js
> +    // const total_count = _.get(response, 'data.total_count');
I think you can just delete this to be honest - may be awhile before we even need paginated queries.

2020-11-20 19:55 UTC, nicklemmon commented on src/helpers/reports.js
> +    ret.comparisons = comparisons;
👍 More consistent!

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +      </Box>
You shouldn't need a `Box` here - the `<Loading />` component has a `maxHeight` prop you can leverage.

Also, it looks like two loading states follow each other, and the size is dramatically different so it looks kind of janky. The size should either be consistent (controlled via a shared component or variable) or there shouldn't be multiple, different loading states:

**First loading state:**
<img width="1546" alt="Screen Shot 2020-11-20 at 2 09 09 PM" src="https://user-images.githubusercontent.com/3613392/99840238-30196400-2b3a-11eb-9edf-ebcc00718972.png">

**Second loading state:**
<img width="1553" alt="Screen Shot 2020-11-20 at 2 09 28 PM" src="https://user-images.githubusercontent.com/3613392/99840271-3c9dbc80-2b3a-11eb-94cf-1473c1ba2c54.png">

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +              stroke: chartStatus === 'loading' ? tokens.color_gray_100 : stroke,
If the `<Loading/>` just takes the place of the chart entirely, is this necessary?

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                  <Charts {...chart} metrics={processedMetrics} to={to} yScale="linear" />
I tried this for the loading and it seemed to work well?
https://github.com/SparkPost/2web2ui/compare/master...SA-1619#diff-7ebbaa622d25702925ac215015c3dd0edbcfa747d72cd17088a3bd05a7a33abaR214

Might need to move the loading state further down though, so might need to just ignore this entirely

2020-11-20 19:55 UTC, nicklemmon commented on src/helpers/api/signals.js
> +export function getTimeSeries(params) {
Should this file be `metrics.js` to mirror the endpoint? I could see it either way.

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> -import styles from './ReportBuilder.module.scss';
Yaaay

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    return getQueryFromOptions({ ...reportOptions, metrics: formattedMetrics });
I'm usually a fan of doing it like you have it - keeping these sorts of things separate - each function only doing one thing.

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +  }, [reportOptions.isReady, refetchTimeSeries]);
Is this even a possible state? It looks like `<Loading/>` is rendered on `ReportBuilder` if `!reportOptions.isReady`.

2020-11-20 19:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
>              showXAxis={i === charts.length - 1}
This is more of a UX question, but shouldn't the things being compared have some sort of label? Like these:
<img width="1321" alt="Screen Shot 2020-11-20 at 2 31 46 PM" src="https://user-images.githubusercontent.com/3613392/99842049-22191280-2b3d-11eb-9ab6-5d44125d5d3e.png">

Would I necessarily know that `greg-hackathon` and `geoip-testing` are templates? They might be something else.

2020-11-20 19:55 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportCompareBy.spec.js
> +      cy.findByRole('heading', { name: 'Fake Subaccount 3 (ID 103)' }).should('exist');
It looks like there are a few other spots you can add `cy.wait()` now that the network requests are going through.

2020-11-23 19:21 UTC, PatrickSison commented on src/helpers/api/signals.js
> +export function getTimeSeries(params) {
Makes it more clear

2020-11-24 15:28 UTC, nicklemmon reviewed
@PatrickSison I had a couple of questions - though depending on your answers we can move forward with this one.

2020-11-24 15:28 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                  <Charts {...chart} metrics={processedMetrics} to={to} yScale="linear" />
Looks much better now. Thank you for doing this.

2020-11-24 15:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +  if (!comparisons.length) {
Should this be `!Boolean(comparisons.length)` to be a little safer?

2020-11-24 15:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/LineChart.js
> +*/
You can remove this comment now

2020-11-24 15:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +  const [activeChart, setActiveChart] = React.useState(null);
<img width="1235" alt="Screen Shot 2020-11-24 at 10 18 08 AM" src="https://user-images.githubusercontent.com/3613392/100113665-91914980-2e3e-11eb-9980-cdedad5a0809.png">

Not sure if this is the expectation: hovering the first chart renders the tooltip, then the second one renders both, but hovering the fourth renders them all.

2020-11-24 18:07 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +  const [activeChart, setActiveChart] = React.useState(null);
Hopefully fixed the behavior for the tooltip. This is a hack in the first place so it's a bit janky

2020-11-24 19:34 UTC, nicklemmon approved these changes
@PatrickSison Looks good to me!

2020-11-24 19:52 UTC, merged