FE-1245 - Removed the "Authenticate for SPF" section from domain details page and verification page for bounce and sending/bounce
SparkPost/2web2ui pull request #1902
Opened 2020-11-18 21:06 UTC by shrirupa

FE-1245 - Removed the "Authenticate for SPF" section from domain details page and verification page for bounce and sending/bounce

### What Changed
 - Removed the "Authenticate for bounce" section from
      - Unverified domain details page - domains/details/sending-bounce/test.123.900
      - Verification pages 
             - Sending/Bounce = domains/details/test.123.900/verify-sending-bounce
             - Bounce = http://localhost:3100/domains/details/test.123.900/verify-bounce
       - Copy in the left Panel for Bounce is also updated to match - https://sparkpost.invisionapp.com/console/share/CS1SX9XT3H/478945608

### How To Test
 - Verify the Authentication for SPF section is gone, and rest of functionality still works correctly

### To Do
- [ ] Address feedback

2020-11-19 20:51 UTC, kchu1337 requested changes
2 additional things I think you can delete. And 1 question.

2020-11-19 20:51 UTC, kchu1337 commented on src/pages/domains/components/SetupBounceDomainSection.js
>      if (!readyFor.bounce) {
Is there still a need for this condition? Or is it just for safety?

2020-11-19 20:51 UTC, kchu1337 commented on src/pages/domains/components/SetupBounceDomainSection.js
> +                  to={`mailto:?subject=Assistance%20Requested%20Verifying%20a%20Bounce%20Domain%20on%20SparkPost&body=${userName}%20has%20requested%20your%20assistance%20verifying%20a%20bounce%20doma
Is this just a typo you are fixing now?

2020-11-19 20:51 UTC, kchu1337 commented on src/pages/domains/components/SendingAndBounceDomainSection.js
>    };
Do you still need this? The condition for displaying the button looks the same;  `(!readyFor.bounce || !readyFor.dkim)`

2020-11-19 21:50 UTC, shrirupa commented on src/pages/domains/components/SetupBounceDomainSection.js
> +                  to={`mailto:?subject=Assistance%20Requested%20Verifying%20a%20Bounce%20Domain%20on%20SparkPost&body=${userName}%20has%20requested%20your%20assistance%20verifying%20a%20bounce%20doma
yes

2020-11-19 22:17 UTC, shrirupa commented on src/pages/domains/components/SetupBounceDomainSection.js
>      if (!readyFor.bounce) {
Removed it. you are right, submit button is already guarded by this condition.

2020-11-19 22:19 UTC, shrirupa commented on src/pages/domains/components/SendingAndBounceDomainSection.js
>    };
Removed it! Thanks!

2020-11-20 16:58 UTC, kchu1337 approved these changes

2020-11-20 18:35 UTC, kchu1337 approved these changes

2020-11-20 18:38 UTC, merged