Sa 1811
SparkPost/2web2ui pull request #1903
Opened 2020-11-18 22:07 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed
 - What changes did you make to satisfy the AC?
     > Outline changes to user flows, any surprising architectural decisions 
     > Alignment between PR commits and this section helps your reviewers.

### How To Test
 - Describe any special dev environment setup required.
     > Anything outside basic hamurai-managed stuff counts as "special".
 - Describe any special accounts that need to be tested.
     > Include any specific user roles and necessary feature flags.

### To Do
- [ ] Any outstanding tasks go here
    > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
- [ ] Tag new routes in Pendo

2020-11-19 16:43 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReport.spec.js
> +      cy.findByRole('option', { name: 'UTC' }).click();
Changed it so we wouldn't have to deal with DST and regex.

2020-11-19 16:46 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    onChange={({ value }) => setTimezone(value)}
Realized that timezone was actually a {label, value} object.

2020-11-19 16:47 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                disabled={loading || Object.keys(touched).length === 0 || isSubmitting}
Added ` Object.keys(touched).length === 0` so the button would be disabled if the user has not touched any fields.

2020-11-19 16:49 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +  const recipients = rest.recipients.map(({ name }) => name);
Was inconsistent between username and name so I decided to use name everywhere. I think there is way to set your own name vs assigned random username.

2020-11-23 20:04 UTC, nicklemmon requested changes
@kchu1337 Left some feedback for you. Reach out if you have questions.

2020-11-23 20:04 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    onClick={() => setUpdateSection('details')}
This could introduce some problems - when a user is editing a `<form>` and they hit enter anywhere within the form, it submits - so this `setUpdateSection()` function would never get called. Another good reason to just incorporate two `<form>` elements.

2020-11-23 20:04 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
>                    value="weekly"
I'm looking at this report and these values aren't populating:
http://localhost:3100/signals/schedule/301036c3-2f79-4174-ba5e-8e031c3a4cd4/d339e654-4f39-4685-b2c2-49a2c028e06e?reportId=301036c3-2f79-4174-ba5e-8e031c3a4cd4&scheduleId=d339e654-4f39-4685-b2c2-49a2c028e06e

<img width="936" alt="Screen Shot 2020-11-23 at 3 02 15 PM" src="https://user-images.githubusercontent.com/3613392/100009509-03b15200-2d9d-11eb-8277-fb84acc18a9a.png">

2020-11-23 20:04 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                    onClick={() => setUpdateSection('timing')}
See my earlier comment, re: submitting a form without clicking this button and the problems this could cause.

2020-11-23 20:04 UTC, nicklemmon commented on src/pages/reportBuilder/ScheduledReportEditPage.js
> +  const { getScheduledReportStatus, report, loading, scheduledReport } = useSelector(
So much better than using `connect`

2020-11-24 16:38 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
>                    value="weekly"
This was from an earlier version before API changes were made. If you look at the network request, it is missing `schedule_type`.

2020-11-24 19:59 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +    </Button>
I made it into it's own component because it's being used in 3 places. Re-use code. Also I will leave it as is because I can't disable `<PageLink>`. Not sure if it's a matchbox bug or a bug in how we wrote the component.

2020-11-24 20:34 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReport.spec.js
> +      //Check that schedule and timezone does not change.
I didn't realize you could chain off `cy.wait`, so I can do that instead.
https://docs.cypress.io/api/commands/its.html#Command-Log

2020-11-24 21:07 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReport.spec.js
> +      cy.findByRole('button', { name: 'Schedule Report' }).should('be.disabled');
Changed to the format of 
1. Cause error in field
2. Blur
3. Check error message
4. Fix error
5. Go next

2020-11-24 21:08 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReport.spec.js
> -      cy.findByLabelText('Time')
Was a duplicate code block on ln 151.

2020-11-24 21:09 UTC, kchu1337 commented on src/helpers/tests/units.test.js
> +
The rest were prettier changes, this are the 2 test cases I added.

2020-11-24 21:12 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                      onChange={({ value }) => setValue('timezone', value, { shouldDirty: true })}
Faster and easier than adding a wrapper. And this way timezone is counted as a form field.

2020-11-24 21:16 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                disabled={loading || Object.keys(touched).length === 0 || isSubmitting}
`on create its disabled until all required fields have values. on update its disabled until a change is detected.` Just set create to be isValid. The only non-require validation is for timing.

2020-11-30 16:53 UTC, nicklemmon requested changes
@kchu1337 The forms implementation largely works but I found some issues with it. Take a look and see what you think.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +    </Button>
I see what you mean - it appears `UnstyledLink` does not handled the `disabled` prop. But not as well as a disabled button.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +    </Button>
Just cut:
https://github.com/SparkPost/matchbox/issues/700

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +      as={isUpdatingScheduledReport ? 'div' : 'form'}
Nice.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                      <Definition.Label> From Address</Definition.Label>
Is there supposed to be a space before the "From" here?

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                      onChange={({ value }) => setValue('timezone', value, { shouldDirty: true })}
I like this approach.

2020-11-30 16:53 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReports.spec.js
> +        .should('deep.equal', {
This is a nice way to do it - a little less verbose than using `cy.wrap`

2020-11-30 16:53 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReports.spec.js
> +      cy.visit('/signals/schedule/foo/bar');
There may be a missing `cy.wait('@getScheduledReport')` in a few spots.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +      onSubmit={!isUpdatingScheduledReport && handleSubmit(onSubmitCreate)}
<img width="697" alt="Screen Shot 2020-11-30 at 11 40 42 AM" src="https://user-images.githubusercontent.com/3613392/100637555-04983580-3301-11eb-8e96-d18a2cbfea63.png">

Seeing some console errors - looks like you may need to use a ternary here.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                </Panel.Section>
It looks like I can create a bug in which the first form prevents the second form from submitting. You may need to use two instances of `useForm` to handle this:
<img width="1017" alt="Screen Shot 2020-11-30 at 11 43 57 AM" src="https://user-images.githubusercontent.com/3613392/100637942-6fe20780-3301-11eb-92ce-2176b14983f9.png">

I know it could get repetitive, but you may need to create distinct edit and create components.

2020-11-30 16:53 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                </Panel.Section>
So to reproduce this, I did:
1. Deleted a required field in the first form
2. Made a valid change in the second form
3. Tried to submit the second form - got an error

2020-12-01 16:14 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> -
Moved all of these into a helper fn.

2020-12-01 16:16 UTC, kchu1337 commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +export const ScheduledReportDetailsForm = ({
Mostly copy+paste. Just made the disabled logic in the parent component and passed the props from useForm

2020-12-01 16:17 UTC, kchu1337 commented on src/pages/reportBuilder/helpers/scheduledReports.js
> +import { formatHourString, formatMinuteString } from 'src/helpers/units';
Basically copy paste from the form file.

2020-12-01 16:18 UTC, kchu1337 commented on src/pages/reportBuilder/helpers/tests/scheduledReports.test.js
> +import { formatFormValues, getDefaultValues } from '../scheduledReports';
Copy pasted from the test file

2020-12-01 16:18 UTC, kchu1337 commented on src/pages/reportBuilder/helpers/tests/scheduledReports.test.js
> +    expect(getDefaultValues(apiValues, users)).toEqual({});
Added this new section of code.

2020-12-01 18:30 UTC, nicklemmon requested changes
@kchu1337 Still seeing a bug, unfortunately, when it comes to validation. At this point, not totally clear what's causing it.

2020-12-01 18:30 UTC, nicklemmon commented on src/pages/reportBuilder/helpers/scheduledReports.js
> +export const WEEK_OPTIONS = [
These are more constants than helpers?

2020-12-01 18:30 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +              ref={register({ required: 'Required' })}
I'm not sure why, but validation isn't working as expected. Steps to reproduce:
1. Go to edit a scheduled report
2. Clear the value of the "Scheduled Report Name" field
3. Click on "Update Details"
4. The field will re-populate with the default value instead of rendering an error

2020-12-01 18:30 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +              ref={register({ required: 'Required' })}
It actually works with the "Send To" field as expected, but it does not work with "Scheduled Report Name" or "Email Subject"

2020-12-01 18:30 UTC, nicklemmon commented on src/pages/reportBuilder/components/ScheduledReportForm.js
> +                </Button>
<img width="970" alt="Screen Shot 2020-12-01 at 1 14 23 PM" src="https://user-images.githubusercontent.com/3613392/100779955-2663ec00-33d7-11eb-9e4e-70cf9b7b427a.png">

When I go to edit a report, the "Update Details" button is not disabled, even before making any edits.

2020-12-02 16:31 UTC, nicklemmon approved these changes
@kchu1337 Looks good!

2020-12-02 16:38 UTC, merged