[FE-1244] Fixed the links to domains in Hibana
SparkPost/2web2ui pull request #1905
Opened 2020-11-19 16:41 UTC by shrirupa

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- In Hibana redirect to /domains/list/sending instead of account/sending-domains from /account/subaccounts page
- In Hibana redirect to /domains/create instead of account/sending-domains/create Add a Sending Domain step on old 
Dashboard page

### How To Test
 - Check if the links redirect to correct pages in Hibana and in OG

### To Do
- [ ] Address feedback

2020-11-19 19:05 UTC, nstanard commented on src/pages/dashboard/components/tests/GettingStartedGuide.test.js
> -  it('should not render the "Start Sending with SparkPost" Expandable when user does not have grants to manageKeys or manageSendingDomains', () => {
This one can be covered by putting the following in the describe block still in the file

```
  it('should not render the "Start Sending with SparkPost" Expandable when user does not have grants to manageKeys or manageSendingDomains', () => {
    const { getAllByTestId, debug } = subject({
      canManageKeys: false,
      canManageSendingDomains: false,
      onboarding: { active_step: "Let's Code" },
    });

    expect(getAllByTestId('expandable-toggle').length).toEqual(1);
  });
```

2020-11-19 19:30 UTC, nstanard commented on src/pages/dashboard/components/tests/GettingStartedGuide.test.js
> -describe('GettingStartedGuide shallow', () => {
I took a stab at putting these tests back in - but I wasn't able to get every assertion migrated over - here is where I left off:

```

  it.only('should render ShowMeSparkpostStep inside "Start Sending with SparkPost" Expandable and this Expandable is open by default', () => {
    const { queryByText, queryAllByTestId, debug } = subject({
      onboarding: { active_step: 'Show Me SparkPost' },
    });

    const expandables = queryAllByTestId('expandable-toggle');

    console.log(debug());

    expect(expandables.length).toEqual(2);
    expect(queryByText('SparkPost Analytics')).toBeInTheDocument();
    expect(queryByText('Start Sending with SparkPost')).toBeInTheDocument();
    expect(queryByText('Send a Test Email')).toBeInTheDocument(); // ShowMeSparkpostStep
    expect(queryByText('Send a test email using our starter template.')).toBeInTheDocument(); // ShowMeSparkpostStep
    // expect(expandables[0]).toHaveProp('defaultOpen');
    // TODO: Find out how to get the attributes of the element and check for aria-expanded="true"
    console.log(expandables[0]);
  });

  it.only('should render LetsCodeStep inside SparkPost Analytics Expandable', () => {
    const { queryByText, queryAllByTestId } = subject({
      onboarding: { active_step: "Let's Code" },
    });
    const expandables = queryAllByTestId('expandable-toggle');
    expect(expandables.length).toEqual(2);
    expect(queryByText('SparkPost Analytics')).toBeInTheDocument();
    expect(queryByText('Start Sending with SparkPost')).toBeInTheDocument();
    expect(
      queryByText("You'll need to add a sending domain in order to start sending emails."),
    ).toBeInTheDocument();
  });

  it.only('should not render the "Start Sending with SparkPost" Expandable when user does not have grants to manageKeys or manageSendingDomains', () => {
    const { queryByText, queryAllByTestId } = subject({
      canManageKeys: false,
      canManageSendingDomains: false,
      onboarding: { active_step: "Let's Code" },
    });
    const expandables = queryAllByTestId('expandable-toggle');
    expect(expandables.length).toEqual(1);
    expect(queryByText('SparkPost Analytics')).toBeInTheDocument();
    expect(queryByText('Start Sending with SparkPost')).not.toBeInTheDocument();
  });
```

2020-11-19 19:58 UTC, nstanard commented on src/pages/dashboard/components/tests/GettingStartedGuide.test.js
>      renderFn(
```
describe('GettingStartedGuide full hibana', () => {
  const subject = (props, renderFn = render) =>
    renderFn(
      <TestApp isHibanaEnabled={true}>
        <GettingStartedGuide {...defaultProps} {...props} />
      </TestApp>,
    );
  it('should navigate to sending domains page when Add Sending Domain is clicked - hibana', () => {
    const { queryByText } = subject({ onboarding: { active_step: "Let's Code" } });
    userEvent.click(queryByText('Add Sending Domain'));
    expect(defaultProps.history.push).toHaveBeenCalledWith(`/domains/create`);
  });
});
```

2020-11-20 18:56 UTC, nstanard commented on src/pages/dashboard/components/tests/GettingStartedGuide.test.js
> -describe('GettingStartedGuide shallow', () => {
https://github.com/SparkPost/2web2ui/pull/1907/files

moved all of this into a PR - more commits coming in just a few min

2020-11-20 19:13 UTC, nstanard requested changes
I was able to figure out each of the jest test cases. If we wanted to convert the getting started tests back to a shallow mount we can. But the way we are testing it right now is fine IMO. Let me know when you have a moment to talk about the PR I've opened up for this. 

https://github.com/SparkPost/2web2ui/pull/1907

2020-11-20 22:00 UTC, shrirupa commented
Thanks @nstanard  for looking at those tests 🎉

2020-11-20 22:04 UTC, nstanard approved these changes
lgtm!

2020-11-20 22:36 UTC, merged