SA-1619 - (UI) Compare By - Aggregate section update
SparkPost/2web2ui pull request #1923
Opened 2020-11-30 19:13 UTC by nicklemmon

[SA-1619](https://sparkpost.atlassian.net/browse/SA-1619)

### What Changed

### How To Test

### To Do
- [ ] Need to upgrade Cypress in order to properly automate testing

2020-11-30 19:20 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +
I happened to be peeking in this file and realized this could be pulled out of the component pretty easily.

2020-12-01 15:50 UTC, nicklemmon commented on src/helpers/metrics.js
>  export function getQueryFromOptionsV2({
Should we add some unit tests to support this?

2020-12-01 15:50 UTC, nicklemmon commented on src/helpers/metrics.js
> +  sending_domains,
Is there a cleaner way to do this that would be easier to maintain?

2020-12-01 15:51 UTC, nicklemmon commented on src/pages/reportBuilder/constants/index.js
> +export const GROUP_BY_CONFIG = {
I moved these in to a central location rather than having multiple config files with one value each.

2020-12-02 17:56 UTC, kchu1337 requested changes

2020-12-02 17:56 UTC, kchu1337 commented on src/pages/reportBuilder/components/CompareByAggregatedMetrics.js
> +          ? aggregatedMetricsKeys.map((metricKey, metricKeyIndex) => {
Is there a reason you use the response object vs formattedMetrics? Then you wouldn't need `getMetricFromKey`.

2020-12-02 17:56 UTC, kchu1337 commented on src/pages/reportBuilder/components/CompareByAggregatedMetrics.js
> +        <Definition dark>
Should this be LabelValue?

2020-12-02 17:56 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +                                          <LegendCircle marginRight="200" color={stroke} />
Should we add the color circle to the compare by? or remove it here?

2020-12-02 17:56 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +                    <Box padding="400" backgroundColor="gray.1000">
Could also move this into it's own component, so the size of report builder decreases. Or implement the ternary in another separate component that contains both the compare by and normal aggregate metrics.

2020-12-02 17:56 UTC, kchu1337 commented on src/helpers/metrics.js
> +  sending_domains,
I'm not sure what this does?

2020-12-02 17:56 UTC, kchu1337 commented on src/helpers/metrics.js
>  export function getQueryFromOptionsV2({
Yeah, but it's not within the scope of this ticket. Up to you.

2020-12-07 14:19 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByAggregatedMetrics.js
> +          ? aggregatedMetricsKeys.map((metricKey, metricKeyIndex) => {
good point - let me try that.

2020-12-07 14:19 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                                          <LegendCircle marginRight="200" color={stroke} />
It's not in the mocks, though it potentially should be. Let me check with UX.

2020-12-07 14:20 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                    <Box padding="400" backgroundColor="gray.1000">
I like that idea

2020-12-07 15:23 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                                          <LegendCircle marginRight="200" color={stroke} />
UX confirmed they missed this. Good catch.

While I was there, I also incorporated the `<Unit/>` component for the value. Definitely would have caused problems otherwise.

2020-12-07 15:53 UTC, nicklemmon commented
@kchu1337 Ready for another pass.

2020-12-07 18:19 UTC, kchu1337 approved these changes

2020-12-07 18:34 UTC, merged