Sa 1756
SparkPost/2web2ui pull request #1928
Opened 2020-12-02 16:56 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2020-12-07 17:28 UTC, nicklemmon requested changes
@kchu1337 Overall looks good - I had a few tiny bits of feedback though nothing major.

2020-12-07 17:28 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/scheduledReports.spec.js
> +    it('Deletes existing scheduled report', () => {
Excellent test here - using the best methods and waiting at the right times. Well done.

2020-12-07 17:28 UTC, nicklemmon commented on src/pages/reportBuilder/ScheduledReportEditPage.js
> +        title="Are you sure you want to Delete Scheduled Report"
Should there be a question mark here? Not sure the capitalization is right in the sentence. Maybe titlecase?

> "Are You Sure You Want to Delete Scheduled Report?"

Don't see mocks for this, so I suppose it's a UX gap.

2020-12-07 17:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/ScheduledReportsModal.js
> +            onClick={() => openDeleteModal({ scheduledReport })}
Are these supposed to render on top of one another like this or one at a time?

<img width="1096" alt="Screen Shot 2020-12-07 at 12 15 08 PM" src="https://user-images.githubusercontent.com/3613392/101382400-eba1fe00-3885-11eb-8598-1e1af1d046ac.png">

2020-12-07 17:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/ScheduledReportsModal.js
> +          <Button variant="minimal" aria-controls={schedule_id} data-id={schedule_id}>
I don't think you need `aria-controls` here, or the `data-id`

2020-12-07 17:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/tests/ScheduledReportsModal.test.js
> +    expect(deleteScheduledReport).toHaveBeenCalledWith('123', '12345');
Should these be in Cypress? Might make for easier refactoring in the future, though these do do the job.

2020-12-07 17:28 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/ScheduledReportsModal.js
> +          <PageLinkAsButton variant="primary" to={`/signals/schedule/${report.id}`}>
This is a clever workaround.

I just filed this to change the component API:
https://github.com/SparkPost/matchbox/issues/710

2020-12-09 16:34 UTC, kchu1337 commented on src/pages/reportBuilder/ScheduledReportEditPage.js
> +        title="Are you sure you want to Delete Scheduled Report"
There's this https://msys.slack.com/archives/GLLAW6UAX/p1606165485165700?thread_ts=1606164866.161600&cid=GLLAW6UAX

2020-12-09 16:39 UTC, kchu1337 commented on src/pages/reportBuilder/components/SavedReportsSection/tests/ScheduledReportsModal.test.js
> +    expect(deleteScheduledReport).toHaveBeenCalledWith('123', '12345');
I like it here since it seems fairly self-contained. My logic is basically 
```
IF (Is it fairly self-contained on this component )
    IF(Is there already a unit test file)
       Put the test in the test file
    ELSE
       Add it to cypress test
ELSE
 Cypress
```

2020-12-09 18:19 UTC, nicklemmon commented on src/pages/reportBuilder/components/SavedReportsSection/tests/ScheduledReportsModal.test.js
> +    expect(deleteScheduledReport).toHaveBeenCalledWith('123', '12345');
That makes sense - I think the only downside is it does negatively impact our ability to refactor. I think I tend to prefer tests like this when the code is re-usable unit rather then feature-specific code. So anything in `src/components`, for example, should have lots of Jest testing, but then features are largely verified with integration testing in the browser.

That being said, helper functions and other small things can be helpful to test in Jest even if they are feature-specific.

I don't think it's worth holding the ticket up over, but just my two cents.

2020-12-10 14:36 UTC, nicklemmon requested changes
@kchu1337 Everything looks good - I found one tiny HTML issue that I should have caught earlier. Let's fix that and then get this out the door.

2020-12-10 14:36 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/savedReports.spec.js
> +          cy.findByRole('button', { name: 'Open Menu' }).click({ force: true });
This is some sort of a bug with using `TableCollection` inside of a modal - just using an arbitrary `cy.wait(500)` also fixes the issue - though I'm fine with your solution too.

Neal ran in to this as well. We did some digging and still unclear what's going on.

2020-12-10 14:36 UTC, nicklemmon commented on src/pages/reportBuilder/ScheduledReportEditPage.js
> +                Make sure you absolutely want to delete this item before proceeding. This action
This needs to be a `<p>` rather than just raw text here. Sorry, should have caught that earlier.

2020-12-10 15:42 UTC, nicklemmon approved these changes
@kchu1337 Looks good to me.

2020-12-10 15:45 UTC, merged