SA-1868
SparkPost/2web2ui pull request #1934
Opened 2020-12-07 15:33 UTC by PatrickSison

### What Changed

- useSparkPostQuery error defaults to an empty object instead of undefined if request fails due to network
- Error state added to charts

### How To Test

- Go to report builder
- Block network request for `time-series` in browser
 - Verify error state renders correctly
 - Verify error does not trigger error boundary page and keeps report builder rendered
 - Verify error message

### To Do

- [ ] Address feedback

2020-12-07 16:04 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
UX was good with the design and the padding. Only feedback was the weight of the state match the mocks

2020-12-07 16:04 UTC, PatrickSison commented on src/components/empty/Empty.js
> +          <Text color="gray.900" fontSize="400" fontWeight="normal">
Changed weight to match the mocks

2020-12-07 16:36 UTC, nicklemmon requested changes
@PatrickSison Just a couple of things:
1. The `Empty` should not be within a `Panel.Section` - this unfortunately might be a little painful
2. We should have some testing around this state

2020-12-07 16:36 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
We should definitely have some Cypress testing to check for this state - should be fairly straight forward if you just stub the response as a failure (I usually do a `400` status code)

2020-12-07 16:36 UTC, nicklemmon commented on src/hooks/useSparkPostQuery/useSparkPostQuery.js
> +  const { response = {} } = error;
Good call!

2020-12-07 16:36 UTC, nicklemmon commented on src/components/empty/Empty.js
> +          <Text color="gray.900" fontSize="400" fontWeight="normal">
Nice.

2020-12-07 16:36 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
I don't think the `Empty` component is meant to render within a `Panel.Section` like this. There should be no white space around the gray area:

<img width="1176" alt="Screen Shot 2020-12-07 at 11 33 55 AM" src="https://user-images.githubusercontent.com/3613392/101377751-3d478a00-3880-11eb-9d67-dbca8271ca67.png">

2020-12-07 16:59 UTC, PatrickSison commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
I asked UX about the padding, and they were cool with the padding. I'll double check again though if that's their preference

2020-12-07 17:48 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
Hmm, this was something they previously said was a bug - we even did a ticket or two to fix this problem in other places in the app as a result - so it would be inconsistent.

2020-12-07 17:48 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    return <Empty message="Unable to load report" description="Please try again" />;
Not to mention, in other features we don't use the empty component but the `ApiErrorBanner` when a request fails.

2020-12-08 20:14 UTC, nicklemmon commented on src/pages/reportBuilder/components/Charts.js
> +    <Box padding={[400, null, 500]}>
Mind explaining this? Not really sure why the padding would go away sometimes...I'm sure  there is a good reason though.

2020-12-09 14:16 UTC, nicklemmon requested changes
@PatrickSison Still seeing some padding issues and this test isn't passing for me locally - we spoke about it in Slack but just wanted to officially add that as review feedback for tracking purposes.

2020-12-09 18:16 UTC, nicklemmon approved these changes
@PatrickSison Looks good to me. As always, appreciate all the back and forth.

2020-12-09 19:21 UTC, merged