FE-1266 - Add aggregate metrics section
SparkPost/2web2ui pull request #1945
Opened 2020-12-09 19:26 UTC by shrirupa

FE-1266 - Add aggregate metrics section

### What Changed

- Made a reusable component for Aggregate Metrics Section
- Removed the refreshReportBuilder from src/actions/summaryChart
- Localized the getAggregateData api call to the AggregateMetricsSection

### How To Test

- Verifying everything looks good on Report Builder page
- Add the metrics section as in the mocks - https://sparkpost.invisionapp.com/console/share/RU1SP41BG7/483505018
- if no report is pinned (user ui options "pinned_report"), these metrics are default metrics for Summary Report
- if user ui options has a "pinned_report", then these metrics are the one associated with pinned report.

### To Do

- [ ] Address feedback

2020-12-11 16:38 UTC, nicklemmon requested changes
@shrirupa First pass is done - let me know what questions you have. Overall things largely work as expected, though I did find a few things worth looking at.

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    </Panel.Section>
<img width="970" alt="Screen Shot 2020-12-11 at 11 03 58 AM" src="https://user-images.githubusercontent.com/3613392/101926074-b1e03880-3ba0-11eb-94d1-3cf6a7afb89b.png">

I don't think the `Panel.Section` should be used here. On the `/signals/analytics` route, it renders without the extra padding:
<img width="1330" alt="Screen Shot 2020-12-11 at 11 05 45 AM" src="https://user-images.githubusercontent.com/3613392/101926185-db00c900-3ba0-11eb-9492-1903d96cd543.png">

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                      processedMetrics={getMetricsFromKeys(pinnedReport?.options?.metrics)}
Is there a risk these would be undefined?

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +  ).format('MMM Do, YYYY')}`;
Could this logic be moved in to `useDashboardContext()`? I think that was my intention originally - to try and keep the business logic distinct from the UI.

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
>  import ChangeReportModal from './components/ChangeReportModal';
Unrelated to this ticket, but I noticed this modal isn't animating when opened. I think it's because it's being conditionally rendered?
```
{isModalOpen && (
  <ChangeReportModal open={isModalOpen} onClose={closeModal} reports={allReports} />
)}
```

You _should_ just be able to do this:
```
<ChangeReportModal open={isModalOpen} onClose={closeModal} reports={allReports} />
```

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +import moment from 'moment';
Can we use `date-fns` instead? I believe we are going to make an effort to remove `moment` in 2021 so it would be helpful to avoid using it.

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                      <ChartGroups reportOptions={pinnedReport.options} p="0" />
Since this is a "global" component now, you could move it to co-exist alongside the aggregated metrics components

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <AggregatedMetrics
<img width="990" alt="Screen Shot 2020-12-11 at 11 18 51 AM" src="https://user-images.githubusercontent.com/3613392/101927595-ac83ed80-3ba2-11eb-8acd-eebe90b82492.png">

It looks like the colors aren't quite aligning here - these appear to be the OG colors for some reason?

2020-12-11 16:38 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <CompareByAggregatedMetrics
It looks like UX wants the layout to be slightly different on the dashboard. Could potentially be a prop that controls it? Like `isStacked` or `stacked` or `collapsed` or ??

<img width="817" alt="Screen Shot 2020-12-11 at 11 22 49 AM" src="https://user-images.githubusercontent.com/3613392/101928241-55cae380-3ba3-11eb-9372-9f8d1e13ebc0.png">

2020-12-11 16:38 UTC, nicklemmon commented on src/hooks/usePinnedRport/usePinnedReport.js
>  }
Glad to see this custom hook here.

When I link to a saved report it isn't populated in the `<select />` as I would expect? Not sure if that's on your end here or on our end really:
<img width="1302" alt="Screen Shot 2020-12-11 at 11 30 30 AM" src="https://user-images.githubusercontent.com/3613392/101929011-4bf5b000-3ba4-11eb-97e0-7571757b1de7.png">

2020-12-11 16:38 UTC, nicklemmon commented on src/hooks/usePinnedRport/usePinnedReport.js
> +      isFirstRender.current = false;
Mind explaining this a bit? Might be helpful to just add some comments describing the requirement you're addressing by doing this.

2020-12-11 17:14 UTC, shrirupa commented on src/pages/dashboardV2/DashboardPageV2.js
> +import moment from 'moment';
have we finalized upon date-fns ?

2020-12-11 17:19 UTC, shrirupa commented on src/hooks/usePinnedRport/usePinnedReport.js
> +      isFirstRender.current = false;
I will add the comment, reason being loadingState for api is false on first render and hence it triggers the getAggregateTable action without the correct pinnedReport.options

2020-12-11 17:26 UTC, shrirupa commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <AggregatedMetrics
ahh, good catch! looks like getMetricsFromKeys needed true as second argument to get right colors.

2020-12-11 17:30 UTC, shrirupa commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <CompareByAggregatedMetrics
I think they want the layout to this only different when View filters button shows up otherwise it is same as Report Builder. That "View Filters"button(added in another PR) is rendered conditionally only when pinned report has associated filters to it.

2020-12-11 18:52 UTC, shrirupa commented on src/hooks/usePinnedRport/usePinnedReport.js
>  }
fixed it! report parameter was being added twice

2020-12-11 19:02 UTC, shrirupa commented on src/hooks/usePinnedRport/usePinnedReport.js
>  }
some saved reports seem to have report param in query_string and some don't 🤷

2020-12-11 19:54 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +import moment from 'moment';
Well, I know are for sure moving away from `moment` and don't have any plans to move away from `date-fns`.

2020-12-11 19:54 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +                    <CompareByAggregatedMetrics
Really? 🤔  That seems off to me.

2020-12-14 14:43 UTC, nicklemmon requested changes
@shrirupa Have some additional feedback - things seem to work well overall and you addressed most of my initial concerns.

I'm a little concerned that some of the logic in the feature is not covered by automated testing. There is a lot going on here, and since we plan to do a fairly significant refactor of report builder charts in the near future, I think we would feel safer making those sorts of changes with more testing in place.

Nice work so far!

2020-12-14 14:43 UTC, nicklemmon commented on src/actions/summaryChart.js
> +      params = getQueryFromOptions({ ...state.reportOptions, metrics: activeMetrics });
Should we be mixing and matching these two helpers? I thought V2 was for use with the newer/Hibana chart UI.

2020-12-14 14:43 UTC, nicklemmon commented on src/hooks/usePinnedRport/usePinnedReport.js
> +  } else {
I don't see tests supporting a lot of these changes? It would be worth adding more to ensure this doesn't break in the future.

2020-12-14 14:43 UTC, nicklemmon commented on src/pages/dashboardV2/DashboardPageV2.js
> +  const dateValue = `${moment(pinnedReport?.options?.from).format('MMM Do')} - ${moment(
Thinking it over again, I think this could probably be extracted as a helper function, actually - since it's now in use in two places that are quite far apart from one another.

2020-12-14 16:26 UTC, shrirupa commented on src/actions/summaryChart.js
> +      params = getQueryFromOptions({ ...state.reportOptions, metrics: activeMetrics });
good point, I don't think we will need getQueryFromOptions here.

2020-12-14 19:50 UTC, nicklemmon approved these changes
@shrirupa This looks good to me. Let me know when you would like to get it out.

2020-12-14 19:58 UTC, merged