FE-1235 : Add View filters button and Modal to Saved Reports Section
SparkPost/2web2ui pull request #1947
Opened 2020-12-10 15:31 UTC by shrirupa

FE-1235 : Add View filters button and Modal to Saved Reports Section

### What Changed

- Added View Filters Button in the Aggregate Metrics Section
- This report should show only when there are any filters associated with the pinned report
- On Clicking the View Report Button in this Modal, it should take you to the report Builder page
- Added the PinnedReportFilterModal that opens on clicking the View Filters Button
- Moved the ActiveFilters component to src/components/ReportBuilder 

### How To Test

- Add the View Filters button to the metrics section. -  https://sparkpost.invisionapp.com/console/share/RU1SP41BG7
- Do not show “View filters” button if there are no filters associated with the pinned report.
- Clicking on View filter opens this Modal -  https://sparkpost.invisionapp.com/console/share/RU1SP41BG7/483505019
- Clicking on View Report, should redirect to Report Builder with the pinned report report options

### To Do

- [ ] Address feedback
- [ ] Add related cypress tests and unit tests
- [x] Verify with UX if the Modal looks good or do they want the filters to have white background.

2020-12-10 16:27 UTC, shrirupa commented on cypress/fixtures/metrics/deliverability/200.get.pinned-report.json
> +  "results": [
from FE-1266

2020-12-10 16:27 UTC, shrirupa commented on cypress/fixtures/users/200.get.has-pinned-report.json
> +  "results": {
from FE-1266

2020-12-10 16:27 UTC, shrirupa commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> +      stubGrantsRequest({ role: 'admin' });
from FE-1266

2020-12-10 16:28 UTC, shrirupa commented on src/actions/summaryChart.js
> +    const state = getState();
from FE-1266

2020-12-16 15:05 UTC, kchu1337 requested changes

2020-12-16 15:05 UTC, kchu1337 commented on src/pages/dashboardV2/DashboardPageV2.js
>                      <AggregatedMetrics
Whenever I open/close the modal, this looks like it's getting re-rendered. And since the metrics take longer, it looks like the metrics aggregate disappears.

2020-12-17 16:21 UTC, kchu1337 approved these changes

2020-12-17 16:29 UTC, merged