SA-1620: Group by table comparison filters
SparkPost/2web2ui pull request #1950
Opened 2020-12-11 15:06 UTC by PatrickSison

### What Changed

- Group By table swaps for CompareByGroupByTable (if there are comparison filters)
- Column added to comparison filter
- Added new useSparkPostQueries

### How To Test

- ON report builder with compare by enabled, add at least 2 comparison filters
 - Go to group by table and verify table works as expected
 - Verify that clicking filter links still adds filters to table
 - Verify that table is still sortable by column
 - Verify that default sort is by group by column (no longer first column)

### To Do

- [ ] Add testing
 - [ ] Disable option for group by if select column is used (or maybe just disable 2nd row if it's the same?)

2020-12-11 18:55 UTC, nicklemmon requested changes
@PatrickSison Seems to work well overall. I have a few comments I've left, plus I don't see any testing to support these changes so that's a concern.

2020-12-11 18:55 UTC, nicklemmon commented on src/helpers/api/metrics.js
> +    url: `${DELIVERABILITY_BASE_URL}${path ? `/${path}` : ''}`,
Doesn't the `params` argument handle this rather than interpolating here?

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +  // CompareByGroupByTable,
Can this be removed?

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +  const getColumnHeaders = () => {
I'm not seeing the default sort within the table?
<img width="1070" alt="Screen Shot 2020-12-11 at 1 43 02 PM" src="https://user-images.githubusercontent.com/3613392/101942145-10b0ac80-3bb7-11eb-85fc-b0c2ca840ae9.png">

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +        <Panel.LEGACY>
No need to use `Panel.LEGACY` within this feature.

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +export const GroupByTable = () => {
👏  Much clearer

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +import React from 'react';
We should have some Cypress testing around all of this? Probably useful to do testing around the multiple requests and their arguments as well as the user's interaction with the table when comparisons are enabled.

2020-12-11 18:55 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/useGroupByTable.js
> +import { useState, useMemo } from 'react';
This could all be tested via the feature itself rather than Jest unit testing, though unit testing might be a little easier to test independently (as well as edge cases).

We have this installed:
https://github.com/testing-library/react-hooks-testing-library

Up to you how it should be handled.

2020-12-11 19:02 UTC, PatrickSison commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +  const getColumnHeaders = () => {
I think default sort is the sort is uses if no sort is selected. Active sorting works otherwise

2020-12-11 19:04 UTC, PatrickSison commented on src/helpers/api/metrics.js
> +    url: `${DELIVERABILITY_BASE_URL}${path ? `/${path}` : ''}`,
Was on the fence with how to handle this, but also it uses the paths `/deliverability/${groupByKey}` to actually route to the appropriate break down table. It feels separate from the rest of the params, but we could pass it in through params and deconstruct just this variable, and send the rest down to the API

2020-12-14 14:54 UTC, nicklemmon commented on src/helpers/api/metrics.js
> +    url: `${DELIVERABILITY_BASE_URL}${path ? `/${path}` : ''}`,
Yeah I think that would be better in my mind - make this as generic/simple as possible and keep complexity elsewhere.

2020-12-14 18:17 UTC, nicklemmon requested changes
@PatrickSison taking another pass and I think I caught one bug. Other feedback is minor, though I do think some additional testing of edge cases is warranted.

2020-12-14 18:17 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +    <Panel.LEGACY>
Same here, no need to use `Panel.LEGACY`

2020-12-14 18:17 UTC, nicklemmon commented on src/hooks/useSparkPostQuery/useSparkPostQuery.js
> +      return defaultQuery(url, { method, params, headers, auth });
You shouldn't have to pass things in to the `defaultQuery` manually? From what I understand, this is how it works:
- A `queryKey` can contain lots of request-related information (method, URL, params) which is passed to each instance of `useQuery`
- `useQuery` takes that `queryKey` and passes it to our axios instance, `sparkPostRequest` - our custom `defaultQuery` destructures the `queryKey` and does that for us
- We pass the `defaultQuery` to the `QueryCache` component so that it is always there, consuming/handling passed-in query keys without us having to manually reference it

2020-12-14 18:17 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +    }
It would be worth adding some testing for the error and empty state scenarios.

2020-12-14 18:17 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +  };
<img width="286" alt="Screen Shot 2020-12-14 at 1 12 30 PM" src="https://user-images.githubusercontent.com/3613392/102118828-37b4eb80-3e0e-11eb-9bb4-3a2615ac299d.png">

Appear to be some issues with rendering subaccounts.

2020-12-14 18:17 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +  };
When clicking on these links that does appear to cause some invalid queries to be passed to the API. Fortunately error scenarios handle this well.

2020-12-14 21:41 UTC, PatrickSison commented on src/hooks/useSparkPostQuery/useSparkPostQuery.js
> +      return defaultQuery(url, { method, params, headers, auth });
I think this is a limit of `useQuery` solved by `useQueries` in `react-query`. For this instance, we don't necessarily know the number of requests that could come in because of the comparisons. Regardless of the number of requests, these have to be joined into one promise as if one fails, the rest fails because the data can't be loaded altogether.

2020-12-16 15:00 UTC, nicklemmon commented on src/hooks/useSparkPostQuery/useSparkPostQuery.js
> +      return defaultQuery(url, { method, params, headers, auth });
That makes sense to me.

And in the not too distant future, we'll migrate to React Query 3, and then a lot of this should go away - though not all of it.

2020-12-16 15:32 UTC, nicklemmon requested changes
@PatrickSison Left a few comments, though not a whole lot - I think this is almost ready.

2020-12-16 15:32 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportBreakdownTable.spec.js
> +      it('will render an empty state the requests fail', () => {
This is an error state, no? Not an empty state?

2020-12-16 15:32 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportBreakdownTable.spec.js
> +        cy.wait('@getWatchedDomains');
Seems like a bug!

2020-12-16 15:32 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportBreakdownTable.spec.js
> +        cy.wait('@getWatchedDomains');
Since they occur simultaneously, probably use this:
```
cy.wait(['@getWatchedDomains', '@getWatchedDomains']);
```

Just helps things be a little bit more self documenting.

2020-12-16 15:32 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +      </Box>
This component should be implemented here. If it's global and re-usable, we can also use it in lots of spots for consistency's sake:
```jsx
function EmptyCell() {
  return (
    <>
      {/* hidden from screen reader users */}
      <span aria-hidden="true">---</span>
      {/* hidden from everyone else */}
      <ScreenReaderOnly>No Data</ScreenReaderOnly>
    </>
  );
}
```

2020-12-16 15:32 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/useGroupByTable.js
> +    return { ...reportOptions, filters: comparedFilters };
This could be tough to fix, but looks like it's possible to add the same filter multiple times through this table, resulting in an API error. It's a weird edge case, so I'm not sure how that should be handled:
<img width="975" alt="Screen Shot 2020-12-16 at 10 13 31 AM" src="https://user-images.githubusercontent.com/3613392/102367223-833ed500-3f87-11eb-9bb3-34491c5c2dba.png">

2020-12-16 15:32 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +        <Panel>
We would want to put this inside a `Panel.Section` for consistency and to avoid having a double border when we upgrade Matchbox (white line is there to show the alignment inconsistency):

<img width="506" alt="Screen Shot 2020-12-16 at 10 15 18 AM" src="https://user-images.githubusercontent.com/3613392/102367418-c13bf900-3f87-11eb-87ce-c4a8be2e9b43.png">

2020-12-16 15:32 UTC, nicklemmon commented on jsconfig.json
> +  "exclude": ["node_modules", "dist"]
Our build folder is `build` rather than `dist` looks like.

2020-12-16 15:32 UTC, nicklemmon commented on src/hooks/useSparkPostQuery/useSparkPostQuery.js
> +export function useSparkPostQueries(queries, config = {}, queryKey) {
Would you mind adding some tests to `useSparkPostQuery.spec.js` and some docs to `useSparkPostQuery.stories.mdx`?

I would think just a tiny bit of both would go a long way.

2020-12-16 15:32 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/useGroupByTable.js
> +          [groupKey]: key, //Readd key (in case it's empty)
Typo here

2020-12-16 15:32 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportBreakdownTable.spec.js
> +        cy.wait('@getWatchedDomains');
Nevermind! This is right. It looks like there are two requests that are invoked via `useSparkPostQueries` each time it attempts the request, so that should total 8. This works too:

```js
cy.wait(['@getWatchedDomains', '@getWatchedDomains']);
cy.wait(['@getWatchedDomains', '@getWatchedDomains']);
cy.wait(['@getWatchedDomains', '@getWatchedDomains']);
cy.wait(['@getWatchedDomains', '@getWatchedDomains']);
```

2020-12-16 16:21 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/reportBreakdownTable.spec.js
> +        cy.wait('@getWatchedDomains');
That's a lot nicer

2020-12-16 18:57 UTC, nicklemmon approved these changes
@PatrickSison 👍 Looks good to me.

2020-12-16 19:44 UTC, merged