SA-1851: Compare by for links tabs
SparkPost/2web2ui pull request #1958
Opened 2020-12-17 06:14 UTC by PatrickSison

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2020-12-18 16:17 UTC, nicklemmon requested changes
@PatrickSison I think there were some merging issues? Probably due to being based on SA-1849.

2020-12-18 16:17 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportTabs.spec.js
> +    // Uncheck defaults, and check a metric that renders the "Bounce Reason" table
Nice.

2020-12-18 16:17 UTC, nicklemmon commented on src/constants/index.js
> +export const REPORT_BUILDER_FILTER_TYPE_COLLECTION = [
I think I ended up deleting this - might be worth rebasing with `master`

2020-12-18 16:17 UTC, nicklemmon commented on src/helpers/bounce.js
> +export { formatAggregates, reshapeCategories, getBandTypes };
Was this all just prettier?

2020-12-18 16:17 UTC, nicklemmon commented on src/pages/reportBuilder/components/tabs/LinksComparisonTab.js
> +    'count_unique_confirmed_opened_approx',
Are these the right metrics? I'm not sure they are the same as the bounce reasons table.

2020-12-18 16:17 UTC, nicklemmon commented on src/pages/reportBuilder/constants/index.js
> +      'range=day&metrics=count_sent&metrics=count_accepted&metrics=count_clicked&metrics=count_rendered',
Just curious - why the change here?

2020-12-18 16:17 UTC, nicklemmon commented on src/pages/reportBuilder/hooks/index.js
> +export { default as usePrepareComparisonRequest } from './usePrepareComparisonRequest';
I think these got duplicated due to a merging issue?

2020-12-21 20:28 UTC, nicklemmon commented on src/constants/index.js
> +export const REPORT_BUILDER_FILTER_TYPE_COLLECTION = [
Yeah this can definitely be deleted. Not used anywhere.

2020-12-21 21:27 UTC, PatrickSison commented on src/pages/reportBuilder/constants/index.js
> +      'range=day&metrics=count_sent&metrics=count_accepted&metrics=count_clicked&metrics=count_rendered',
Sorry, forgot to reply to this. This was outside the scope of this ticket, but attached to this. UX asked for changes to this request

2020-12-22 14:35 UTC, PatrickSison commented on src/helpers/bounce.js
> +export { formatAggregates, reshapeCategories, getBandTypes };
Yeah, this was all just prettier. Didn't mean to make changes to this file

2020-12-22 16:46 UTC, nicklemmon requested changes
@PatrickSison I noticed a couple of small tweaks that are needed in your testing, otherwise looks good.

2020-12-22 16:46 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportTabs.spec.js
> +          const [deliverabilityReq, engagementReq] = xhrs;
The order should be swapped here

2020-12-22 16:46 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportTabs.spec.js
> +        // Select the bounce reason tab and verify the network request
Small typo

2020-12-22 17:45 UTC, nicklemmon approved these changes
@PatrickSison 👍  Looks good to me.

2020-12-22 18:07 UTC, merged