SA-1896: Release Scheduled Reports
SparkPost/2web2ui pull request #1959
Opened 2020-12-17 16:27 UTC by kchu1337

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2020-12-18 20:43 UTC, kchu1337 commented on src/pages/reportBuilder/helpers/scheduledReports.js
> +    .filter(Boolean);
Removes users who cannot be found.

2020-12-21 14:17 UTC, nicklemmon approved these changes
@kchu1337 This looks good to me - test failure appears to be a flaky test.

2020-12-21 16:56 UTC, nicklemmon requested changes
@kchu1337 I sent you a Slack message about it, but the test failure here is actually something that needs to be addressed before we merge. It's technically a Matchbox problem, but we don't want to introduce test failures if we can help it.

2020-12-21 18:46 UTC, nicklemmon approved these changes
@kchu1337 Looks good to me - thanks for fixing that test.

2020-12-21 20:03 UTC, merged