FE-1250 - Add Recipient Lists Empty State
SparkPost/2web2ui pull request #1962
Opened 2020-12-17 20:28 UTC by logansparlin

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- Added new empty state for Recipient Lists
- Note: Copy does not match mocks, it has been updated

### How To Test

- Run the app
- Enable account ui flag: "allow_empty_states"
- With no recipient lists and hibana enabled, verify you see the empty state
- With recipient lists make sure you see the muted banner if it has not previously been dismissed

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2020-12-21 19:24 UTC, nicklemmon commented on cypress/tests/integration/abTesting/listPage.spec.js
> +        .should('have.attr', 'href', '/templates');
Hey, not doing a formal review here but just taking a glance at testing. Overall really nice work.

Just a heads up, you can use a custom function we have for this:
```
cy.verifyLink({ 
  content: 'Whatever the content is',
  href: '/whatever/the/href/is'
})
```

2020-12-21 19:27 UTC, nicklemmon commented on src/pages/recipientLists/components/RecipientListEmptyState.js
> +        <EmptyState.Action component={PageLink} to="/lists/recipient-lists/create">
Random Matchbox note, but for API consistency, this prop should probably be `as` rather than `component`

2020-12-21 19:30 UTC, nicklemmon commented on cypress/tests/integration/abTesting/listPage.spec.js
> +    cy.get('table').should('not.be.visible');
We just migrated to Cypress 6 and this may not work anymore. You may need to use `should('not.exist')`

2020-12-22 15:57 UTC, jonambas commented on src/pages/recipientLists/components/RecipientListEmptyState.js
> +        <EmptyState.Action component={PageLink} to="/lists/recipient-lists/create">
UX-411 – This one is actually on the Button component

2020-12-23 18:17 UTC, nicklemmon requested changes
@logansparlin  Shrirupa asked for a little more feedback in the event this were ready for deployment - I found a few things that are worth taking a look at.

Thanks.

2020-12-23 18:17 UTC, nicklemmon commented on cypress/fixtures/recipient-lists/200.get.json
> +            "total_accepted_recipients": 1
We maybe don't want to include this sort of thing in our code - probably don't need to grab such a long list, either.

2020-12-23 18:17 UTC, nicklemmon commented on src/pages/recipientLists/components/InfoBanner.js
> +  if (dismiss) return null;
I think this should be `dismissed` rather than `dismiss` - this confused me initially.

2020-12-23 18:17 UTC, nicklemmon commented on src/pages/recipientLists/ListPage.container.js
> +  isEmptyStateEnabled: isAccountUiOptionSet('allow_empty_states')(state),
Shouldn't we be using the newer `useSelector` hook instead of `connect` here?

2021-01-04 19:38 UTC, shrirupa commented on src/pages/recipientLists/ListPage.js
> +          show: !error && recipientLists.length === 0,
we don't want to remove this old empty state, since it shows up in the OG version of app

2021-01-05 16:30 UTC, shrirupa commented on src/pages/recipientLists/components/InfoBanner.js
> +        When sending email to multiple recipients, it’s best to put them in a recipient list. This
The spec doc has one more line before this text.

2021-01-05 16:37 UTC, shrirupa approved these changes
just have this one last comment https://github.com/SparkPost/2web2ui/pull/1962/files#r552044865. Everything else looks good to me!

2021-01-05 19:59 UTC, merged