SA-1892: Added segment to report builder comparison form
SparkPost/2web2ui pull request #1972
Opened 2020-12-22 14:33 UTC by PatrickSison

### What Changed

- Added segment tracking event for compare by in report builder

### How To Test
- Go to Comparison form in report builder
- Apply form with no comparisons
- Check that request does not go through with applying
- Apply form with at least 2 comparison
- Check that request goes through with the appropriate data

### To Do

- [ ] Verify data on segment

2020-12-22 14:39 UTC, bkemper commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      segmentTrack(SEGMENT_EVENTS.REPORT_BUILDER_COMPARISON_ADDED, {
Shouldn't this be called after `handleSubmit` is successful?

2020-12-22 14:55 UTC, PatrickSison commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      segmentTrack(SEGMENT_EVENTS.REPORT_BUILDER_COMPARISON_ADDED, {
handleSubmit is a synchronous function at least, and all it does is update state in the context. We could do it in the context provider and see if state has changed?

2020-12-22 15:01 UTC, PatrickSison commented
Wonder if it's more valuable to see regardless of if the form is empty if the form is submitted. Not sure if we want to see users who look at the form and apply nothing

2020-12-28 17:21 UTC, kchu1337 requested changes

2020-12-28 17:21 UTC, kchu1337 commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      segmentTrack(SEGMENT_EVENTS.REPORT_BUILDER_COMPARISON_ADDED, {
Ideally, it should just check that the number of filters changes. For example, ```if(_.isEqual(comparisons, formattedFIlters)```. But I think there is a bug where it's updating without needed to click the submit button.

2020-12-28 17:21 UTC, kchu1337 commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      segmentTrack(SEGMENT_EVENTS.REPORT_BUILDER_COMPARISON_ADDED, {
If you keep it like this, if can send a segment event even if they kept their comparisons the same. And if they remove all comparisons, this does not send an event.

2020-12-31 15:20 UTC, PatrickSison commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      segmentTrack(SEGMENT_EVENTS.REPORT_BUILDER_COMPARISON_ADDED, {
@kchu1337 Is your suggestion then that we send any time comparison filters exclusively when it changes (including from any filters down to no filters)? I do agree though it should probably not send when the filters have been unchanged

2021-01-04 21:36 UTC, kchu1337 requested changes

2021-01-04 21:36 UTC, kchu1337 commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      formChanged: state.formChanged,
I would either do `state.formChanged || false` or set it's initial state to false rather than undefined. I think Segment does some weird caching so if you don't explicitly define it, it keeps the previous value.

2021-01-05 18:06 UTC, kchu1337 approved these changes

2021-01-06 16:25 UTC, merged