SA-1893: Compare by filters limited to 10 filters
SparkPost/2web2ui pull request #1983
Opened 2020-12-31 15:10 UTC by PatrickSison

### What Changed

- Added comparison limit of 10 filters

### How To Test

- On Hibana, with `allow_compare_by` feature flag enabled, go to Report Builder page
- Click on `Add Comparison`
- Select comparison type
- Fill out form, adding up to 10 filters
- Verify that warning appears at top of form

### To Do

- [ ] Address feedback

### Notes
- Just realized that user wouldn't immediately see the warning message. Might be worth thinking about how the message is displayed.

2021-01-04 15:50 UTC, nicklemmon requested changes
@PatrickSison Your code is relatively straightforward and seems good to me, however, the UX leaves a bit to be desired. I think you already know that though

2021-01-04 15:50 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportCompareBy.spec.js
> +        cy.findByText('Limit on number of comparisons reached').should('exist');
Yeah, per your point in your PR, this is really a bug - the banner `should.be.visible` rather than just exist. Probably worth working with UX on this one, but there are a few ways to handle it:
1. Move focus to the banner when it renders - though this would be kind of odd when the user hasn't finished entering their last comparison
2. Render a snackbar showing the message in addition to the banner at the top of the form

2021-01-04 15:50 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/reportCompareBy.spec.js
> +        cy.findByText('Limit on number of comparisons reached').should('exist');
it would be worth asserting that the "Add <whatever>" button is no longer rendered as well.

2021-01-04 16:24 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/reportCompareBy.spec.js
> +        cy.findByText('Limit on number of comparisons reached').should('exist');
I will follow up... as soon as slack comes back lol. But agreed

2021-01-04 20:52 UTC, nicklemmon reviewed
@PatrickSison Left a couple of comments - I could be missing something when it comes to the state reducer. I'll ping you about it.

2021-01-04 20:52 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +      }
I'm not sure why this would be necessary? How could the user have more than the number of fields that end up being rendered in the form?

2021-01-04 20:52 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
> +          )}
The only problem with this generic error banner that is used for two sets of UI - is UX OK with the other error being at the bottom of the form as well?

It makes sense either way, just wanted to check.

2021-01-05 14:18 UTC, nicklemmon approved these changes
@PatrickSison Code is much cleaner and works as expected. Nice job. 👍

2021-01-05 15:47 UTC, merged