FE-1269 - Create Empty State for Analytics Report
SparkPost/2web2ui pull request #1994
Opened 2021-01-05 23:04 UTC by shrirupa

FE-1269 - Create Empty State for Analytics Report 

### What Changed

-  Empty state should show up on Analytics Report when user has no sending domain.
-  Added the three Tabs  as in the mock (with placeholder components)

mocks - https://sparkpost.invisionapp.com/console/Empty-States-ckcno05yk00tf011ij29ebpmx/ckevla6xu04f301yh7ymqfocx/play#project_console
### How To Test

- Enable "allow_empty_states" feature flag and check the Analytics page when you have no sending domain, you should see the Empty state as in the mock, with three placeholder tabs
- When "allow_empty_states" feature flag is not enabled the Analytics Page should appear as it is now.

### To Do

- [ ] Address feedback

2021-01-08 15:40 UTC, kchu1337 requested changes
Having some trouble with my openresty settings. I'll take another look at content in another pass once I get it fixed.

2021-01-08 15:40 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +        show: sendingDomains.length === 0 && isEmptyStateEnabled,
Do you need to check `isEmptyStateEnabled` since the Page component already is?

2021-01-08 20:46 UTC, shrirupa commented on src/pages/reportBuilder/ReportBuilder.js
> +        show: sendingDomains.length === 0 && isEmptyStateEnabled,
yes, actually we need this because show: sendingDomains.length === 0 will trigger matchbox to show the default empty state which doesn't exist for this Report Builder Page. you can see this problem, on any account where empty states is not enabled.

2021-01-12 18:11 UTC, kchu1337 approved these changes

2021-01-12 22:05 UTC, merged