FE-1292
SparkPost/2web2ui pull request #1997
Opened 2021-01-06 18:53 UTC by shrirupa

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-01-12 14:33 UTC, nicklemmon requested changes
@shrirupa I left some comments for you - nothing major that I can see though it is difficult to test locally obviously.

2021-01-12 14:33 UTC, nicklemmon commented on cypress/fixtures/usage/200.get.no-results.json
> +  "results": {
So the API will *always* return this data structure? I would think the `"start"` and `"end"` values wouldn't be specific dates if so.

2021-01-12 14:33 UTC, nicklemmon commented on cypress/tests/integration/accounts/usage/usagePage.spec.js
> +      cy.wait(['@usageReq']);
An array shouldn't be needed here - but maybe you had a reason for introducing it?

2021-01-12 14:33 UTC, nicklemmon commented on src/pages/usage/components/MessagingUsageChart.js
> +    thresholdIndex === -1 || planVolume === -1
Is there any way we could store this `-1` value in a way that makes it more self-documenting?

Like a constant maybe?

```
// And here is a comment linking to the API docs explaining this value
const UNLIMITED_VOLUME = -1
```

Then later:
```
planVolume === UNLIMITED_VOLUME
```

2021-01-12 14:33 UTC, nicklemmon commented on src/reducers/usage.js
> +export default (state = initialState, { type, payload }) => {
So this isn't in use yet, you just wanted to set it up so people in the future use it safely?

2021-01-12 14:33 UTC, nicklemmon commented on src/selectors/accountBillingInfo.js
> +const getTransmissionsUsageFromUsageApi = state => _.get(state, 'usage.messaging');
Is there any way you could add some notes explaining why you might want to get this data from the usage API vs. the account API? Or maybe just links to docs or something.

2021-01-12 17:07 UTC, shrirupa commented on cypress/fixtures/usage/200.get.no-results.json
> +  "results": {
yes, so api will always return that data structure. start and end dates being almost always billing cycle dates.

2021-01-12 17:17 UTC, shrirupa commented on src/pages/usage/components/MessagingUsageChart.js
> +    thresholdIndex === -1 || planVolume === -1
good point!

2021-01-12 17:38 UTC, shrirupa commented on src/reducers/usage.js
> +export default (state = initialState, { type, payload }) => {
no actually, its in use now here `getTransmissionsUsageFromUsageApi = state => _.get(state, 'usage.messaging');`

2021-01-12 17:41 UTC, shrirupa commented on src/selectors/accountBillingInfo.js
> +const getTransmissionsUsageFromUsageApi = state => _.get(state, 'usage.messaging');
usage is in weird place in app actually, we have messaging usage being returned from GET account/include=usage but not roles and tenants have access to this and we also have usage from GET /usage and more tenants and user have access to this. for specific roles that have access, its best to consult access library. https://github.com/SparkPost/access/blob/master/lib/token-access.js

2021-01-12 17:44 UTC, shrirupa commented on src/selectors/accountBillingInfo.js
> +const getTransmissionsUsageFromUsageApi = state => _.get(state, 'usage.messaging');
Added the same comment above these selectors.

2021-01-12 18:43 UTC, nicklemmon requested changes
@shrirupa I found a couple of issues that I missed earlier - sorry about that.

After these we should be able to move forward.

2021-01-12 18:43 UTC, nicklemmon commented on cypress/tests/integration/accounts/usage/usagePage.spec.js
>      });
Should have caught this earlier, but looks like this can be removed entirely - except in the tests that are explicitly stubbing a different account response (like the enterprise and annual plan tests).

So that means waiting for `'@accountReq'` in nearly every test except for those can be removed.

2021-01-12 18:43 UTC, nicklemmon commented on src/selectors/accountBillingInfo.js
> +//GET account/include=usage but not roles and tenants have access to this and
Typo here "but not roles and tenants" should be "but not all roles and tenants"

2021-01-12 21:46 UTC, shrirupa commented
@nicklemmon  Thanks for the feedback! This is ready for last pass.

2021-01-12 22:07 UTC, nicklemmon commented
@shrirupa Looks like that error state test might be a little flaky. Mind taking a look? Is there a missing `cy.wait()` maybe?

2021-01-13 14:29 UTC, shrirupa commented
> @shrirupa Looks like that error state test might be a little flaky. Mind taking a look? Is there a missing `cy.wait()` maybe?

Looks like I missed removing one accountReq. They should all pass now.

2021-01-13 15:35 UTC, nicklemmon approved these changes

2021-01-13 15:37 UTC, merged