SA-1956 - (UI) Don't allow "break down by" if comparing by that resource type
SparkPost/2web2ui pull request #2009
Opened 2021-01-13 18:18 UTC by nicklemmon

[SA-1956](https://sparkpost.atlassian.net/browse/SA-1956)

### What Changed

- `GroupByOption` filters by the current active comparison to remove it from the "Break Down By" select options when present

### How To Test

1. Go to `/signals/analytics` and add active comparisons
2. Click on the select labelled "Break Down By" and verify that the comparison type is not present in the list
3. Remove any active comparisons and verify that all select options render as expected

### To Do

- [ ] Incorporate feedback

2021-01-13 18:19 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/CompareByGroupByTable.js
> +import { ApiErrorBanner, Empty, PanelLoading, TableCollection, Unit } from 'src/components';
I just re-organized some imports in this component while I was here

2021-01-13 21:03 UTC, kchu1337 requested changes

2021-01-13 21:03 UTC, kchu1337 commented on src/pages/reportBuilder/components/tests/GroupByOption.test.js
> +    mockReportBuilderContext({ comparisons: [{ type: 'Subaccount', value: '123456' }] });
If you do remove the Once, then you should probably just do     
```js
useReportBuilderContext.mockImplementationOnce((() => ({
      state: { comparisons: [{ type: 'Subaccount', value: '123456' }] },
    })));
```

2021-01-13 21:18 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByOption.js
> +          (key === 'watched-domain' && !topDomainsOnly)
I did that originally but I thought it was confusing to read because of the outer `!` - which is kind of confusing to begin with. Not really sure why that's there to be honest.

Which do you think is easier to read?

2021-01-13 21:18 UTC, nicklemmon commented on src/pages/reportBuilder/components/tests/GroupByOption.test.js
> +  return useReportBuilderContext.mockImplementationOnce(() => ({
Cool, that would be great. Let me try it.

2021-01-13 21:21 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByOption.js
> +          (key === 'watched-domain' && !topDomainsOnly)
Looking at it again I think you're right actually.

2021-01-13 21:36 UTC, kchu1337 commented on src/pages/reportBuilder/components/GroupByTable/GroupByOption.js
> +          (key === 'watched-domain' && !topDomainsOnly)
The outer ! confused me too. But it's there because there is no `.omit` and we have to use `filter`. Basically it makes the inside evaluations easier to understand. Basically omit this option when any of the below conditions are true. 
The other way around would be to keep this option when all of the below conditions are false.

2021-01-14 14:13 UTC, nicklemmon commented
@kchu1337 Just incorporated your feedback. Ready for another pass when you have time.

2021-01-14 18:12 UTC, kchu1337 requested changes

2021-01-14 18:12 UTC, kchu1337 commented on src/pages/reportBuilder/components/tests/GroupByOption.test.js
> +    // mockReportBuilderContext();
Left a comment in.

2021-01-14 19:35 UTC, nicklemmon commented on src/pages/reportBuilder/components/tests/GroupByOption.test.js
> +    // mockReportBuilderContext();
🤦

2021-01-14 20:16 UTC, nicklemmon commented
@kchu1337 Ready for another pass for real this time

2021-01-15 15:34 UTC, kchu1337 approved these changes

2021-01-19 19:05 UTC, merged