SA-1957: Added deliverability metrics to the metrics drawer
SparkPost/2web2ui pull request #2010
Opened 2021-01-14 14:35 UTC by PatrickSison

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-02-05 14:49 UTC, nicklemmon requested changes
@PatrickSison I left a few comments for you. A couple of things:

1. There aren't any automated tests backing up these changes. Additionally, the integration tests that already exist are broken as a result.
2. This seems like two tickets in one? Shouldn't that banner in the `MetricsForm` be one ticket and the multiselect be another? Maybe not

It sounds like you still had some things to push up so you may have already fixed some of these things! Sorry about that.

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +              </ScreenReaderOnly>
Will this UI *always* be paired with a `<table />`? I would think potentially not. If that's the case, this content should be controlled by a prop.

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +              </ScreenReaderOnly>
Not to mention, these directions should not conditionally render just when the 'Select All' checkbox is present? The directions would apply no matter which checkboxes are rendered.

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> + * @description Attaches selectAll and click behavior for the checkboxes.
Would be good to add `@param` info here as well

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +      if (action.name === 'selectAll') {
Should there just be another action, `SELECT_ALL` instead of putting a lot of logic within a single case? Seems like this isn't really taking advantage of the legibility benefits that a state reducer can offer with so many conditions within a particular case.

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +import React, { useState, useReducer, useCallback, useMemo } from 'react';
Since this is a global, re-usable component we definitely want some unit tests to back this up - especially since there is a lot of state management logic in the hook that should be really well supported.

2021-02-05 14:49 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +  const allCheckboxesChecked = checkedCheckboxes?.length === checkboxes.length;
To be safer, it may be worth wrapping these in a `Boolean()`

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/useGroupByTable.js
> +      );
I was able to break the page by:

1. Breaking down by subaccount
2. Selecting all of the checkboxes in the multiselect
3. Unchecking the first checkbox

<img width="1334" alt="Screen Shot 2021-02-05 at 9 30 16 AM" src="https://user-images.githubusercontent.com/3613392/107046657-e2091980-6794-11eb-934c-077a145d7edf.png">

The following API request failed with a 400:
http://api.sparkpost.test/api/v1/metrics/deliverability/subaccount?delimiter=,&from=2021-01-29T09:00&metrics=&precision=hour&rollup=true&timezone=America%2FNew_York&to=2021-02-05T09:29

Looks like somehow all of the metrics were cleared.

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> +    : ['count_spam', 'count_inbox', 'inbox_folder_rate', 'spam_folder_rate'];
There is a lot of logic alongside the DOM rendering. It may be time to break this out in to a `useMetricsForm` hook

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> -  const renderMetrics = metrics =>
Nice. Thanks for moving this. Definitely no need to have these functions.

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> +                              <Checkbox
<img width="493" alt="Screen Shot 2021-02-05 at 9 36 28 AM" src="https://user-images.githubusercontent.com/3613392/107047310-ae7abf00-6795-11eb-8c0c-5dcf583aa6e5.png">

Are these supposed to be connected? When I check them the state changes in both `Expandable` instances

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> +                              <Checkbox
Hovering over these disabled checkboxes renders a tooltip with empty content:
<img width="252" alt="Screen Shot 2021-02-05 at 9 37 49 AM" src="https://user-images.githubusercontent.com/3613392/107047509-e4b83e80-6795-11eb-9dff-edc520e544e6.png">

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/components.js
> +              showIcon={false}
🤔 I don't think I understand why this would be hidden - now it just surprises the user that it opens in a new tab, going against our pattern.

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
>    Engagement: 'Interaction in messages in the inbox',
I know this wasn't introduced in this ticket, but this is grammatically incorrect. Should be:

> "Interaction with messages in the inbox"

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +            <Column width={4 / 12}>{/* TODO: Include search bar for later */}</Column>
Since this will be available to end users before we have the search bar, do we want to leave an empty column like this? Might be more of a UX question but it looks weird to me.

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +    if (!formattedData.length) {
might be good to wrap this in a `Boolean()`

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +        {row[key] !== undefined && row[key] !== null ? (
Could be simplified to `Boolean(row[key])`, right?

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +      enabled: reportOptions.isReady && groupBy,
For the `react-query` upgrade, important to wrap this in `Boolean()` as well.

2021-02-05 14:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +  const hasD12yMetricsEnabled = useSelector(state =>
Same as some of the other UI, there is a *lot* of business logic alongside the DOM rendering. Is it time to break this out in to a hook?

2021-02-09 20:35 UTC, PatrickSison commented on src/pages/reportBuilder/components/GroupByTable/GroupByTable.js
> +  const hasD12yMetricsEnabled = useSelector(state =>
Yeah, probably worth already breaking out. I'll update that

2021-02-09 20:48 UTC, PatrickSison commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> -  const renderMetrics = metrics =>
This actually solved the issue of the checkbox tabbing behavior. Coincidentally it is also code cleanup

2021-02-10 15:30 UTC, PatrickSison commented on src/helpers/metrics.js
> +  const hasPanel = dataSource.includes('panel');
Add more unit testing around this

2021-02-10 15:30 UTC, PatrickSison commented on src/helpers/metrics.js
> +      return metric;
Should maybe throw in some other state

2021-02-10 15:31 UTC, PatrickSison commented
Add testing around feature flags being off

2021-02-10 20:22 UTC, nicklemmon requested changes
@PatrickSison Big PR means big feedback! Let me know what questions you have.

Also, looks like there are some test failures though I'm sure you've seen that by now.

2021-02-10 20:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/components.js
> +    <Box padding="500" pb="100">
Rather than having padding on this component, the components themselves should have a `<Stack />` wrapping them.

2021-02-10 20:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/components.js
> +    <Box padding="500" pb="100">
Can this not fit inside `Drawer.Content` to handle the padding? I'm sure there is some reason it isn't like that.

2021-02-10 20:22 UTC, nicklemmon commented on src/pages/reportBuilder/components/MetricsForm/components.js
> +              showIcon={false}
By hidden, I mean why would the icon be hidden? Isn't this breaking our pattern for external links?

2021-02-10 20:22 UTC, nicklemmon commented on src/config/metrics.js
> +    product: 'deliverability',
This could just be a data problem, that I feel like that value shouldn't be 0 for "Moved to Inbox Count"? This is our usual test account in staging with all deliverability metrics applied:
![Screen Shot 2021-02-10 at 3 18 19 PM](https://user-images.githubusercontent.com/3613392/107566837-5851b580-6bb3-11eb-908f-b5f4c3bd5f8b.png)

2021-02-10 20:36 UTC, PatrickSison commented on src/pages/reportBuilder/components/GroupByTable/GroupByOption.js
> +      <Column width={4 / 12}>{renderDomainsCheckbox()}</Column>
This checkbox only exists if you select Recipient Domains. There's a checkbox for "Top Domains". Haley is still looking into if we need this or this can get removed

2021-02-10 20:41 UTC, PatrickSison commented on src/pages/reportBuilder/components/MetricsForm/MetricsForm.js
> +                              <Checkbox
Yeah, once the feature flag gets removed, we'll remove the checkbox. I suppose though we might as well remove it from the Deliverability category in the mean time until the time of feature flag removal

2021-02-10 20:45 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/constants/index.js
> +export const INBOX_METRICS = [
Yeah, gonna rename some of the Inbox Tracker stuff to Deliverability for the sake of readability/searchability

2021-02-10 20:45 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/metricsForm.spec.js
> +  describe('regular', () => {});
Nope. Tests primarily blended in with `reportPage.spec.js`

2021-02-12 05:38 UTC, PatrickSison commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +      ...checkboxes.map(checkbox => ({ ...checkbox, isChecked: false })),
Yeah, I'll leave a todo. thought about more customization for later on

2021-02-12 05:40 UTC, PatrickSison commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +    values: targetCheckboxes.map(({ name }) => name),
Values is just returning list of selected values. Checkboxes can always be completely empty, but if the flag for allowEmpty is false, then if all checkboxes are empty, then all possible values are returned

2021-02-12 06:14 UTC, PatrickSison commented on src/pages/reportBuilder/components/MetricsForm/components.js
> +    <Box padding="500" pb="100">
Only reason that padding is on box instead of default `Drawer.Content` padding is because of the tabs spanning full width.

2021-02-12 06:18 UTC, PatrickSison commented on src/config/metrics.js
> +    product: 'deliverability',
It's the data coming back as 0

2021-02-12 14:00 UTC, PatrickSison commented on src/pages/reportBuilder/components/GroupByTable/GroupByOption.js
> +      <Box marginTop="600">
Yeah. I'm going to reset it back for now

2021-02-12 14:42 UTC, PatrickSison commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +  const [isPopoverOpen, setIsPopoverOpen] = useState(false);
Do you think this is something that can be in a later iteration?

2021-02-12 14:44 UTC, PatrickSison commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +            <ScreenReaderOnly>{label}</ScreenReaderOnly>
I'm not quite understanding of what the path forward for this is. This was a copy over from the domains version of this component. Should we remove this tag since the label tag exists above?

2021-02-16 13:54 UTC, nicklemmon commented on src/components/MultiSelectDropdown/MultiSelectDropdown.js
> +            <ScreenReaderOnly>{label}</ScreenReaderOnly>
Well it needs to be there, but the children of `ScreenReaderOnly` should not be the same as `label`. Something like this:

```jsx
<Popover trigger={<button/>}>
  <ScreenReaderOnly>{screenReaderOnlyDirections</ScreenReaderOnly>
  
  {/* checkboxes go here *}
</Popover>
```

And it needs to be the first child of the `<Popover>` _not_ the popover button.

2021-02-16 14:30 UTC, nicklemmon requested changes
@PatrickSison Two tiny things - one of them is a question and I'm not sure what the expectation is.

2021-02-16 14:30 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/metricsForm.spec.js
> +import { PAGE_URL, INBOX_METRICS } from './constants';
These look great. Well done.

2021-02-16 14:30 UTC, nicklemmon commented on src/components/MultiCheckboxDropdown/MultiCheckboxDropdown.js
> + */
Nice. Love it.

2021-02-16 14:30 UTC, nicklemmon commented on src/components/MultiCheckboxDropdown/MultiCheckboxDropdown.js
> + * @name useMultiSelect
This should probably be `useMultiCheckbox` now?

2021-02-16 14:30 UTC, nicklemmon commented on src/components/MultiCheckboxDropdown/MultiCheckboxDropdown.js
> +                  onChange={checkbox.onChange}
For some reason the popover is closing `onChange` - is that expected?

2021-02-16 18:18 UTC, nicklemmon approved these changes
@PatrickSison Looks good! Approved.

2021-02-17 14:35 UTC, merged