[FE-1329] set HibanaEnabled to be true
SparkPost/2web2ui pull request #2015
Opened 2021-01-15 21:41 UTC by shrirupa

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-01-20 16:30 UTC, nicklemmon requested changes
@shrirupa Very glad to see this green! I left a few comments here and there.

Additionally, I would go ahead and remove the OG-specific steps from our CircleCI config. Oddly enough the "OG" integration tests are just the Hibana tests at this point so no need to keep them both running. If you would like help doing that let me know.

2021-01-20 16:30 UTC, nicklemmon commented on src/pages/blocklist/components/tests/IncidentsCollection.test.js
> +    // expect(queryByText('Last 7 Days')).toBeInTheDocument(); TODO: figure out why this failing
Oddly enough I'm not seeing where this would have been rendering to begin with.

```js
const columns = [
  { label: 'Resource', sortKey: 'resource' },
  { label: 'Blocklist', sortKey: 'blocklist_name' },
  { label: 'Date Listed', sortKey: 'occurred_at' },
  { label: 'Date Resolved', sortKey: 'resolved_at' },
  { label: '' },
];
```

I don't see a `dateRange` column anywhere.

2021-01-20 16:30 UTC, nicklemmon commented on src/pages/blocklist/tests/WatchlistAddPage.test.js
>      const watchlistAdd = jest.fn(() => promise);
Changing line 61 to the following appears to fix this one:
```js
const save = getByRole('button', { name: saveText });
```

2021-01-20 16:30 UTC, nicklemmon commented on src/pages/templates/components/tests/SavedIndicator.test.js
>  import TestApp from 'src/__testHelpers__/TestApp';
Honestly I think it's fine to just delete this test - I don't think it's terribly valuable.

2021-01-20 18:43 UTC, shrirupa commented on cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js
> -import { IS_HIBANA_ENABLED, USERNAME } from 'cypress/constants';
good point!

2021-01-20 18:47 UTC, shrirupa commented on src/pages/blocklist/tests/WatchlistAddPage.test.js
>      const watchlistAdd = jest.fn(() => promise);
😄  Thanks for the fix!

2021-01-20 18:54 UTC, shrirupa commented
@nicklemmon  Thanks for the feedback and fixes! I have addressed all the comments (need to rebase, this PR will have rebase required in spec file till the day we deploy 😅 ). I will need help removing turning off OG tests in circle ci, and is that something we do after we deploy ?

2021-01-21 17:56 UTC, nicklemmon requested changes
@shrirupa Some very nit-picky points of feedback at this point. No need to address now - it can wait until a future rebase prior to the release.

2021-01-21 17:56 UTC, nicklemmon commented on cypress/tests/integration/navigation/navigation.spec.js
> +describe('the Hibana navigation', () => {
This can just be 'the navigation' - no need to call it 'the Hibana navigation'

2021-01-21 17:56 UTC, nicklemmon commented on cypress/tests/integration/dashboard/dashboardPage.spec.js
> +describe('Version 2 of the dashboard page', () => {
Same as the navigation spec - this can just be 'The dashboard page' instead of referencing version 2.

2021-01-22 14:53 UTC, nicklemmon approved these changes
@shrirupa This looks good. We'll need to rebase and re-review before launch.

2021-01-25 14:49 UTC, merged