[AC-1836] UI: Enforce 2FA required changes
SparkPost/2web2ui pull request #2042
Opened 2021-01-26 21:29 UTC by shrirupa

[AC-1836] UI: Enforce 2FA required changes

### What Changed

- When account option `enforce_tfa_required` is enabled then 
     - On account settings page, “2FA Required” status should read “Required” and the toggle button should be disabled at 
     “On” position 

      - Show a banner under the 2FA panel saying: “Two-factor authentication is required for your account.” 

      - The SSO section should be hidden when the when the account option “enforce_tfa_required” is true
- When tfa_required is true then Disable 2FA should read Reset 2FA

### How To Test

- Enable ''enforce_tfa_required" for your account and verify the state mentioned in 1st point
- Enable "tfa_required" and verify the state mentioned in 2nd point 

### To Do

- [ ] Address feedback

2021-01-27 15:18 UTC, shrirupa commented
@nicklemmon  not sure why the test is failing the checkbox looks disabled in the screenshot in ci artifacts

2021-01-27 17:28 UTC, nicklemmon reviewed
@shrirupa I left a few comments, and I'm pretty sure I figured out the cause of the Cypress test failure. Let me know what questions you have.

2021-01-27 17:28 UTC, nicklemmon commented on src/pages/profile/components/DisableTfaModal.js
> +                    : 'Disable 2FA'}
To me, this is a little hard to read.

Could this work? It's a little more verbose. Just my opinion really so feel free to ignore this if you disagree:
```jsx
{tfaRequired && togglePending ? 'Resetting...' : 'Reset 2FA'}
{!tfaRequired && togglePending ? 'Disabling...' : 'Disable 2FA'}
```

2021-01-27 17:28 UTC, nicklemmon commented on src/pages/profile/components/tests/__snapshots__/DisableTfaModal.test.js.snap
> +        <Stack>
I know I keep repeating myself here, but again - can we just delete these snapshot tests entirely?

2021-01-27 17:28 UTC, nicklemmon commented on cypress/tests/integration/accounts/account-settings/accountSettingsPage.spec.js
> +    cy.findAllByRole('checkbox', { id: 'enforceTfa' })
It looks like this query is returning the wrong `<Toggle />` - it's grabbing the second checkbox instead of the first:
![Screen Shot 2021-01-27 at 12 12 15 PM](https://user-images.githubusercontent.com/3613392/106027623-1136d100-6099-11eb-9736-741f90313240.png)

It looks like `id` is not a valid option that can be passed in here:
https://testing-library.com/docs/queries/byrole

So I think the solution is to do a few things:
1. Add a `label` to the `<Toggle />` so that it's easier to query and addresses the HTML/a11y bug
2. Remove the `findAllBy*` and use `findBy` with the `name` option
3. Incorporate the `cy.wait()` for the accounts request if possible

That should clear it up.

2021-01-27 18:58 UTC, shrirupa commented on src/pages/account/components/EnforceTfaPanel/TogglePanelSection.js
> +                id="enforceTfa"
ahh, got it! Thanks!

2021-01-28 14:51 UTC, shrirupa commented
@nicklemmon Thanks for the feedback! I have addressed all the feedback, this should be ready for another pass.

2021-01-28 20:30 UTC, nicklemmon approved these changes
@shrirupa I had a couple of more nit-picky comments - though things are working as expected.

2021-01-29 14:00 UTC, nicklemmon requested changes
@shrirupa - Sorry about this but I found one tiny addition to a Cypress test that will improve things. I tested out my suggestion locally and it does work so you should be able to just plug and play.

I'll approve afterwards and we can deploy.

2021-01-29 14:34 UTC, nicklemmon approved these changes
@shrirupa 🎉

2021-01-29 14:35 UTC, merged