FE-1354 -
SparkPost/2web2ui pull request #2045
Opened 2021-01-26 23:37 UTC by nstanard

### What Changed
- Correct custom eslint rule folder location (so they run with the other tests)
- jest config now uses an env variable for match location
- package.json now has a script alias to call only the custom eslint rules

### How To Test
- run `npm run test` and the new `npm run test-custom-eslint-rules`

### To Do
- [ ] Feedback

2021-01-27 16:13 UTC, nicklemmon requested changes
@nstanard Left a few comments for you - let me know what questions you have

2021-01-27 16:13 UTC, nicklemmon commented on .eslintplugin/require-is-first-render-empty-state-loading.js
> +                    message: 'Page with hibanaEmptyStateComponentAttr and loading attribute missing isFirstRender in the assignment expression.',
👍

2021-01-27 16:13 UTC, nicklemmon commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
In VSCode locally I'm not encountering the error here - I'm looking at `src/pagesReportBuilder/ReportBuilder` and I changed the `Page` props to:

```js
<Page
   title={!showReportBuilderEmptyState ? 'Analytics Report' : null}
   primaryArea={!showReportBuilderEmptyState ? getPrimaryArea() : null}
   empty={{
     trackingOnly: showReportBuilderEmptyState,
    }}
>
```

2021-01-27 20:21 UTC, nstanard commented on jest.config.js
> +  process.env.TEST_MATCH_LIST || [matchSrc, matchScripts, matchProjectESLintRules].join('|');
I've reverted this file.

2021-01-27 20:23 UTC, nstanard commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
I'm looking to leave a script alias in place do explicitly call out how to just test those rules. I did chain the other test command though.

2021-01-27 20:24 UTC, nstanard commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
You'll get the error if you stage that and try to commit, but I'm not seeing VSCode highlight for this. I'm not exactly sure why right now.

2021-01-27 21:16 UTC, nstanard commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
NVM, this is working for me now locally!

2021-01-28 13:44 UTC, nicklemmon commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
Hmm, not sure I agree - we have tests all over the app and don't have a custom script to handle each location? What makes this folder different than those? 🤔

2021-01-28 13:45 UTC, nicklemmon commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
Let me check and see if it works for me too - probably doing something wrong on my end.

2021-01-28 17:30 UTC, nstanard commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
That's a fair question. My thought is that if we leave a script in place that calls out this top level rule directory it will make it more obvious to people less familiar with the project as they ramp up and get to know it. The project specific eslint rule tests aren't currently running when on master for `npm run test`, that's because the location of those rules changed but the references in jest and the package file didn't get updated. I am hoping that having this alias helps make it more obvious at a glance what they are and where they exist. I don't expect the jest integration to change again in the near future, but I do think having an alias for the rule tests helps to accomplish "documentation through code".

2021-01-29 13:38 UTC, nicklemmon commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
I appreciate what you're trying to do - I just feel like the Jest config already accomplishes that since it has that config option for which directories to target pretty explicitly.

That being said, if you feel strongly about it let's leave it in. How about this - I'll set a reminder to myself in 4 or 5 months or so to circle back. If it's something we've found useful we leave it in, otherwise we take it out. What do you think?

2021-01-29 13:43 UTC, nicklemmon commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
Actually, come to think of it it looks like the `jest.config.js` wasn't updated correctly so that's a problem!

```
testMatch: [
  '<rootDir>/src/**/__tests__/**/*.js?(x)',
  '<rootDir>/(eslint-rules|src|scripts)/**/*.test.js?(x)',
],
```

2021-01-29 13:44 UTC, nicklemmon commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
Hmm, still not seeing the error - I was even able to commit the changes successfully. What JSX are you using exactly to reproduce the warning?

2021-01-29 18:07 UTC, nstanard commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
ugh, that was updated/fixed on this pr, but then I rebased and once again, it got reverted (in the rebase I just did)

2021-01-29 18:15 UTC, nstanard commented on .eslintplugin/utils/eslint-test-runner.js
>  import { Linter } from 'eslint';
We should write a rule for this 😁

2021-01-29 18:16 UTC, nstanard commented on .eslintplugin/tests/require-is-first-render-empty-state-loading.test.js
> +    },
I'm just removing the loading attribute from the `<Page />` instance to get VSCode to flag it.
![image](https://user-images.githubusercontent.com/4204806/106312075-bda8bc80-622b-11eb-9bcc-27677ba38644.png)

2021-02-01 19:13 UTC, nstanard commented on package.json
> +    "test-custom-eslint-rules": "TEST_MATCH_LIST=.eslintplugin node scripts/test.js --env=jsdom --config=./jest.config.js",
I've created myself a few bash aliases to give myself this outside the package file and removed this from the PR.

2021-02-02 00:29 UTC, nicklemmon approved these changes
@nstanard It works! Looks good to me. Let's get this merged in the AM. There won't be anything to verify I suppose.

2021-02-02 13:30 UTC, merged