SA-2042: Report Builder update for timezones
SparkPost/2web2ui pull request #2046
Opened 2021-01-28 14:30 UTC by PatrickSison

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-02-04 16:59 UTC, nicklemmon requested changes
@PatrickSison I have a little bit of feedback so far - I was running in to some issues with our usual test account on staging. Mind taking a look at the dashboard on this branch and see what you see?

2021-02-04 18:44 UTC, PatrickSison commented on src/helpers/date.js
> +  moment.tz(args.join(' '), FORMATS.INPUT_DATETIMES, true, timezone);
I think the only reason I kept it as moment.tz is the fact that `INPUT_DATETIMES` was an array with different formats. I wonder if the other formats are even used though so might be worth changing

2021-02-04 19:06 UTC, PatrickSison commented on src/helpers/date.js
> +  moment.tz(args.join(' '), FORMATS.INPUT_DATETIMES, true, timezone);
It's to parse it with the context of a timezone in mind. Otherwise, without providing a timezone, it assumes local timezone (which would be incorrect)

2021-02-09 14:22 UTC, nicklemmon requested changes
@PatrickSison Almost there! I have a few comments, re: testing.

And per our convo on Slack, how query params are handled needs to be tweaked:

* Same dates in the URL query params for `to` and `from` as everywhere else (as in they match the selected timezone)/
* Not including the `to` and `from` params when there is no custom range set

2021-02-16 15:11 UTC, nicklemmon approved these changes
@PatrickSison Everything seems to be working as expected - one thing we spoke about earlier was the dates in the URL? It looks like they are still in UTC? Is this going to cause confusion?

2021-02-18 15:08 UTC, nicklemmon approved these changes
@PatrickSison This looks good - I had one comment (about a comment!) that I think has a typo or some missing content.

2021-02-18 15:08 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +      //If coming from copy and pasted URL with report and overridden filters, should have repo
> "should have repo"

Not sure what this means?

2021-02-18 18:26 UTC, merged