SA-2022 - Cleanup non rollups code
SparkPost/2web2ui pull request #2059
Opened 2021-02-03 21:18 UTC by nicklemmon

[SA-2022](https://sparkpost.atlassian.net/browse/SA-2022)

### What Changed

### How To Test

### To Do

- [ ] Should we rename/remove the `getRollupsPrecision` helper?

2021-02-05 23:19 UTC, kchu1337 requested changes
Added some feedback. I didn't check that you removed all references, but I left feedback for the ones you did remove.

2021-02-05 23:19 UTC, kchu1337 commented on src/actions/reportOptions.js
> +    const getPrecision = getRollupPrecision;
Can probably just do import { getRollupPrecision as getPrecision}

2021-02-05 23:19 UTC, kchu1337 commented on src/components/datePicker/DatePickerNew.js
> +  const getPrecision = getRollupPrecision;
Same here. import { getRollupPrecision as getPrecision}

2021-02-05 23:19 UTC, kchu1337 commented on src/components/datePicker/ManualEntryFormNew.js
> +  const getPrecision = getRollupPrecision;
Same here. import { getRollupPrecision as getPrecision}

2021-02-05 23:19 UTC, kchu1337 commented on src/pages/reportBuilder/context/ReportBuilderContext.js
> +      const getPrecision = getRollupPrecision;
Same here. import { getRollupPrecision as getPrecision}

2021-02-09 00:37 UTC, nicklemmon commented on src/actions/reportOptions.js
> +    const getPrecision = getRollupPrecision;
That's a great idea

2021-02-09 00:43 UTC, nicklemmon commented on src/pages/reportBuilder/components/DateTimeSection/tests/DateTimeSection.test.js
> +  it('should not disable fields', () => {
Yeeah - this isn't really a global component either so we can probably just `rm -rf` and move on.

2021-02-09 01:03 UTC, nicklemmon commented
@kchu1337 Ready for another look when you have time

2021-02-09 16:18 UTC, kchu1337 approved these changes

2021-02-09 18:51 UTC, merged