SA-2095: Do not display report builder empty state for subaccount reporting users
SparkPost/2web2ui pull request #2060
Opened 2021-02-03 23:18 UTC by bkemper

### What Changed

- 

### How To Test

- ?

2021-02-03 23:53 UTC, kchu1337 requested changes

2021-02-03 23:53 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +  canManageDomains: hasGrants('sending_domains/manage'),
```suggestion
  canManageDomains: hasGrants('sending_domains/manage')(state),
```

2021-02-03 23:53 UTC, kchu1337 commented on src/pages/reportBuilder/ReportBuilder.js
> +  isSubaccoutReporting: hasRole(ROLES.SUBACCOUNT_REPORTING),
```suggestion
  isSubaccoutReporting: hasRole(ROLES.SUBACCOUNT_REPORTING)(state),

```

2021-02-04 03:56 UTC, kchu1337 approved these changes

2021-02-04 14:01 UTC, nicklemmon commented
I hate to be that guy, but should have some tests to back up this change?

2021-02-04 14:33 UTC, bkemper commented
> I hate to be that guy, but should have some tests to back up this change?

👏 👏 👏 Thank you for holding us accountable!  It is our responsibility to put some test coverage around this fix.  Kevin and I discussed it last night and I forgot to add a todo item to the description.

2021-02-04 18:03 UTC, kchu1337 approved these changes

2021-02-04 18:40 UTC, merged