FE-1353 - dont show onboarding for on prem (allow_events_ingest)
SparkPost/2web2ui pull request #2061
Opened 2021-02-04 19:05 UTC by nstanard

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-02-04 21:03 UTC, nstanard commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
Is this the correct condition? Shouldn't it be `getAccountUiOptionValue` with state passed in? Or maybe state gets passed in later where these objects get used. But shouldn't it be `getAccountUiOptionValue` not `hasAccountOptionEnabled` @PatrickSison @bkemper ?

2021-02-04 21:20 UTC, PatrickSison commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
Account option are tied to the account, and UI options are an nested object inside options. The account object would be similar to something like this

```javascript
{
  options: {
    allow_events_ingest: true,
    ...,
    ui: {
      custom_option: true,
      ...
    }
  }
}

```

2021-02-04 21:21 UTC, PatrickSison commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
The UI object is freeform but the other options are a defined list. Those 2 functions are different accessors. 1 for main options on the top level, the second would be for just the UI options

2021-02-04 21:23 UTC, nstanard commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
Sorry, I should have been more specific - the reason I ask is because the fixtures have the following object structure:

```
"options": {
      "ui": {
        ...
        "allow_events_ingest": true,
        ...
      }
}
```

2021-02-04 21:27 UTC, nstanard commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
Meanwhile.... our actual redux store is both structures.... 🤦 

![image](https://user-images.githubusercontent.com/4204806/106957340-82abfa80-66fd-11eb-83af-ec8a4737604f.png)

2021-02-04 21:30 UTC, bkemper commented on src/config/routes/signals.js
>      condition: hasAccountOptionEnabled('allow_events_ingest'),
It is better to use `hasAccountOptionEnabled` vs `getAccountUiOptionValue` when the expectation is a boolean value.  `has` will guarantee a boolean value where `getAccountUiOptionValue` may provide you either a boolean or undefined.  The use case for `getAccountUiOptionValue` was on the dashboard when we wanted to save the current step you were on as a string.

Regarding usage, this is a bad example because route configuration doesn't have access to state.  This condition is eventually handed off to `<AccessControl />`, see https://github.com/SparkPost/2web2ui/blob/master/src/components/auth/ProtectedRoute.js#L15

2021-02-05 18:53 UTC, nstanard commented on cypress/fixtures/account/200.get.json
> +      "allow_events_ingest": true,
this change causes at least the following tests to fail:

```
it.only('all nav links renders correctly for templates', () => {
it.only('all nav links renders correctly for reporting user', () => {
```

2021-02-09 22:23 UTC, shrirupa commented on cypress/fixtures/account/200.get.on-prem.json
> +  "results": {
I think account/200.get.has-integration-page.json is for the same purpose, we should probably keep only one of them.

2021-02-10 22:12 UTC, shrirupa requested changes
~when i created a new account, even then I didn't see the other on-boarding steps ~

2021-02-10 22:24 UTC, shrirupa approved these changes

2021-02-11 21:10 UTC, merged