SA-1827: UX feedback for report builder
SparkPost/2web2ui pull request #2070
Opened 2021-02-10 14:11 UTC by PatrickSison

### What Changed

- Bounce reason table includes count and percent now
- Date picker limits to 6 months

### How To Test

- Go to report builder
- Open date picker and verify that date picker doesn't allow for dates before 6 months before today
- Close date picker and add any bounce metrics
- Go to bounce tab
- Verify that count and percent are now included in value

### To Do

- [ ] Address feedback

2021-02-16 15:24 UTC, nicklemmon approved these changes
@PatrickSison Everything works well - just hoping to see one more test case added before moving forward.

Thanks!

2021-02-16 15:24 UTC, nicklemmon commented on src/pages/reportBuilder/components/DateTimeSection/DateTimeSection.js
> +          datePickerProps={{
Hate to be that guy, but it would be good to have a Cypress test around this. Testing a datepicker can be a pain, but you can still use `cy.findByRole()` to do it. The datepicker is made up of of cells with `role="gridcell"` and an `aria-label` attribute:

<img width="953" alt="Screen Shot 2021-02-16 at 10 20 45 AM" src="https://user-images.githubusercontent.com/3613392/108083028-aa298e00-7040-11eb-82aa-eb330b66acef.png">

You can use those to grab the right elements and check if they are disabled appropriately. You would probably need to use `cy.clock()` as well to keep the date stable.

2021-02-16 15:25 UTC, nicklemmon requested changes
Whoops, accidentally clicked "Approve" - just hoping to see one more test case for the 6 month date range.

2021-02-17 19:35 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/dateAndTimeSection.spec.js
> +  it('should disable invalid dates the date picker', () => {
New test introduced for date picker

2021-02-17 19:35 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/dateAndTimeSection.spec.js
> +        .click()
Lol could be a cleaner way for this

2021-02-17 19:35 UTC, PatrickSison commented on src/pages/reportBuilder/components/tables/tests/BounceReasonTable.test.js
> +    expect(queryByText('5 (50%)')).toBeInTheDocument();
Intended change

2021-02-17 19:35 UTC, PatrickSison commented on src/pages/reportBuilder/components/tables/BounceReasonTable.js
> +          {numerator} (<Percent value={safeRate(numerator, denominator)} />)
This is the other change. The rest is date/time stuff after consolidating with SA-2042 PR

2021-02-22 16:09 UTC, nicklemmon approved these changes
@PatrickSison Looks good to me - I left one comment, re: how you can improve that one funny series of commands but your choice if you want to implement.

2021-02-22 16:09 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/dateAndTimeSection.spec.js
> +        .click()
it would be very repetitive, but if you click one time, check that the month is changing, then click again each time that might help prevent flakiness here

2021-02-22 16:09 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/dateAndTimeSection.spec.js
> +      cy.get('[aria-label="Tue Jul 30 2019"]').should('have.attr', 'aria-disabled', 'false');
Nice! Perfect.

2021-02-22 21:24 UTC, merged