AC-1850 - ChoosePlanPage flashes before redirecting to dashboard and adding a paid plan
SparkPost/2web2ui pull request #2077
Opened 2021-02-17 22:37 UTC by shrirupa

AC-1850 - ChoosePlanPage flashes before redirecting to dashboard and adding a paid plan

### What Changed
_Note-_ 
_Cause of this bug seemed to be coming from the actions emitted by the redux form, the form would emit a redux/@Destroy action after a successful submit which would trigger rerender of the form before the redirect to dashboard._

- moved the redirect and alert to useEffect instead of then.

### How To Test

- Sign up for a new account.
- On Choose plan page, choose a paid plan
- check if the flasing of the page is gone and you get redirected to dashboard smoothly

### To Do

- [ ] Address feedback

2021-02-19 21:30 UTC, kchu1337 requested changes

2021-02-19 21:30 UTC, kchu1337 commented on src/selectors/onboarding.js
> +          state.billingCreate.loading,
It seems like this is why it's going to the loading spinner.

2021-02-19 21:30 UTC, kchu1337 commented on src/reducers/billingCreate.js
> +        ...state,
I don't think you need to destructure state since you are already setting the 3 keys.

2021-02-19 21:30 UTC, kchu1337 commented on src/actions/billingCreate.js
> +      .catch(() => dispatch({ type: 'BILLING_CREATE__ERROR' }));
You have an extra "_"

2021-02-22 14:03 UTC, shrirupa commented on src/actions/billingCreate.js
> +      .catch(() => dispatch({ type: 'BILLING_CREATE__ERROR' }));
good catch!

2021-02-23 15:33 UTC, kchu1337 commented on src/selectors/onboarding.js
> +    billingCreateSuccess: state => state.billingCreate.success,
Nothing really happens when error is true. Do you want to add an alert?

2021-02-23 15:51 UTC, kchu1337 approved these changes

2021-02-23 16:00 UTC, merged