SA-2139
SparkPost/2web2ui pull request #2078
Opened 2021-02-18 15:42 UTC by PatrickSison

### What Changed

- Added text truncation component w/ tooltip
- Added text truncation to compare by aggregate row for user provided values

### How To Test

- Add compare by filters with long string names (I've found some decent length ones in templates)
- Decrease view port to small view
- Verify that text is properly truncated
- Verify that tooltip exists for truncated text
- Verify that tooltip doesn't exist for non truncated text

### To Do

- [ ] Add test ? Not sure how to easily test this

2021-02-18 16:45 UTC, kchu1337 submitted a review, later dismissed

2021-02-18 16:45 UTC, kchu1337 commented on src/pages/reportBuilder/components/GroupByTable/tests/components.test.js
> +import React from 'react';
What is this file for?

2021-02-18 16:45 UTC, kchu1337 commented on src/components/reportBuilder/CompareByAggregatedRow.js
> +              <TextTooltip>{comparison.value}</TextTooltip>
We have a `shrinkToFit` helper in src/helpers/string.js if that helps.

2021-02-18 16:45 UTC, kchu1337 commented on src/components/TextTooltip/TextTooltip.js
> +export default function TextTooltip({ children, id = 'text-tooltip-popover' }) {
This doesn't seem to work if you wrap the string in a `<div>`. Maybe validate that children is a string using Proptype?

2021-02-18 16:49 UTC, PatrickSison commented on src/components/reportBuilder/CompareByAggregatedRow.js
> +              <TextTooltip>{comparison.value}</TextTooltip>
Was trying not to do any JS truncation and do it through straight CSS

2021-02-18 16:49 UTC, PatrickSison commented on src/components/reportBuilder/CompareByAggregatedRow.js
> +              <TextTooltip>{comparison.value}</TextTooltip>
Especially if we got variable width. Seems like it would be useful for other cases

2021-02-18 17:05 UTC, PatrickSison commented on src/components/TextTooltip/TextTooltip.js
> +export default function TextTooltip({ children, id = 'text-tooltip-popover' }) {
Yeah, I suppose for this iteration, we should lock it down and if we find a use case for more complex children, we can implement a solution later on

2021-02-19 14:05 UTC, PatrickSison commented on src/pages/reportBuilder/components/GroupByTable/tests/components.test.js
> +import React from 'react';
I've no idea how this ended up here lol. I think this was committed to the wrong branch

2021-02-22 20:10 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +          .should('be.visible'); //Tooltip
Shouldn't we add a test for this?

2021-02-22 20:11 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +          .should('be.visible'); //Tooltip
We can use `cy.viewport` — https://docs.cypress.io/api/commands/viewport.html#Syntax

2021-02-22 20:23 UTC, bkemper commented on src/components/TextTooltip/TextTooltip.js
> +        <span ref={textRef}>{children}</span>
Like `src/components/tooltip`, I think we need the `aria-controls={id}` on the `span`.

2021-02-22 20:25 UTC, bkemper reviewed
It works for me!  I added two comments that should be addressed for both adding a quick test and adding the a11y prop.

2021-02-25 14:26 UTC, nicklemmon requested changes
@PatrickSison Just missing some unit tests for the new component you wrote - otherwise looks good.

2021-02-25 14:26 UTC, nicklemmon commented on src/components/TextTooltip/TextTooltip.js
> +import React, { useRef } from 'react';
New global component means some unit tests are needed

2021-02-25 14:30 UTC, nicklemmon commented on src/components/TextTooltip/TextTooltip.js
> +      color="gray.800"
I would think these should be controlled via props?

2021-02-25 15:58 UTC, nicklemmon approved these changes
@PatrickSison Looks good, let's do it. 👍

2021-02-25 16:00 UTC, merged