SA-2161: Allow users to search for filter and compare values with a single character in Report Builder
SparkPost/2web2ui pull request #2082
Opened 2021-02-23 17:19 UTC by bkemper

### What Changed

- Added a "Add Filter" option to the "Filter" and "Compare" value typeaheads to allow users to enter a value not found in the typeahead options

<img width="1389" alt="Screen Shot 2021-02-23 at 12 16 16 PM" src="https://user-images.githubusercontent.com/1335605/108881190-0d7f6700-75d1-11eb-8bd2-02d07aae7f78.png">

- The "Add Filter" option will not be displayed if the input value matches a typeahead option

<img width="1391" alt="Screen Shot 2021-02-23 at 12 16 29 PM" src="https://user-images.githubusercontent.com/1335605/108881329-2e47bc80-75d1-11eb-96e8-2d49868302bf.png">

- The "Add Filter" option will not be displayed if the input value matches a selected item

<img width="1390" alt="Screen Shot 2021-02-23 at 12 16 47 PM" src="https://user-images.githubusercontent.com/1335605/108881476-58997a00-75d1-11eb-9792-acab195944e9.png">
 

### How To Test

- Good question

### To Do

- [ ] specs

### Follow-Up

The following are a list of potential follow-up tickets.  Let's discuss before cutting them.

 - Typeahead Consolidation - we have several implementations which caused duplication
 - Compare onBlur behavior - the user experience is a little clunky to me, if you select something, remove, blur, then it comes back?  Is this what we want?
 - Additional messaging - we discussed in prep meeting adding additional text letting the user know about the 3 character limit, but the filter typeahead is not flexible enough to handle this addition
 - Subaccount Validation - if a non-numeric value for subaccounts is entered, the api requests will fail and display three snackbars

2021-02-23 17:23 UTC, bkemper commented on src/pages/reportBuilder/helpers/index.js
> +                    value: subaccount ? `${subaccount.name} (ID ${id})` : id,
Small, but big change.  Before the id would be set to `undefined` and would break.  Now, we proceed custom subaccount values.

2021-02-23 17:58 UTC, bkemper commented on src/pages/reportBuilder/components/ReportOptions.js
> +          <ScreenReaderOnly>Report Options</ScreenReaderOnly>
Extra credit

2021-03-01 20:49 UTC, nicklemmon requested changes
@bkemper First pass complete - I left a few comments for you.

You have a few test failures I _think_ are caused by the test vs. the actual implementation. I left a comment that explains why I think they are happening. The IP pools test failure is a known flaky test that I brought up to Shrirupa though it deserves a ticket at this point I believe. I will add it to my list to cut one.

2021-03-01 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/Typeahead.js
> +      customItemHelpText="Add Filter"
Are we still sure we want to do this? I believe the option would be read to screen reader users as:

> "Add 'Fa' Add Filter"

It doesn't really make sense?

2021-03-01 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/helpers/index.js
> +                    value: subaccount ? `${subaccount.name} (ID ${id})` : id,
Looks like there are some unit tests that support this function - should we add a test for the scenario you're describing?

2021-03-01 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/Typeahead.js
>        loading={status === 'loading'}
The loading state isn't rendering for me anymore? I don't see any loading indicator when the API is being hit.

It is rendering in the `CompareByForm` component but not the `FiltersForm`.

2021-03-01 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByForm/Typeahead.js
> +        item,
Should this be spread? The final structure is a little funny to me:
```json
{
  "content": "80-campaign",
  "isVisible": true,
  "item": {
    "type": "campaigns",
    "value": "80-campaign"
  }
}
```

2021-03-01 20:49 UTC, nicklemmon commented on src/pages/reportBuilder/components/CompareByForm/Typeahead.js
> +                {items.length ? (
For type safety, might be best to wrap this in a `Boolean()`

2021-03-01 20:49 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +      cy.findByRole('option', { name: new RegExp(text) })
Looks like using `new RegExp()` here is introducing some test failures - the `name` option already accepts both strings and regular expressions so you should be able to just whichever as you need them rather than parsing all passed-in `text` as a regular expression:
https://testing-library.com/docs/queries/byrole/

2021-03-03 11:10 UTC, bkemper commented on src/pages/reportBuilder/components/Typeahead.js
> +      customItemHelpText="Add Filter"
Discussed with UX.  Decision was to drop "Add" from the beginning.
— https://msys.slack.com/archives/GLLAW6UAX/p1614635731046900

2021-03-03 11:31 UTC, bkemper commented on src/pages/reportBuilder/components/Typeahead.js
>        loading={status === 'loading'}
This is the problem with having two variations of typeaheads.  I would need to rebuild the filter typeahead to get the loading spinner to work.  This work would probably be best done in a follow-up ticket.  The reason is the filter typeahead uses ComboBoxMenu to render the list of options and the `emptyMessage` prop to render the spinner.  With always having a custom option available, the emptyMessage/loader is never displayed.  I should have called this out in the description.  I thought about hacking around it, but I think that will make things worse.  We need to circle back with UX, clean up this interaction and refactor these typeaheads.

2021-03-03 11:42 UTC, bkemper commented on src/pages/reportBuilder/components/CompareByForm/Typeahead.js
> +        item,
I'm open for suggestions.  I guess it is the duplication with "content" and "item.value" that is funny?  In the initial construction of this array, I was trying to prevent attribute logic by rendering a common structure that could then be easily filtered and enriched with `getItemProps`.

2021-03-03 11:43 UTC, bkemper commented on src/pages/reportBuilder/components/CompareByForm/Typeahead.js
> +                {items.length ? (
Is that safer or should I change this to `items.lenght > 0`?

2021-03-03 11:45 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +      cy.findByRole('option', { name: new RegExp(text) })
😊

2021-03-03 11:55 UTC, bkemper commented on src/pages/reportBuilder/components/ReportOptions.js
> +          <ScreenReaderOnly>Report Options</ScreenReaderOnly>
I fixed this and remembered that `Drawer.Header` renders an h2.

2021-03-03 12:07 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +      cy.findByRole('option', { name: new RegExp(text) })
Actually, this is catching a bug.

<img width="416" alt="Screen Shot 2021-03-03 at 6 59 50 AM" src="https://user-images.githubusercontent.com/1335605/109802652-17ffb900-7bee-11eb-99cc-8f4fd32d6d87.png">

2021-03-03 15:12 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +      cy.findByRole('option', { name: new RegExp(text) })
I added some additional logic to improve matching on real items.

2021-03-03 21:25 UTC, nicklemmon approved these changes
@bkemper I added a few comments in spots, but nothing that really holds this one back. 👍

2021-03-03 21:27 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +    it('does not render after the user clear invalid, duplicated filters', () => {
😊

2021-03-03 21:35 UTC, bkemper commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> +          cy.findByRole('button', { name: 'Remove Filter' }).click();
My `causeDuplicationError` change to use subaccount forced me.  This was changing the compare select from contains to equals.  Subaccount only supports equals, so I decided to just remove it instead of changing the compare to trigger the reevaluation.

2021-03-03 21:53 UTC, merged