SA-1997: Add
SparkPost/2web2ui pull request #2086
Opened 2021-02-26 13:47 UTC by PatrickSison

### What Changed

- Added tooltip section for industry benchmark
- Added average in aggregate section
- Added area in chart for industry benchmark

### How To Test

- Go to appteam account
- Enable inbox folder rate metric
- Verify that the inbox folder rate appears

### To Do

- [ ] Address feedback
- [ ] Add integration testing?
- [ ] Add unit testing?

### Notes
- A bit hard to do unit testing around recharts
- Integration testing a bit difficult as well until the parts... integrated (SA-1993)

2021-03-02 16:23 UTC, kchu1337 requested changes

2021-03-02 16:23 UTC, kchu1337 commented on src/hooks/reportBuilder/useIndustryBenchmark.js
> +      return data;
Just a little unclear. If it's loading or error, would it return old data?

2021-03-03 15:27 UTC, PatrickSison commented on src/pages/reportBuilder/context/ReportBuilderContext.js
> +  industryCategory: 'all',
I'm cool with that structure. Will update as discussed

2021-03-03 15:38 UTC, PatrickSison commented on src/helpers/api/metrics.js
> +    url: `${BENCHMARK_BASE_URL}/inbox-rate`,
Agreed. I'll leave as now, but should be minor change once we start getting more benchmarks

2021-03-04 15:07 UTC, PatrickSison commented on src/hooks/reportBuilder/useIndustryBenchmark.js
> +  }, [options, formattedMetrics]);
Wouldn't it just depend on the object that's passed in to the dependency array?

2021-03-04 15:15 UTC, PatrickSison commented on src/components/reportBuilder/AggregatedMetrics.js
> +  const transformedData = transformData([data[0]], aggregatedMetrics);
This is for the rate calculations

2021-03-04 15:16 UTC, PatrickSison commented on src/components/reportBuilder/AggregatedMetrics.js
> +            {hasData &&
Because of the way that we disable the requests if the metrics come through, this is to "clear" data if all the metrics are removed without rendering this section of data

2021-03-04 15:16 UTC, PatrickSison commented on src/hooks/reportBuilder/useIndustryBenchmark.js
> +      return data;
It's more of the reverse. I only want to do the extra filtering/processing on the data once it's ready

2021-03-05 15:01 UTC, kchu1337 commented on src/hooks/reportBuilder/useIndustryBenchmark.js
> +  }, [options, formattedMetrics]);
UseEffect compares by reference. 
If you add these 
```js
useEffect(() => {
    console.log('JSON', JSON.stringify(options))
  }, [JSON.stringify(options)]);

  useEffect(() => {
    console.log(' normal', options)
  }, [options]);
  ```
  The second one will run more times.

2021-03-05 15:15 UTC, PatrickSison commented on src/components/reportBuilder/AggregatedMetrics.js
> +            {hasData &&
React-query doesn't have a way right now to reset if we chose to disable the request, so for now, we ignore the cached data

2021-03-05 15:15 UTC, PatrickSison commented on src/hooks/reportBuilder/useIndustryBenchmark.js
> +  }, [options, formattedMetrics]);
Oh, I got it. I forgot that I did a spread for the declaration of the options object.

2021-03-08 15:09 UTC, kchu1337 commented on src/components/reportBuilder/Charts.js
>    const chartData = useMemo(() => {
I'm seeing this function being run multiple times. It may not be getting memoized properly. Trying to figure out why.

2021-03-08 15:14 UTC, kchu1337 commented on src/components/reportBuilder/Charts.js
>    const chartData = useMemo(() => {
nvm. It's working fine.

2021-03-08 15:23 UTC, kchu1337 approved these changes

2021-03-08 16:00 UTC, merged