SA-2207: Deleted old summary report code
SparkPost/2web2ui pull request #2093
Opened 2021-03-02 14:51 UTC by PatrickSison

### What Changed

- Remove old Summary report code
- Rename V2 functions to regular function names

### How To Test

- Verify the app works as expected
- Verify that the URLs still work as expected

### To Do

- [ ] Address feedback

2021-03-03 14:33 UTC, PatrickSison commented
@nicklemmon I think this is ready for a pass now

2021-03-03 14:36 UTC, PatrickSison commented on cypress/tests/integration/signals-analytics/analytics-report/bounceReasonTable.spec.js
> +    cy.wait(['@getDeliverability', '@getDeliverability', '@getTimeSeries', '@getTimeSeries']);
Not sure how these were passing before, or what changed. It was getting caught on the previous request, but the number of requests still seem appropriate

2021-03-03 14:36 UTC, PatrickSison commented on src/components/charts/LineChart.js
> +  Area,
Chart stuff irrelevant from SA-1997. Merged it in to this though as it had some code detaching from the summaryReport action/reducers

2021-03-03 14:36 UTC, PatrickSison commented on src/components/charts/LineChart.js
> +  Area,
I might actually remove it because then that means this is blocked by SA-1997... I'll just have to make the same changes manually

2021-03-04 16:03 UTC, PatrickSison commented on src/components/reportBuilder/Tooltip.js
> +  const industryRate = payload.find(entry => entry.dataKey === 'industry_rate');
All the chart stuff irrelevant. Will remove for the sake of this PR

2021-03-04 16:03 UTC, PatrickSison commented on src/helpers/api/metrics.js
> +const BENCHMARK_BASE_URL = `${METRICS_BASE_URL}/benchmarks`;
SA-1997, not this PR

2021-03-04 16:03 UTC, PatrickSison commented on src/helpers/tests/__snapshots__/metrics.test.js.snap
> +  "query_filters": "{\\"groupings\\":[{\\"value\\":{\\"0\\":{\\"0\\":\\"g\\"},\\"1\\":{\\"0\\":\\"m\\"},\\"2\\":{\\"0\\":\\"a\\"},\\"3\\":{\\"0\\":\\"i\\"},\\"4\\":{\\"0\\":\\"l\\"},\\"5\\":{\\"0\\":
😱

2021-03-04 16:03 UTC, PatrickSison commented on src/pages/reportBuilder/components/tabs/DelayReasonsTab.js
> +    select: data => data[0],
This is the part that was broken before. Aggregate data comes in an array (although because it's singular, really it should be an object 🤷 )

2021-03-04 16:03 UTC, PatrickSison commented on src/selectors/bounceReport.js
> +import { createSelector } from 'reselect';
The selectors in this file are still being used. Maybe I can move them over to helper functions? Really it's to help pre-format some data for the bounce reasons table

2021-03-08 14:20 UTC, nicklemmon requested changes
@PatrickSison I have a few comments for you - though I don't really want to proceed with this one until the base branch is merged.

Let me know if you have any questions.

2021-03-08 14:39 UTC, PatrickSison commented on src/helpers/tests/reports.test.js
> +        expect(reports.parseSearch(opts.search)).toEqual(expect.objectContaining(opts.match));
You can assert that it's a specific part of the object (like the object contains a certain set of key/values (rather than matching the whole exact object). It's useful, but maybe that's bad practice? Not sure.

2021-03-08 14:40 UTC, PatrickSison commented on src/pages/dashboardV2/DashboardPageV2.js
> -  useEffect(() => {
Yup

2021-03-08 14:40 UTC, PatrickSison commented on src/helpers/tests/__snapshots__/reports.test.js.snap
> +        "undefined": Object {
Yeah, that ain't good lol

2021-03-08 18:05 UTC, PatrickSison commented on src/pages/reportBuilder/ReportBuilder.js
> -  }, [refreshReportBuilder, reportOptions, isEmpty]);
I think the only thing this did was make the report options still available for anything still tied to redux (so now obsolete)

2021-03-08 18:53 UTC, nicklemmon commented on src/pages/reportBuilder/ReportBuilder.js
> +                <Charts metrics={processedMetrics} to={to} yScale="linear" />
Are any of these props being used by the component? I don't think so - it looks like it's all being derived from context.

2021-03-08 18:53 UTC, nicklemmon commented on src/pages/subaccounts/components/test/SubaccountCreateForm.test.js
> +  wrapper.setProps({ ipPools: ['salt water'] });
Not sure why some of these are updated as a part of this PR?

2021-03-08 18:53 UTC, nicklemmon commented on src/helpers/tests/__snapshots__/metrics.test.js.snap
> +  "query_filters": "{\\"groupings\\":[{\\"value\\":{\\"0\\":{\\"0\\":\\"g\\"},\\"1\\":{\\"0\\":\\"m\\"},\\"2\\":{\\"0\\":\\"a\\"},\\"3\\":{\\"0\\":\\"i\\"},\\"4\\":{\\"0\\":\\"l\\"},\\"5\\":{\\"0\\":
@PatrickSison Not sure if you saw my comment - did this snapshot find a bug? ☝️

2021-03-08 18:55 UTC, PatrickSison commented on src/pages/subaccounts/components/test/SubaccountCreateForm.test.js
> +  wrapper.setProps({ ipPools: ['salt water'] });
When merging master into this, I guess the linter picked up on files committed that weren't linted prettified correctly?

2021-03-08 18:55 UTC, PatrickSison commented on src/pages/subaccounts/components/test/SubaccountCreateForm.test.js
> +  wrapper.setProps({ ipPools: ['salt water'] });
I think. I have no idea why else

2021-03-08 19:01 UTC, nicklemmon requested changes
@PatrickSison Another pass - I know you didn't quite get to the previous round of feedback but I saw a few other things while I was here - getting close on this one 👍

2021-03-08 19:01 UTC, nicklemmon commented on src/pages/reportBuilder/components/tabs/DelayReasonsTab.js
> +function useQueriesWithComparison(comparison) {
Or is this 2 divided by the overall number of delays in the time range?

2021-03-08 21:47 UTC, PatrickSison commented on src/pages/reportBuilder/components/tabs/DelayReasonsTab.js
> +function useQueriesWithComparison(comparison) {
2 over the total number in the time range. Probably a little confusing with the word `Total` in the previous column

2021-03-09 14:11 UTC, PatrickSison commented on src/helpers/tests/__snapshots__/metrics.test.js.snap
> +  "query_filters": "{\\"groupings\\":[{\\"value\\":{\\"0\\":{\\"0\\":\\"g\\"},\\"1\\":{\\"0\\":\\"m\\"},\\"2\\":{\\"0\\":\\"a\\"},\\"3\\":{\\"0\\":\\"i\\"},\\"4\\":{\\"0\\":\\"l\\"},\\"5\\":{\\"0\\":
Yeah, with the current behavior. This function as is hasn't been providing default `to` or `from` anymore.

2021-03-10 14:24 UTC, nicklemmon approved these changes
@PatrickSison 👍  Looks good. Happy to see all the red in this PR.

2021-03-10 15:47 UTC, merged