SA-2211 - (UI) Add missing integration tests for all filter and comparison types
SparkPost/2web2ui pull request #2105
Opened 2021-03-08 16:54 UTC by nicklemmon

[SA-2211](https://sparkpost.atlassian.net/browse/SA-2211)

### What Changed

- Adds a new Cypress-specific configuration array used to drive tests in both the compare by and filters form specs

### How To Test

- Verify tests adequately verify the I/O behavior for the filters form and the compare by form

### To Do

- [ ] Incorporate feedback

2021-03-12 16:00 UTC, kchu1337 requested changes
Minor things. Leave a comment if the changes I requested aren't necessary or possible.

2021-03-12 16:00 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> -    beforeEach(() => navigateToForm());
Is there a reason for this?

2021-03-12 17:56 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js
> -    beforeEach(() => navigateToForm());
in general, `beforeEach` causes confusing for people entering a new test - the behavior within a test case isn't entirely available within the closure. Intellisense can't help you figure out what's going on, etc.

2021-03-12 17:58 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +      FILTER_OPTIONS.forEach(option => {
if it's within a new test case (i.e., within an `it()` callback) then there isn't a way to avoid re-visiting the page cleanly. In general, the Cypress team encourages writing longer tests with frequent assertions anyways so this sort of fits that bill?

Is your concern the length of the test? I could be missing something from your comment.

2021-03-12 17:58 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +        cy.wait(`@${option.requestAlias}`);
This is enough to assert the call to the endpoint was made - though it doesn't verify things like parameters that may be passed to said request. That could be helpful. Would that be worth adding somehow?

2021-03-12 18:53 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +      FILTER_OPTIONS.forEach(option => {
Yeah. Ideally it wouldn't need to revisit the page each time. Up to you if you want to update it. If there's a new `it` for each filter, it would be easier to tell when one filter breaks vs the whole test failing.

2021-03-12 18:56 UTC, kchu1337 commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +        cy.wait(`@${option.requestAlias}`);
I think it might be worth it to verify that the match parameter is correct. Although not all of them use match iirc.

2021-03-15 14:05 UTC, nicklemmon commented on cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js
> +      FILTER_OPTIONS.forEach(option => {
I tried it out and it works. Nice. Didn't know that was possible.

2021-03-15 14:31 UTC, nicklemmon commented
@kchu1337 Ready for another pass - I ended up implementing both of your recommendations 👍

2021-03-15 18:50 UTC, kchu1337 approved these changes

2021-03-15 18:59 UTC, merged