SA-2247: Remove most of inbox placement pages
SparkPost/2web2ui pull request #2110
Opened 2021-03-09 14:51 UTC by PatrickSison

### What Changed

- Removed inbox placement pages
- Separated seedlist page
- Moved seedlist page to `Configuration` top level nav

### How To Test

- Go to an account
- Verify inbox placement nav item no longer exists
- Verify that the Seedlist page is under the configuration nav item
- Verify that the seedlist page still is under the inbox placement feature flag

### To Do

- [ ] Address feedback

2021-03-10 20:45 UTC, shrirupa commented
<img width="315" alt="Screen Shot 2021-03-10 at 3 45 17 PM" src="https://user-images.githubusercontent.com/4179337/110695261-a6100c80-81b7-11eb-83c8-629562247ad2.png">
does this description need to change too ?

2021-03-10 20:50 UTC, shrirupa commented on src/config/routes/inboxPlacement.js
> +    supportDocSearch: 'seedlis4t',
typo may be 'seedlist' ?

2021-03-10 20:51 UTC, shrirupa commented on src/pages/inboxPlacement/SeedListPage.js
> +  return <Page title="Seedlist">{isHibanaEnabled ? renderHibana() : renderOG()}</Page>;
upto you but we can remove the isHibanaEnabled check now 🙂

2021-03-10 20:56 UTC, shrirupa commented on src/selectors/inboxPlacement.js
>    seeds.find(seed => endsWith(seed, 'seed.sparkpost.com')),
not sure if we can remediate this Codeql warning 🤷  may be just ignore it.

2021-03-10 20:57 UTC, shrirupa reviewed
just had a few comments, overall looks good!

2021-03-11 14:10 UTC, shrirupa commented on src/selectors/inboxPlacement.js
>    seeds.find(seed => endsWith(seed, 'seed.sparkpost.com')),
may be moving this to constants file can help

2021-03-11 17:01 UTC, PatrickSison commented on src/config/routes/inboxPlacement.js
> +    supportDocSearch: 'seedlis4t',
Oops typo

2021-03-12 19:30 UTC, shrirupa requested changes
![Screen Shot 2021-03-12 at 2 29 50 PM](https://user-images.githubusercontent.com/4179337/110989151-768c0c00-833f-11eb-9fa5-7409334227ee.png)
Sorry didn't notice this earlier, but that bottom subnav disappears when seedlist is clicked

2021-03-16 16:59 UTC, shrirupa commented on src/config/routes/signals.js
> +    subcategory: 'Signals Integration',
🎉

2021-03-16 16:59 UTC, shrirupa approved these changes
Looks good to me!

2021-03-16 17:55 UTC, merged