FE-1369 - Add custom useSparkPostMutation hook
SparkPost/2web2ui pull request #2120
Opened 2021-03-11 19:16 UTC by nicklemmon

[FE-1369](https://sparkpost.atlassian.net/browse/FE-1369)

### What Changed

- Adds supporting Cypress tests for the Suppressions create page
- Adds an index file for typeahead components for easier exporting
- Adds `useSparkPostMutation` hook

### How To Test

- TBD 🚧

### To Do

- [ ] Refactor Suppression create page to use the new `useSparkPostMutation` hook
- [ ] Add supporting Jest tests for `useSparkPostMutation`

2021-03-11 19:16 UTC, nicklemmon commented on cypress/tests/integration/recipients/suppressions/createPage.spec.js
> +    cy.findByRole('heading', { name: 'Add Suppressions', level: 1 }).should('be.visible');
The `level` option here makes sure the heading hierarchy is correct, in this case an `h1`.

2021-03-11 19:17 UTC, nicklemmon commented on src/config/routes/index.js
> +    title: 'Add Suppressions',
The `<title>` should align with the `<h1>` on the page.

2021-03-15 19:36 UTC, nicklemmon commented on src/actions/abTesting.js
> +import { setSubaccountHeader } from 'src/helpers/subaccounts';
Just changed this import here

2021-03-15 19:37 UTC, nicklemmon commented on src/__testHelpers__/TestApp.js
> +      <GlobalAlertWrapper />
Global snackbars were not rendering in a virtual DOM/RTL environment until this was added.

2021-03-15 19:38 UTC, nicklemmon commented on package.json
> +    "react-query": "^3.12.1",
Slightly out of date on both of these - went ahead and upgraded.

The `react-hook-form` upgrade includes a new hook - `useController` which I ended up leveraging.

2021-03-15 19:38 UTC, nicklemmon commented on src/actions/helpers/setSubaccountHeader.js
> -import _ from 'lodash';
Didn't actually delete this, just moved it since this helper is not specific to Redux actions.

2021-03-15 19:39 UTC, nicklemmon commented on src/actions/templates.js
> +    );
All Prettier!

2021-03-15 19:39 UTC, nicklemmon commented on src/actions/templates.js
> +import { setSubaccountHeader } from 'src/helpers/subaccounts';
A lot of Prettier formatting here - only changed the import here.

2021-03-15 19:40 UTC, nicklemmon commented on src/components/typeahead/index.js
> +export { default as TypeSelect } from './TypeSelect';
We do lots of very deep importing from this folder. I thought this would help improve the DX.

2021-03-15 19:41 UTC, nicklemmon commented on src/helpers/api/defaultQueryFn.js
> +    data,
Until now, we weren't supporting passing things to the request `body` - but now we are since we can now do "PUT" and "POST" requests.

2021-03-15 19:41 UTC, nicklemmon commented on src/helpers/api/suppressions.js
> +export function createOrUpdateSuppressions({ recipients = [], subaccount }) {
This is almost exactly the same as the equivalent Redux action.

2021-03-15 19:42 UTC, nicklemmon commented on src/helpers/api/suppressions.js
> +  const sanitizedRecipients = recipients.map(
Should all this data manipulation happen at this layer? We don't tend to do this this way.

2021-03-15 19:42 UTC, nicklemmon commented on src/helpers/subaccounts.js
> +export function setSubaccountQuery(id) {
Just changed from `const` to `function`

2021-03-15 19:42 UTC, nicklemmon commented on src/helpers/subaccounts.js
> +export function setSubaccountHeader(subaccount = null) {
Migrated from the other helpers file

2021-03-15 19:43 UTC, nicklemmon commented on src/helpers/tests/subaccounts.test.js
> +    });
Migrated from another file

2021-03-15 19:47 UTC, nicklemmon commented on src/hooks/useSparkPostQuery/useSparkPostQuery.mdx
> -# useSparkPostQuery
This was somehow duplicated? The docs now live at `src/hooks/api/apiHooks.mdx`

2021-03-15 19:54 UTC, nicklemmon commented on src/pages/suppressions/components/AddForm.js
> +import { SubaccountTypeaheadController } from 'src/components/reactHookFormControllers';
No point in reading the diff of the file here - I completely started from scratch, using the old component merely as a reference.

2021-03-15 19:54 UTC, nicklemmon commented on src/pages/suppressions/components/AddForm.js
> +function mapDataToRecipients(data) {
Should this helper live elsewhere? Maybe as a global helper?

2021-03-19 13:23 UTC, nicklemmon commented
@PatrickSison This one is a lot bigger than I intended it to be. Let me set up a walkthrough so I can give you a lay of the land before you dive in.

2021-03-25 14:12 UTC, PatrickSison requested changes
I think there's one decent change, but everything else looks really good. I like the approach to the refactor of building the necessary integration test first and then updating the feature 👍

2021-03-25 14:12 UTC, PatrickSison commented on src/helpers/tests/subaccounts.test.js
> +      expect(subaccounts.setSubaccountHeader({ id: 1 })).toEqual({ 'x-msys-subaccount': 1 });
Still a bit weird that we do a decent amount of "overloading" for these functions for different formats.

2021-03-25 14:12 UTC, PatrickSison commented on cypress/tests/integration/recipients/suppressions/createPage.spec.js
> +    cy.findByRole('heading', { name: 'Add Suppressions', level: 1 }).should('be.visible');
Neat. Didn't know that

2021-03-25 14:12 UTC, PatrickSison commented on cypress/tests/integration/recipients/suppressions/createPage.spec.js
> +const PAGE_URL = '/lists/suppressions/create';
Awesome tests, and a good thing to test before making the actual changes to keep tests in line

2021-03-25 14:12 UTC, PatrickSison commented on src/components/globalAlert/Alert.js
> +        <ButtonLink className={styles.Details} onClick={this.handleDetails}>
👏

2021-03-25 14:12 UTC, PatrickSison commented on src/config/routes/index.js
> +    title: 'Add Suppressions',
Agreed. Do we need to do with breaking down header (like domains has `Add Domains | Domains | SparkPost`

2021-03-25 14:12 UTC, PatrickSison commented on src/pages/suppressions/components/AddForm.js
> +function mapDataToRecipients(data) {
Yeah, I think some of this should be combined (or at least live closer) with the other data processing happening inside `src/helpers/api/suppressions`. It's feels a bit more intuitive that they live together (and since nowhere else is using the in-between stage of that data)

2021-03-31 13:06 UTC, nicklemmon commented on src/pages/suppressions/components/AddForm.js
> +    return mutation.mutate({ recipients, subaccount });
Yeah all of this terminology borrowed from Apollo/GraphQL is a little odd.

2021-03-31 13:31 UTC, nicklemmon commented on src/config/routes/index.js
> +    title: 'Add Suppressions',
Technically yes - that would be easy enough to accomplish while we're here.

2021-03-31 14:15 UTC, nicklemmon commented
@PatrickSison Ready for another pass when you have time.

2021-03-31 17:21 UTC, shrirupa commented on src/components/reactHookFormControllers/ComboBoxTypeaheadController.js
> +export function ComboBoxTypeaheadController(props) {
curious to understand why this was renamed ?

2021-04-01 19:58 UTC, shrirupa commented on src/pages/suppressions/components/AddForm.js
> +            label="Email Address"
required * seems to be missing from Email Address and Type. Is that something UX wants to keep ?

2021-04-01 20:13 UTC, shrirupa commented on src/pages/suppressions/components/AddForm.js
> +          Add / Update
A small bug - Add/ Update button is disabled on the first load but after you fill the form completely and then clear out the form again, the button still remains enabled.

2021-04-01 20:21 UTC, shrirupa commented on src/pages/suppressions/components/AddForm.js
> +          Add / Update
Looks like this exists in staging too, so I would say don't worry about it in this PR.

2021-04-01 20:26 UTC, shrirupa commented on src/helpers/api/suppressions.js
> +  const sanitizedRecipients = recipients.map(
I think you are right this looks like it should be separated out, may be into a data formatting helper formDatatoApiFormat

2021-04-01 20:27 UTC, shrirupa commented on cypress/tests/integration/recipients/suppressions/createPage.spec.js
> +        expect(xhr.request.headers['x-msys-subaccount']).to.equal(101);
👏

2021-04-01 20:31 UTC, shrirupa commented on src/helpers/api/suppressions.js
> +  const sanitizedRecipients = recipients.map(
actually isn't this logic similar to toRecipientArray helper that you already have.

2021-04-02 16:54 UTC, shrirupa approved these changes
Looks good to me! verified that suppressions create page worked the same as before and changing imports has also not broken the build.

2021-04-02 17:05 UTC, merged