AC-1864 - Webhook Form Fields
SparkPost/2web2ui pull request #2125
Opened 2021-03-16 16:18 UTC by nstanard

https://sparkpost.atlassian.net/browse/AC-1864

### What Changed

- Added ids to the webhook form fields.

### How To Test

- Test the webhook form submit event calls the `src/components/tracking/form` tracking handler.
- Test create AND edit for webhooks.
- Double check that all fields have the right attributes so we can send that info through to segment in a follow on ticket.

See original ticket for understanding elements/attributes: https://sparkpost.atlassian.net/browse/AC-1864

### To Do

- [ ] Feedback

### Important Notes:
 - `src/components/tracking/form` component has logging in place to verify the submit event fires: 
 
![image](https://user-images.githubusercontent.com/4204806/111343118-1d76ed80-8649-11eb-804b-51744d560c0a.png)

Create Submit:
![image](https://user-images.githubusercontent.com/4204806/111343233-367f9e80-8649-11eb-9774-e2a360dc0546.png)

Edit Submit:
![image](https://user-images.githubusercontent.com/4204806/111343150-25369200-8649-11eb-9622-fdc83afe9e48.png)

2021-03-16 16:53 UTC, nicklemmon requested changes
Left a few comments.

Also, it would be worth changing these `id` values - they are getting passed in a way that looks confusing because of the use of the `.` and if you needed to use any DOM manipulation browser APIs, it would cause some problems:
<img width="368" alt="Screen Shot 2021-03-16 at 12 52 11 PM" src="https://user-images.githubusercontent.com/3613392/111348407-8c0e7800-8656-11eb-9a93-b9d374687bc4.png">

For example, `document.querySelector('#events.delay')` does not grab the element correctly because it thinks the `.delay` refers to the `class` attribute rather than the `id`.

2021-03-16 16:53 UTC, nicklemmon commented on src/pages/webhooks/components/Fields.js
> +          More information.
It's weird from a JSX standpoint, but the period should be outside of the link - the text is clickable not the punctuation in the sentence.

2021-03-16 16:53 UTC, nicklemmon commented on src/pages/webhooks/components/Fields.js
> +        <TranslatableText>
👍

2021-03-16 16:53 UTC, nicklemmon commented on src/pages/webhooks/components/tests/__snapshots__/Fields.test.js.snap
>    component={[Function]}
Snapshot test should just be deleted at this point - this is pretty useless. Even slowed you down on implementing this ticket!

2021-03-16 16:53 UTC, nicklemmon commented on src/pages/webhooks/components/Fields.js
> +          More information.
https://ux.stackexchange.com/questions/17331/should-a-full-sentence-html-link-include-the-period-in-the-linked-text#:~:text=Use%20a%20period%20(or%20other,don't%20link%20the%20period.

2021-03-16 17:03 UTC, nstanard commented on src/pages/webhooks/components/tests/__snapshots__/Fields.test.js.snap
>    component={[Function]}
I actually don't mind the snapshots. Might delete here later when I have time.

2021-03-18 14:15 UTC, nstanard commented
> Left a few comments.
> 
> Also, it would be worth changing these `id` values - they are getting passed in a way that looks confusing because of the use of the `.` and if you needed to use any DOM manipulation browser APIs, it would cause some problems:
> <img alt="Screen Shot 2021-03-16 at 12 52 11 PM" width="368" src="https://user-images.githubusercontent.com/3613392/111348407-8c0e7800-8656-11eb-9a93-b9d374687bc4.png">
> 
> For example, `document.querySelector('#events.delay')` does not grab the element correctly because it thinks the `.delay` refers to the `class` attribute rather than the `id`.

I'd actually prefer we write these locations up and limit the changes we make for the scope of the label/id work. For this PR I did add an id override but I don't think I'll do that for all of them. If the form fields have the right attributes and labels I'll leave them alone.

2021-03-18 14:36 UTC, nstanard commented on src/pages/webhooks/components/WebhookForm.js
> +              id={key}
We should probably decide if we want to enforce `id` attributes on `<Field` components or let redux-form set them via the `name=` attribute. Turns out that I don't actually have to add these id attributes - the IDs are already there.

![image](https://user-images.githubusercontent.com/4204806/111644030-71124400-87cd-11eb-8d19-66a4ac25c0e9.png)

2021-03-18 14:39 UTC, nstanard commented on src/pages/webhooks/components/WebhookForm.js
> +              id={key}
So basically, the changes on this PR aren't really needed. (but has helped me better understand the actual scope of work needed to make sure we are tracking the form fields properly)

2021-03-18 14:44 UTC, nstanard commented
This form actually has all the ids/names and labels as far as I can tell. They may not be formatted in an ideal way but they are making it through to the tracking submit event so I'm closing this and using it as a base of what to look for as I make my way through all the Form instances.

2021-03-18 14:45 UTC, closed without merging