FE-1414 - Download CSV button
SparkPost/2web2ui pull request #2131
Opened 2021-03-18 16:32 UTC by nstanard

### What Changed

- Added Download CSV button to domain tabs 

### How To Test

- Visit sending, bounce, and tracking domain tabs with and without pagination visible.
- Filter and sort the table results and test the CSV Download for each tab.

### To Do

- [ ] Feedback

2021-03-18 16:33 UTC, nstanard commented on src/pages/domains/components/styles.js
> +export const PaginationDownloadButtonWrapper = styled.div`
@jonambas Do you have an alternate way to do this with Matchbox components?

2021-03-18 16:40 UTC, nstanard commented on src/pages/domains/components/styles.js
> +export const PaginationDownloadButtonWrapper = styled.div`
Scratch that, used built in pagination save as by mapping the table instance rows.

2021-03-18 20:23 UTC, nicklemmon requested changes
@nstanard Your changes work - I left one comment, re: variable naming.

Adding automated testing behind this is also needed. It looks like there is a Cypress test that was avoiding testing a downloaded file due to a missing feature in some of the billing page specs (`cypress/tests/integration/accounts/billing/billingPage.spec.js`).

The good news is our current version of Cypress now supports file downloading. They even have a testing recipe to validate file content if you want to go that far:
https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__download/cypress/integration/local-download-spec.js

At the very least, testing that the button is there for each tab is important.

Thanks!

2021-03-18 20:23 UTC, nicklemmon commented on src/pages/domains/components/TrackingDomainsTab.js
> +
👾

2021-03-18 20:23 UTC, nicklemmon commented on src/pages/domains/components/SendingDomainsTab.js
> +        data={tableInstance.rows.map(i => i.original)}
Mind using a more descriptive variable name than `i` here? Maybe `row`? Or you could always destructure it:
```js
tableInstance.rows.map(({ original }) => original));
```

2021-03-22 16:55 UTC, nstanard commented
> @nstanard Your changes work - I left one comment, re: variable naming.
> At the very least, testing that the button is there for each tab is important.
> 
> Thanks!

I did what I could with the time I had available but the actual download test will have to wait for another day. We should probably write that up to add some cypress helpers/tasks/commands to make checking downloaded CSV files easier.

2021-03-22 17:10 UTC, nicklemmon approved these changes
Looks good to me!

2021-03-22 17:10 UTC, nicklemmon commented on cypress/plugins/index.js
> +    },
This is cool!

2021-03-22 17:32 UTC, merged