AC-1911 - Fix Safari SSO redirect issue
SparkPost/2web2ui pull request #2134
Opened 2021-03-18 21:32 UTC by shrirupa

AC-1911 - Fix Safari SSO redirect issue

### What Changed

- Replaced strict with lax in default config [May be need to check with security for this]
- Made SSOPage to be a functional component

### How To Test

- Point openresty to uat.
- please let me know when you test this I can run accusers locally(could be an issue with aws persimissions to run this) and also share with you my okta creds to test this.

### To Do

- [ ] Address feedback

2021-03-23 20:38 UTC, nicklemmon requested changes
@shrirupa Overall looks good - left a tiny bit of feedback.

Thanks.

2021-03-23 20:38 UTC, nicklemmon commented on src/pages/sso/tests/__snapshots__/SSOPage.test.js.snap
> +exports[`SSOPage renders correctly 1`] = `<Fragment />`;
Is this really necessary? 🤷

2021-03-23 20:38 UTC, nicklemmon commented on src/helpers/authCookie.js
>  }
I see how you handled it here - it would be worth adding additional testing around this change. You would have to get a mock return value from `is.safari()` but it would definitely be good to make sure that's covered.

2021-03-24 17:15 UTC, shrirupa commented on src/pages/sso/tests/__snapshots__/SSOPage.test.js.snap
> +exports[`SSOPage renders correctly 1`] = `<Fragment />`;
no, I just left it there when I changed to functional component. I can remove it though.

2021-03-24 18:22 UTC, nicklemmon approved these changes
@shrirupa Looks good to me! Nice testing.

2021-03-24 19:40 UTC, merged