WIP FE-1423 Replace desktop account dropdown button
SparkPost/2web2ui pull request #2149
Opened 2021-03-29 14:18 UTC by jonambas

Note: Give your PR a short title. Something like "_TICKET NUMBER: feature description_" is good.

### What Changed

- What changes did you make to satisfy the AC?
  > Outline changes to user flows, any surprising architectural decisions Alignment between PR
  > commits and this section helps your reviewers.

### How To Test

- Describe any special dev environment setup required.
  > Anything outside basic hamurai-managed stuff counts as "special".
- Describe any special accounts that need to be tested.
  > Include any specific user roles and necessary feature flags.

### To Do

- [ ] Any outstanding tasks go here
  > Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)

2021-03-31 14:54 UTC, jonambas commented on src/components/hibana/DesktopNavigation.js
> +            <Inline space="100">
Decreased spacing here to accommodate the larger button size, got the 👍  from UX

2021-03-31 14:55 UTC, jonambas commented on src/components/matchbox/index.js
> +export { Skeleton } from '@sparkpost/matchbox-hibana';
Wasn't sure if this is okay?

2021-03-31 15:01 UTC, jonambas commented on src/components/hibana/DesktopAccountButton.js
> +    return <Skeleton.Box height="650" width="900" borderRadius="pill" />;
Button was disabled when currentUser is loading so I figured it would be fine to replace with a Skeleton component – let me know if this is alright

2021-03-31 15:05 UTC, nicklemmon requested changes
@jonambas I left a few comments for you. It's good to see you working in the app directly for this kind of thing. Good stuff 👍

2021-03-31 15:05 UTC, nicklemmon commented on src/components/hibana/DesktopAccountButton.js
> +  ${({ isOpen, theme }) => (isOpen ? `background: ${theme.colors.gray[700]};` : '')}
to combine it with the other `background` property, you could use a ternary. Up to you if you want to:
```js
background: ${({ isOpen, theme }) => background: isOpen ? theme.colors.gray[700] : theme.colors.brand.orange)};
```

2021-03-31 15:05 UTC, nicklemmon commented on src/components/hibana/DesktopAccountButton.js
> +  background: ${({ theme }) => theme.colors.brand.orange};
I'm obviously not a designer on the team, but the orange color makes the button feel very visually dominant to me. It carries a lot of weight:

<img width="1480" alt="Screen Shot 2021-03-31 at 11 04 45 AM" src="https://user-images.githubusercontent.com/3613392/113166653-f7d51100-9210-11eb-838e-b227881ac766.png">

2021-03-31 15:18 UTC, jonambas commented on src/components/hibana/DesktopAccountButton.js
> +const DesktopAccountButton = styled(Box)`
forgot an `as="button"`

2021-03-31 15:19 UTC, jonambas commented on src/components/hibana/DesktopAccountButton.js
> +  background: ${({ theme }) => theme.colors.brand.orange};
Yeah, this was the main issue really – some user's didn't totally understand this was clickable

2021-03-31 15:40 UTC, jonambas commented on src/components/matchbox/Skeleton.js
> +
Let me know if I did this correctly 😬  I modeled this off of the Layout wrapper

2021-03-31 15:51 UTC, jonambas commented
CodeQL checks failed on `src/pages/domains/components/VerifyToken.js` 🤔

2021-03-31 19:03 UTC, nicklemmon commented on src/components/matchbox/Skeleton.js
> +
Nice, this looks good. Eventually we'll replace all these aliased imports `as MatchboxSkeleton` rather than `HibanaSkeleton` but right now the consistency is more important.

2021-03-31 19:04 UTC, nicklemmon commented on src/components/matchbox/Skeleton.js
> +
It would be good to add some simple unit tests to make sure things are passing to the components as expected. There are several examples out there - in general we want to use React Testing Library and not Enzyme for these.

2021-03-31 19:06 UTC, nicklemmon commented on src/components/hibana/DesktopAccountButton.js
> +  background: ${({ theme }) => theme.colors.brand.orange};
Hmm, I would think an orange outline with gray text would help? Or a blue outline with blue text? 🤔 The border radius seems to indicate its clickable to me so I would think the color could be tweaked and still get that effect?

Just my two cents!

2021-03-31 20:40 UTC, jonambas commented on src/components/hibana/DesktopAccountButton.js
> +  background: ${({ theme }) => theme.colors.brand.orange};
Lemme ask the UX team

2021-04-01 14:47 UTC, jonambas commented on src/components/matchbox/Skeleton.js
> +
I couldn't test two of the Skeleton components – see UX-491, they aren't passing through data-id

2021-04-01 18:06 UTC, nicklemmon approved these changes
@jonambas Looks good! 👍

2021-04-01 19:53 UTC, merged